### ISSUE TITLE
Parameterise and clarify magic numbers in tests

### ISSUE THREAD

**Issue by danwt** [cosmos/interchain-security#100]
There are a lot of magic numbers in tests, which is fine until they have to be changed. They should be parameterized away, derived, or commented and named better.

This is mostly an issue because I'm trying to bring more automated tests, which requires a good understanding of parameters. From this I discovered https://github.com/cosmos/interchain-security/issues/99, which might require downstream changes in all our tests - which will be hard to change.

I consider this issue very low priority as it doesn't block us. It's more of a tech debt issue.

**Comment by danwt** [comment]
I can add examples on Monday.

**Comment by smarshall-spitzbart** [comment]
Does this issue still apply? 

Imo unit tests and their values have been clarified pretty well following the PRs that were a part of https://github.com/cosmos/interchain-security/issues/219. 

I still see a couple of hardcoded values in e2e tests like [this ](https://github.com/cosmos/interchain-security/blob/handshake-tests/tests/e2e/slashing_test.go#L415) and [this](https://github.com/cosmos/interchain-security/blob/handshake-tests/tests/e2e/slashing_test.go#L602), but those seem to be arbitrary values just to test a happy path of code.

I'm gonna close this issue, but let's chat and/or open up new issues if there's more specific test values that you want to be clarified or parameterized
