### ISSUE TITLE
Fix leak in unbonding hooks

### ISSUE THREAD

**Issue by danwt** [cosmos/interchain-security#103]
I think there is a leak in the unbonding hooks

The method `DeleteUnbondingIndex` is only called in one branch for each `CanComplete` method

- Undel: https://github.com/cosmos/cosmos-sdk/blob/e75e83fa99fc9ce8ffdf6717f780cd1c78b06ad4/x/staking/keeper/unbonding.go#L279
- Redel: https://github.com/cosmos/cosmos-sdk/blob/e75e83fa99fc9ce8ffdf6717f780cd1c78b06ad4/x/staking/keeper/unbonding.go#L312
- Validator: https://github.com/cosmos/cosmos-sdk/blob/e75e83fa99fc9ce8ffdf6717f780cd1c78b06ad4/x/staking/keeper/unbonding.go#L342

which will leak storage space if the other branch is taken, because the method as a whole is only ever taken _once_ according to the spec

https://github.com/cosmos/ibc/blob/marius/ccv/spec/app/ics-028-cross-chain-validation/technical_specification.md#external-data-structures

**Comment by mpoke** [comment]
@danwt Nice catch. I think the function `DeleteUnbondingIndex` should be called also 

- here for undelegations: https://github.com/cosmos/cosmos-sdk/blob/e75e83fa99fc9ce8ffdf6717f780cd1c78b06ad4/x/staking/keeper/delegation.go#L793
- here for redelegations: https://github.com/cosmos/cosmos-sdk/blob/e75e83fa99fc9ce8ffdf6717f780cd1c78b06ad4/x/staking/keeper/delegation.go#L896
- here for unbonding validators: https://github.com/cosmos/cosmos-sdk/blob/e75e83fa99fc9ce8ffdf6717f780cd1c78b06ad4/x/staking/keeper/validator.go#L441

**Comment by danwt** [comment]
@mpoke I just realised I don't see why for your points above? The `CanComplete`s must be called before reaching any of those code points so we can just delete the index in the `CanComplete` calls. E.g. move the delete calls up 1 parenthesis level. Right?

**Comment by mpoke** [comment]
Fixed by https://github.com/cosmos/cosmos-sdk/pull/12849
