### ISSUE TITLE
Make `UnbondingCanComplete()` simply set `onHold = False` instead of trying to complete immediately

### ISSUE THREAD

**Issue by danwt** [cosmos/interchain-security#104]
There is a pattern used for each of undel, redel, and validator

```
if not matured:
  entry.onHold = False
else:
  // complete now
```

but I think the `// complete now` branch is unneeded and complicates things.

`onHold` is set false in these places

- Undel: https://github.com/cosmos/cosmos-sdk/blob/e75e83fa99fc9ce8ffdf6717f780cd1c78b06ad4/x/staking/keeper/unbonding.go#L256
- Redel: https://github.com/cosmos/cosmos-sdk/blob/e75e83fa99fc9ce8ffdf6717f780cd1c78b06ad4/x/staking/keeper/unbonding.go#L306
- Validator: https://github.com/cosmos/cosmos-sdk/blob/e75e83fa99fc9ce8ffdf6717f780cd1c78b06ad4/x/staking/keeper/unbonding.go#L333

I think we can remove the branching because we don’t need to complete the operation right there. I think it the operations will be completed in the next endBlock anyway (val_state_change.go).

https://github.com/cosmos/cosmos-sdk/blob/e75e83fa99fc9ce8ffdf6717f780cd1c78b06ad4/x/staking/keeper/val_state_change.go#L18

**Comment by danwt** [comment]
@sainoe @mpoke, what do you think?

**Comment by danwt** [comment]
Related 

- https://github.com/cosmos/interchain-security/issues/103

**Comment by sainoe** [comment]
Good catch @danwt ! This assumption seems legit.

Note that the IS existing tests in [x/ccv/provider/unbonding_hook_test.go](https://github.com/cosmos/interchain-security/blob/1eb5b5fd0d3f6fb4b13f76aa0347fd7195947439/x/ccv/provider/unbonding_hook_test.go#L103) will need to be updated. Mostly by adding :
```
s.providerChain.App.EndBlock(abci.RequestEndBlock{})
```
to complete the unbondings.

**Comment by danwt** [comment]
@mpoke responded to this out of band and explained:

The matury queue works such that matured operations are deleted from the queue. This means they will never be revisited after setting `onHold=False`, so the additional explicit completion seems necessary.
