### ISSUE TITLE
Update IBC calls to latest version from ibc-go (v3.0.0) 

### ISSUE THREAD

**Issue by mpoke** [cosmos/interchain-security#107]

**Comment by dusan-ethernal** [comment]
@danwt CosmWasm is using this version: github.com/cosmos/ibc-go/v3 v3.0.0
The method that mismatches is OnChanOpenAck() that, in CosmWasm code, has additional counterpartyChannelID parameter and counterpartyVersion, while IS has only counterpartyMetadata parameter. We are not sure if this is the only difference.

**Comment by danwt** [comment]
In progress PR

- https://github.com/cosmos/interchain-security/pull/149

See

https://github.com/cosmos/interchain-security/blob/3707e45bf596d69a255f0f77b33872fcaf5a7d91/x/ccv/consumer/module.go#L303

It seems we need a different way to get `ProviderFeePoolAddr` and call `SetProviderFeePoolAddrStr` with it, as the data is no longer sent in acks.

**Comment by danwt** [comment]
Done
