### ISSUE TITLE
Clarify the purpose of `Infraction_INFRACTION_UNSPECIFIED`

### ISSUE THREAD

**Issue by AaronKutch** [cosmos/interchain-security#1073]
Previously, it was called `FractionEmpty` but has been recently renamed on the main branch. I happened to notice scrolling over the implementation for other things that `Infraction_INFRACTION_UNSPECIFIED` is treated as a no-op by https://github.com/cosmos/interchain-security/blob/acc494ffea097bfcd31900f7a37044da46700636/x/ccv/consumer/keeper/validators.go#L120 and is treated as invalid by a `ValidateBasic` I see elsewhere in the code . This property is mentioned nowhere and you could easily miss it unless you happen to see that one if statement in the implementation.
All the protobuf documentation says about it is "UNSPECIFIED defines an empty infraction". Based on that, I have expected it simply to mean that the infraction type is unspecified (i.e. if the infraction does not correspond to a double sign or cosmos block downtime, then I should use the unspecified variant). The SDK itself seems to use it like this for a generic slash function with "It specifies no intraction reason". On the ICS side, I see a copy of the function with "This function should not be called anywhere" at the bottom of its description. Why does that exist in the first place if it shouldn't be called, are there any safeguards that could be added? The ICS side also uses it for the same reason in another place "Slash for a standalone chain does not require an infraction reason so we pass in Infraction_INFRACTION_UNSPECIFIED". There is some serious dissonance going on here.
I have been using `Infraction_INFRACTION_UNSPECIFIED` as a stand-in for whenever an infraction was not for a cosmos-level double sign or downtime. Do the other variants get unique treatments as well?
This should be fixed/thoroughly documented in the future, but what should I do about my current usage of this?

**Comment by smarshall-spitzbart** [comment]
Hey @AaronKutch thanks for the info. Personally I'm having a hard time understanding what action you want us to take to resolve this issue. Please use a relevant issue template with succinct answers to fields.

To answer parts of your post:

> Based on that, I have expected it simply to mean that the infraction type is unspecified

This is the correct understanding, I'm not sure what other meaning `stakingtypes.Infraction_INFRACTION_UNSPECIFIED` can take, besides an unspecified infraction. 

> On the ICS side, I see a copy of the function with "This function should not be called anywhere" at the bottom of its description. Why does that exist in the first place if it shouldn't be called

The answer to this question seems to exist in the line above what you've quoted. `ConsumerKeeper must implement StakingKeeper interface`. 

> I have been using Infraction_INFRACTION_UNSPECIFIED as a stand-in for whenever an infraction was not for a cosmos-level double sign or downtime.

Replicated security currently only supports slashing for the infractions specified in the cosmos sdk staking module

**Comment by AaronKutch** [comment]
Thanks, I think the problem is that I don't see any of these distinctions in the high level docs, or at least documentation on the functions or types. Now that I read it over a second time, it appears that adr-002 corresponds to the downtime infraction type, and adr-003 corresponds to the double sign infraction type. I think the developer docs should state explicitly what `Infraction_` type corresponds to what and the specific implications of using it as a parameter. `Infraction_INFRACTION_UNSPECIFIED` isn't touched upon at all and needs to be (such as, is it only useful as a no-op marker?).

**Comment by mpoke** [comment]
@AaronKutch I'm closing this issue as the questions were addressed. Please let us know if you have other questions.
