### ISSUE TITLE
refactor ICS v3 slash packet handling

### ISSUE THREAD

**Issue by MSalopek** [cosmos/interchain-security#1105]
## Problem
A discrepancy in SlashPacket handling was discovered in an ICS v3 release candidate.

The issue is summarized in #1092.

PR #1093 attempts to solve the problem on ICS side, but the fix will not be needed if the change makes it into a cosmos-sdk v47 release.

In case the fix does not make it into cosmos-sdk, the solution to be used in ICS v3 release should be more robust than the one in #1093.

Tracking the issue on cosmos-sdk:
* 

## Closing criteria

A more robust solution would revert to using the same types that were used in ICS v1/2 and move from using `cosmos-sdk/staking` types internally. The change must not break the wire or storage (it must be backward compatible) to avoid painful state migrations on both the consumer and the provider

### Steps:
- [ ] confirm "old" and "new" infraction are only incompatible when marshalled to JSON 
- [ ] confirm "old" and "new" infraction enums are compatible when stored (avoid state breaks, check that "old" stored as proto bytes can be marshalled into "new" proto)
- [ ] use "old" infraciton types used by ICS v1/2
- [ ] change internal slash infraction handling (change all if/else blocks and switch/case blocks)
- [ ] ensure backward compatibility is maintained using e2e tests between ICS v1/2 & ICS v3 provider and consumer

## Problem details

In #1093 the consumer chain will always send slash packets in a format that can be parsed by providers of all ICS versions (v1, v2, v3).  To achieve this, a new proto message was added that is not stored in state but only marshalled to JSON when sending it over the wire (since IBC protocols use JSON byte arrays for packet data).

Provider code was expanded to accept both the v3 and v1 packets. This approach works as a stop-gap, but it would be a lot cleaner if we had a way of unmarshalling packets that does not rely on errors in unmarshalling to determine the correct type.

See example of current implementation:
```golang
func UnmarshalConsumerPacket(packet channeltypes.Packet) (consumerPacket ccv.ConsumerPacketData, err error) {
	// First try unmarshaling into ccv.ConsumerPacketData type
	if err := ccv.ModuleCdc.UnmarshalJSON(packet.GetData(), &consumerPacket); err != nil {
		// If failed, packet should be a v1 slash packet, retry for ConsumerPacketDataV1 packet type
		var v1Packet ccv.ConsumerPacketDataV1
		errV1 := ccv.ModuleCdc.UnmarshalJSON(packet.GetData(), &v1Packet)
		if errV1 != nil {
			// If neither worked, return error
			return ccv.ConsumerPacketData{}, errV1
		}

		// VSC matured packets should not be unmarshaled as v1 packets
		if v1Packet.Type == ccv.VscMaturedPacket {
			return ccv.ConsumerPacketData{}, fmt.Errorf("VSC matured packets should be correctly unmarshaled")
		}

		// Convert from v1 packet type
		consumerPacket = ccv.ConsumerPacketData{
			Type: v1Packet.Type,
			Data: &ccv.ConsumerPacketData_SlashPacketData{
				SlashPacketData: v1Packet.GetSlashPacketData().FromV1(),
			},
		}
	}
	return consumerPacket, nil
}
```

This is the "old" enum definition used by ICS v1/2:
```
// InfractionType indicates the infraction type a validator commited.
// NOTE: ccv.InfractionType to maintain compatibility between ICS versions
// using different versions of the cosmos-sdk and ibc-go modules.
enum InfractionType {
  option (gogoproto.goproto_enum_prefix) = false;

  // UNSPECIFIED defines an empty infraction type.
  INFRACTION_TYPE_UNSPECIFIED = 0 [(gogoproto.enumvalue_customname) = "InfractionEmpty"];
  // DOUBLE_SIGN defines a validator that double-signs a block.
  INFRACTION_TYPE_DOUBLE_SIGN = 1 [(gogoproto.enumvalue_customname) = "DoubleSign"];
  // DOWNTIME defines a validator that missed signing too many blocks.
  INFRACTION_TYPE_DOWNTIME = 2 [(gogoproto.enumvalue_customname) = "Downtime"];
}
```

The code on both the consumer and the provider could be changed to support the "old" enum instead of relying on `cosmos-sdk/x/staking` enum. The `cosmos-sdk/x/staking` enum must still be used when processing evidence - it would have to be converted to the "old" enum.

### Backporting
It is possible that we will need to backport parts of this solution to ICS v1 and v2.

### More details available on cosmos-sdk:
* https://github.com/cosmos/cosmos-sdk/pull/16742
* https://github.com/cosmos/cosmos-sdk/issues/16740

**Comment by MSalopek** [comment]
Issue was put to blocked to allow the situation to resolve.
A draft PR will be created that implements the refactor stated above and used only if the change cannot be accomodated on cosmos-sdk.

**Comment by MSalopek** [comment]
The change will not be accomodated in `cosmos-sdk` since it introduces some overhead. Instead, a more robust solution will be implemented in ICS.

**Comment by mpoke** [comment]
@MSalopek is this issue still relevant?

**Comment by MSalopek** [comment]
It seems that https://github.com/cosmos/interchain-security/pull/1093 is the only solution we needed.

What we did in the end was allow the provider to check which type of slash packet it received and use appropriate marshallers.
