### ISSUE TITLE
Disable messages on consumer chain

### ISSUE THREAD

**Issue by mpoke** [cosmos/interchain-security#115]
Depending on the type of the consumer chain, some messages need to be disabled. 

- [ ] By default, minimum runnable consumer chains (see https://github.com/cosmos/interchain-security/issues/59) MUST have the following messages **_disabled_**:
  - messages for the staking module, i.e., https://docs.cosmos.network/main/modules/staking/03_messages.html
  - messages for the slashing module, i.e., https://docs.cosmos.network/main/modules/slashing/03_messages.html
  - messages for the evidence module, i.e., https://docs.cosmos.network/main/modules/evidence/03_messages.html
  - messages for the distribution module, i.e., https://docs.cosmos.network/main/modules/distribution/04_messages.html
  - messages for the gov module, i.e., https://docs.cosmos.network/main/modules/gov/03_messages.html
  
Addressed by https://github.com/cosmos/interchain-security/pull/272

- [ ] For consumer chains with the "democracy package" installed (see https://github.com/cosmos/interchain-security/issues/66), the following messages should be **_enabled_**:
  - messages for the staking module, directed to the gov-staking module
  - messages for the distribution module, directed to the gov-distribution module
  - messages for the gov module
  
Addresses by https://github.com/cosmos/interchain-security/issues/141

**Comment by jtremback** [comment]
I think this is done
