### ISSUE TITLE
Cover light client equivocation attacks in E2E tests

### ISSUE THREAD

**Issue by sainoe** [cosmos/interchain-security#1180]
## Problem

Currently, the E2E tests are only testing the ICS misbehaviour handling feature by triggering a "lunatic" light client attack.
However, this test case isn't sufficient since only the "equivocation" light client attacks are expected to be handled and lead to the jailing and tombstoning of validators.

## Closing criteria

Add a test case that generates an "equivocation" light client attack to the E2E tests.

## Problem details

The current way of generating a "lunatic" attack is by forking the consumer chain. This results in the malicious chain sending invalid client headers to the provider chain. Note that after observing the block produced by the main and forked chain, the only block header fields that aren't equal are: `time`, `app_hash`, and `last_commit_hash`. Maybe it's a point to start in order to simulate an "equivocation" attack.

**Comment by p-offtermatt** [comment]
Hey, I took a look at this and it looks like CometMock could be useful here.
I added support for equivocation in CometMock - it can produce DuplicateVoteEvidence now.
Is this the type of evidence you were looking to produce? see https://github.com/cosmos/interchain-security/issues/1190

**Comment by sainoe** [comment]
Hi. Great work in integrating the equivocation into CometMock!
Here the need is to get a [`LightClientAttackEvidence`](https://github.com/cometbft/cometbft/blob/3d1c36d1ecb27a8f9791fe661d4e2f15224a3796/proto/tendermint/types/evidence.proto#L28) that embeds a double signing infraction committed to a block. Does CometMock already support that?

Note that these E2E tests also involve a Hermes Relayer probing evidences committed on-chain.

**Comment by p-offtermatt** [comment]
Ah, I misunderstood - I added DoubleSignEvidence to CometMock, LightClientAttackEvidence is not something I have looked at yet. I have looking into adding LightClientAttackEvidence to CometMock on the roadmap https://github.com/informalsystems/CometMock/issues/34, but if the test crucially relies on Hermes, CometMock won't be able to help at the moment, see https://github.com/cosmos/cosmos-sdk/issues/16277

If you think this could also be done with the go relayer, let me know and I'm happy to add LightClientAttackEvidence as soon as I can!

**Comment by p-offtermatt** [comment]
Hey, light client attacks are now available in CometMock, see https://github.com/cosmos/interchain-security/pull/1249. Again, this does not work with Hermes, but just mentioning here in case this is useful.

**Comment by sainoe** [comment]
Adressed in #1388 & #1249.
