### ISSUE TITLE
The API for submitting the equivocation proposal has a lot of defects

### ISSUE THREAD

**Issue by mpoke** [cosmos/interchain-security#1195]
## Problem

This issue is based on the feedback from @zmanian on https://www.mintscan.io/cosmos/proposals/818

## Closing criteria

The following concerns are addressed. 

## Problem details

- The slashlog isn't queryable. The equivocation packet being received is only visible on the log provider chain. That's hard to access. 
- The equivocation is queryable on the consumer chain. You have equivocation in the consensus address of the consumer chain validator. You need to submit the EquivocationProposal with consensus address of the provider chain. There isn't an obvious way to that reverse look up.
- The validator can change their consumer key after the slashing event so you need an archive node to look this up.

**Comment by MSalopek** [comment]
Related:
https://github.com/cosmos/interchain-security/issues/741

**Comment by mpoke** [comment]
Closing since https://github.com/cosmos/interchain-security/issues/732 will make this a non-issue.
