### ISSUE TITLE
Cut new release off main with IBC bump and recent consumer changes

### ISSUE THREAD

**Issue by smarshall-spitzbart** [cosmos/interchain-security#1198]
## Problem

There are some recent features that have been merged to main which should make it into a release soon. See [changelog](https://github.com/cosmos/interchain-security/blob/64d860d10d6055950dd0672f7c3b8b2790d0f0a5/CHANGELOG.md#unreleased) 

## Closing criteria

Cut new release so it can be deployed by consumers

**Comment by mpoke** [comment]
Requirements: 

- [ ] https://github.com/cosmos/interchain-security/pull/1196 is merged

**Comment by smarshall-spitzbart** [comment]
https://github.com/cosmos/interchain-security/releases/tag/v3.2.0-consumer-rc0
