### ISSUE TITLE
Remove deps on external packages for types sent over wire

### ISSUE THREAD

**Issue by shaspitz** [cosmos/interchain-security#1215]
## Problem

We've seen critical bugs in the past that happened due to the fact that types sent over the wire depend on external packages from sdk and comet. We should remove these external deps, and ensure that every struct sent over the wire is defined internally to this repo, and will not unexpectedly change. 

## Closing criteria

Following https://github.com/cosmos/interchain-security/pull/1071 being merged, remove external references to sdk and comet that're seen in wire.proto, wire.go, etc. 

## Problem details

See https://github.com/cosmos/interchain-security/blob/7986c99b3b49b7603590607e9a026a109dd5eecc/proto/interchain_security/ccv/v1/wire.proto#L7 and https://github.com/cosmos/interchain-security/blob/7986c99b3b49b7603590607e9a026a109dd5eecc/proto/interchain_security/ccv/v1/wire.proto#L10

**Comment by shaspitz** [comment]
I started solving this issue thinking it'd be trivial, see [this branch as a start](https://github.com/cosmos/interchain-security/compare/shawn%2Frm-external-deps-from-wire). However, there's a bunch of shim code from sdk that'd need to be ported over to our repo as well to make the branch build. See [this shim for example](https://github.com/cosmos/interchain-security/blob/80b637fbb3857d58ba3cb3c1fa216eb7e203c54c/x/ccv/provider/keeper/keeper_test.go#L162)

**Comment by mpoke** [comment]
@MSalopek how feasible is to do this? Is it worth the trouble?

**Comment by MSalopek** [comment]
Doing this would be adding very little value with a whole lot of work.

We can address this issue if it becomes an actual pain point and not just a nice to have.

Closing as this is unlikely to get prioritized due to the size of the refactor, potential wire breaks in consumer <-> provider communication and the amount of testing required to confirm no breaks actually happened.
