### ISSUE TITLE
Separate releasing/semver for provider and consumer 

### ISSUE THREAD

**Issue by smarshall-spitzbart** [cosmos/interchain-security#1216]
## Problem

We're going to ditch the idea of "go.mod split" in favor of keeping one go.mod and separating releasing/semver for consumer and provider with tags. See https://github.com/cosmos/interchain-security/issues/801#issuecomment-1683349298 

## Closing criteria

- New releasing procedure is documented
- PR template updated

**Comment by smarshall-spitzbart** [comment]
Just tried some things out and it'd be better to slightly alter the release paradigm to look like `vX.Y.Z-provider` and `vX.Y.Z-consumer`, instead of prefixing the semver number, this is more consistent with tags we've released in the past, and I just confirmed both formats are importable by other repos

**Comment by p-offtermatt** [comment]
I might have missed it, but should there also be an ADR for this to supercede https://github.com/cosmos/interchain-security/pull/897? It might be worth it to get a better summary of benefits/costs associated with this, and to get the context collected in one palce.

**Comment by smarshall-spitzbart** [comment]
I can convert the [comment mentioned in this issue](https://github.com/cosmos/interchain-security/issues/801#issuecomment-1683349298) to an ADR if you'd like? This topic got to a point that it has been talked about all year (too much discussion imo) and never solved, so I skipped ADR :)

**Comment by p-offtermatt** [comment]
I think that comment could almost verbatim become an ADR, yes!

**Comment by smarshall-spitzbart** [comment]
> I think that comment could almost verbatim become an ADR, yes!

Sounds good 👍 https://github.com/cosmos/interchain-security/issues/1216#issuecomment-1687712480
