### ISSUE TITLE
Question: Consumer chain not producing blocks, but why

### ISSUE THREAD

**Issue by ashishchandr70** [cosmos/interchain-security#1218]
According to [this](https://github.com/cosmos/interchain-security/blob/cca008d856e3ffc60ec1a486871d0faa702abe26/docs/docs/validators/overview.md#6-chain-start), "The consumer chain will start producing blocks as soon as 66.67% of the provider chain's voting power comes online (**on the consumer chain**). The relayer should be started after block production commences"

Can someone elaborate on what this means i.e. **66.67% of the provider chain's voting power comes online on the consumer chain**?

I think I somewhat understand what this means but I want to be sure so there are no ambiguities.

I have the following setup in my local dev environment:

2 validators on the provider chain (both have their power set to 100)
1 validator on the consumer chain (single node setup)

When the provider validator count is 1, the consumer (1 validator) produces blocks and I can start hermes and the CCV channel can be created.

However, when I use the setup described above i.e. 2 provider validators and 1 consumer validator, the consumer chain does not produce blocks. Instead I see this:

`INF No addresses to dial. Falling back to seeds`

The voting power for both validators on the provider chain is 100. The consumer chain starts with a validator that is assigned a power of 100 as well. So I think I need to up the validator's power to 200 or more for it to start producing blocks as a single validator. Is this correct?

**Comment by AaronKutch** [comment]
There are many things that could cause this, from consensus keys not being assigned correctly or used on the consumer node to the genesis state not being set. Was a proposal made and passed? I have https://github.com/pendulum-labs/onomy_tests/tree/dev for an example of some automated tests, although I need to add support for multiple validators.

**Comment by mpoke** [comment]
Hi @AaronKutch. 

> Can someone elaborate on what this means i.e. 66.67% of the provider chain's voting power comes online on the consumer chain?

The current documentation is for Replicated Security. This means that the validator set on the consumer is the same as the validator set on the provider, i.e., same validators with same voting powers. 

> I have the following setup in my local dev environment:
> 
> 2 validators on the provider chain (both have their power set to 100)
> 1 validator on the consumer chain (single node setup)
> The voting power for both validators on the provider chain is 100. The consumer chain starts with a validator that is assigned a power of 100 as well. So I think I need to up the validator's power to 200 or more for it to start producing blocks as a single validator. Is this correct?

As mentioned above, the validator sets must match. CometBFT on the consumer chain expects the validator set to consists of the two validators on the provider. For more details check the [code](https://github.com/cosmos/interchain-security/blob/4a7bd10409c151f4e4e470a217dcc6480f763aac/x/ccv/provider/keeper/proposal.go#L272) or the [spec](https://github.com/cosmos/ibc/blob/main/spec/app/ics-028-cross-chain-validation/overview_and_basic_concepts.md#channel-initialization)
