### ISSUE TITLE
Removing the only consumer chain

### ISSUE THREAD

**Issue by mpoke** [cosmos/interchain-security#122]
ref. 

- https://github.com/cosmos/interchain-security/pull/118#discussion_r887888264

> what happens theoretically if the unbonding is put on hold while child chains exist, but then child chain gets removed with gov proposal before hold is lifted?

**Comment by danwt** [comment]
Can we make this issue actionable, or define a closing criteria?

**Comment by mpoke** [comment]
> Can we make this issue actionable, or define a closing criteria?

The implementation should follow the fix in the spec https://github.com/cosmos/ibc/pull/770

**Comment by mpoke** [comment]
Already fixed by https://github.com/cosmos/interchain-security/blob/d059b86608defeb84fc541db35e93411f15f9d5e/x/ccv/provider/keeper/proposal.go#L84. @danwt Could you please confirm this?

**Comment by danwt** [comment]
@mpoke just from that line it seems like it. Do you have a situation or complication in mind?

**Comment by mpoke** [comment]
No, this was the scenario we wanted to handle, i.e., stoping a consumer chain that was the only chain an unbonding op was waiting for.

**Comment by danwt** [comment]
It seems fine.
