### ISSUE TITLE
Refactor E2E tests Hermes config

### ISSUE THREAD

**Issue by sainoe** [cosmos/interchain-security#1226]
## Problem

The ICS misbehaviour E2E tests introduced a new [script](tests/e2e/testnet-scripts/fork-consumer.sh) that configures a special Hermes relayer instance. 

## Closing criteria

We should put this config in its own file similar to [hermes-config.toml](tests/e2e/testnet-scripts/hermes-config.toml).

**Comment by MSalopek** [comment]
All links are broken @sainoe

**Comment by sainoe** [comment]
Closed because not required.
