### ISSUE TITLE
Add ChanCloseConfirm to IBC-GO testing

### ISSUE THREAD

**Issue by sainoe** [cosmos/interchain-security#123]
Enable the full simulation of a channel closing handshake according to [ICS4](https://github.com/cosmos/ibc/tree/marius/ccv/spec/core/ics-004-channel-and-packet-semantics#closing-handshake). 

* An IBC testing endpoint should complete the handshake by calling `ChanCloseConfirm` in respond to a counter-party endpoint closing its channel's end with `ChanCloseInit` which is  already implemented in the IBC-GO testing suite.

* Required to test the removal of a consumer chain

**Comment by smarshall-spitzbart** [comment]
We have [this test](https://github.com/cosmos/interchain-security/blob/30084e034ed88f09193c2faf156a53e32c97e905/x/ccv/consumer/ibc_module_test.go#L392) merged, and both the consumer/providers `OnChanCloseConfirm` simply returns a nil error. @sainoe may know better if there's still action to take

**Comment by mpoke** [comment]
Closing as it is low priority.
