### ISSUE TITLE
Coordinating governance changes of a consumer chain from the producer chain

### ISSUE THREAD

**Issue by AaronKutch** [cosmos/interchain-security#1231]
Hello, our use of replicated security has hit a snag related to the governance of the consumer chain. Some of our consumer chains will be created for reasons of isolating expensive modules from one another, so that if one is lagging for fails for some reason it will not bring down the chain. They will use the IBC version of the staking token from the producer for gas fees and such on the consumer. However, our current consumer-democracy setup would result in an issue where the power to make governance changes comes from the amount of the IBC staking token staked with the consumer-side validator set separate from the replicated security set. We need the power to make governance changes come from governance on the producer chain and have the same security as the block-to-block replicated security on the consumer.
A temporary solution could be to make text proposals on the producer that direct things like placing cosmovisor upgrade plans on the consumer, but that introduces unsavory possibilities like validators diverging if some of them fail to place the upgrade plans. Is there a relatively easy code path that allows a proposal on the producer chain to generate a passed proposal on the consumer chain through some IBC signal signed with the replicated security set, and we can just disable other methods of creating proposals on the consumer chain?

**Comment by AaronKutch** [comment]
Or am I missing something? There is a `consumer-democracy` and plain `consumer` setup for the consumer chains. I presume that the plain `consumer` setup is not viable for real world uses that will require upgrades and tweaks that require governance. The only way they would currently work in practice is with the manual upgrade placing?

**Comment by mpoke** [comment]
Hi @AaronKutch. The consumer-democracy is meant to work with a consumer token that is staked in the `x/ccv/democracy/staking` module. For provider-driven governance (i.e., based on the provider voting power), please see this work https://github.com/cosmos/interchain-security/pull/416 that is currently paused until the Hub is upgrading to SDK 0.47 and IBC 7. 

Also note that both `consumer-democracy` and `consumer` are just examples of how to setup ICS. We are using these mostly for testing. We expect consumer chains to have their own setup.

**Comment by mpoke** [comment]
@AaronKutch I'm closing this issue. Please let us know if you have other questions.

**Comment by AaronKutch** [comment]
There should be some tracking issue for provider-driven governance

**Comment by mpoke** [comment]
@AaronKutch good point. See https://github.com/cosmos/interchain-security/issues/1271
