### ISSUE TITLE
Question: Provider and Consumer chains

### ISSUE THREAD

**Issue by ashishchandr70** [cosmos/interchain-security#1250]
Hi,

I came across this snippet which indicates [a consumer chain can be its own provider](https://github.com/cosmos/ibc/blob/0cd8028ea593a240723d13bba17f3d61d62397ad/spec/app/ics-028-cross-chain-validation/overview_and_basic_concepts.md#motivation). Does this imply a single application binary that encapsulates `provider` and `consumer` modules in itself?

Given that the `consumer` module is incompatible with the `staking` module, which is needed by the `provider`, how would this be possible?

Thanks

**Comment by mpoke** [comment]
> I came across this snippet which indicates [a consumer chain can be its own provider](https://github.com/cosmos/ibc/blob/0cd8028ea593a240723d13bba17f3d61d62397ad/spec/app/ics-028-cross-chain-validation/overview_and_basic_concepts.md#motivation). Does this imply a single application binary that encapsulates provider and consumer modules in itself?

In principle this is possible. We never try to test this scenario. 

> Given that the consumer module is incompatible with the staking module, which is needed by the provider, how would this be possible?

The consumer module is not incompatible with the staking module. See the [democracy consumer](https://github.com/cosmos/interchain-security/tree/main/x/ccv/democracy) as an example of a consumer chain with a staking module. Stride is an example of such a chain in production.

**Comment by ashishchandr70** [comment]
Thanks @mpoke for the pointer to democracy consumer. I will check it out. Thanks again!
