### ISSUE TITLE
Feature requires: We need a query which can return all rotated validator keys by consumer `chain_id`

### ISSUE THREAD

**Issue by liangping** [cosmos/interchain-security#1251]
Hello, 

This query can return a single rotated key with a given address.  this is not efficient that we have to query the each by each on front-end. 

https://github.com/cosmos/interchain-security/blob/d137d39f01a2e2c85f90e7ea0bc0d1738affb4b1/x/ccv/provider/types/query.pb.go#L425C6-L425C39

For example: 

```
curl https://api-cosmoshub-ia.cosmosia.notional.ventures/interchain_security/ccv/provider/validator_consumer_addr?provider_address=cosmosvalcons1rtst6se0nfgjy362v33jt5d05crgdyhfvvvvay&chain_id=stride-1
```

```json
{
  "consumer_address": "cosmosvalcons1dt6ezae48ll23atl940m6xkzs6vz0falch5k9r"
}
```

Would be great, if we can just use `chain_id=stride-1` and return something like this:

```json
{
    "<old_key>": "<new_key>",
    "cosmosvalcons1rtst6se0nfgjy362v33jt5d05crgdyhfvvvvay" : "cosmosvalcons1dt6ezae48ll23atl940m6xkzs6vz0falch5k9r",
    "cosmosvalcons1rtst6se0nfgjy362v33jt5d05crgdyhfvvvvay" : "cosmosvalcons1dt6ezae48ll23atl940m6xkzs6vz0falch5k9r",
}
```

**Comment by ThanhNhann** [comment]
Can I handle this issue?

**Comment by mpoke** [comment]
Thanks @ThanhNhann. I assigned you. Ping if you need help.

**Comment by ThanhNhann** [comment]
HI @liangping and @mpoke, I want to clarify that the goal of this issue is to have a list of pairs `{providerConsAddr, consumerAddr}` right ?

**Comment by liangping** [comment]
@ThanhNhann this is what I am expected. but a list of key pairs is ok to me 

```json
{
    "<old_key>": "<new_key>",
    "cosmosvalcons1rtst6se0nfgjy362v33jt5d05crgdyhfvvvvay" : "cosmosvalcons1dt6ezae48ll23atl940m6xkzs6vz0falch5k9r",
    "cosmosvalcons1rtst6se0nfgjy362v33jt5d05crgdyhfvvvvay" : "cosmosvalcons1dt6ezae48ll23atl940m6xkzs6vz0falch5k9r",
}
```

**Comment by ThanhNhann** [comment]
thank @liangping for the fast reply

**Comment by ThanhNhann** [comment]
I just made a pr for this issue, can you take a look to check it? @liangping

**Comment by liangping** [comment]
@ThanhNhann I just got a new idea!

We need a api like this: [/cosmos/staking/v1beta1/validators](
https://lcd.osmosis.zone/cosmos/staking/v1beta1/validators?pagination.limit=200&status=BOND_STATUS_BONDED)

it returns a full validator list with validator's rotated key on the consumer chain. 

Currently consumer chain does not provide validators api since there's no staking module, so it would be better to have this instead of the list of key pair.

but you can keep the key pair list.

**Comment by freak12techno** [comment]
Hi, just wondering if that's expected: on my node, the REST endpoint returns some binary data instead of `cosmosvalcons` addresses, is that expected:
Example on my node: https://api.cosmos.quokkastake.io/interchain_security/ccv/provider/consumer_chain_id?chain_id=neutron-1
<img width="555" alt="image" src="https://github.com/cosmos/interchain-security/assets/83376337/cc0783f0-532b-48d7-86a3-2cbc8a682f1a">
