### ISSUE TITLE
No query for oldest unconfirmed VSCPacket

### ISSUE THREAD

**Issue by mpoke** [cosmos/interchain-security#1263]
## Problem

Currently there is no possibility to query the oldest sent VSCPacket for which the equivalent `VSCMaturedPackets` were not received from all consumer chains. This info is needed to estimate the time until a consumer chain will be removed due to the `VSCTimeout`.

## Closing criteria

Add a query that returns the vsc send timestamp with the lowest `vscID` for the given chainID, i.e., `GetFirstVscSendTimestamp`.

**Comment by neitdung** [comment]
Could I take this issue sir, @mpoke?

**Comment by neitdung** [comment]
After investigation, I've found function has been implemented at here: [GetFirstVscSendTimestamp function](https://github.com/cosmos/interchain-security/blob/a9b090f98c212018e063f707e300a912401e6e05/x/ccv/provider/keeper/keeper.go#L1070) So, I think we should close this issue

**Comment by MSalopek** [comment]
The issue should not be closed since it states that there is no query to extract the information.

> Add a query that returns the vsc send timestamp with the lowest vscID for the given chainID, i.e., GetFirstVscSendTimestamp.

The gRPC/API and CLI query should return the information contained in the `GetFirstVscSendTimestamp` response.
