### ISSUE TITLE
Change naming of slash meter to downtime meter

### ISSUE THREAD

**Issue by shaspitz** [cosmos/interchain-security#1276]
## Problem

The notion of a "slash meter" exists on the provider to throttle downtime packets that're applied from consumers on the provider val set. The name slash meter is not the best, as downtime packets coming from consumers (yes those are called "slash packets" but that naming should be changed as well) only jail a validator.

## Closing criteria

Use naming that's more descriptive of the infraction that's actually being communicated between chains, not the action that's taken. "downtime meter" is likely the best naming

**Comment by mpoke** [comment]
Closing as this would break API and the effort is not really worth it.
