### ISSUE TITLE
EPIC: Read-only protocol

### ISSUE THREAD

**Issue by mpoke** [cosmos/interchain-security#1293]
## Problem

This is a meta issue to track the work on making ICS a read-only protocol. 

## Closing criteria

Either ICS is redesigned as read-only protocol (i.e., no CCV channel) or a good reasoning of why this is not feasible is provided.

## Problem details

We would like to simplify the ICS protocol to work with IBC queries. This will allow for a much simpler protocol, and easier maintenance going forward, as well as making the Hub more robust to malfunctioning consumer chains.

## Task list

```[tasklist]
### Must have
- [ ] Update spec -- https://github.com/cosmos/ibc/issues/1010
```

```[tasklist]
### Nice to have
- [ ] https://github.com/cosmos/interchain-security/issues/761
```

**Comment by smarshall-spitzbart** [comment]
Consumer initiated slashing will still exist with this idea correct? Everything would just be invoked by provider tx instead of an IBC packet

**Comment by mpoke** [comment]
> Consumer initiated slashing will still exist with this idea correct? Everything would just be invoked by provider tx instead of an IBC packet

Jailing for downtime is necessary. We'll need to figure out how to do it though. An IBC packet is a TX sent by a relayer and it comes with some nice proofs. Maybe something along the lines of https://github.com/cosmos/interchain-security/issues/761 could be a solution. Not sure.

**Comment by mpoke** [comment]
We believe that `VSCMaturedPackets` cannot be removed from the Replicated Security protocol without compromising the security of the system. This is due to the security model of IBC light clients. We documented our findings [here](https://docs.google.com/document/d/1LPx_Q8gV3Pmlytty3g126RcGv2NJN91H6n0ayicjnfg/edit). As a result, we are closing this issue.
