### ISSUE TITLE
comet/cometmock discrepancy w.r.t downtime related e2e tests

### ISSUE THREAD

**Issue by shaspitz** [cosmos/interchain-security#1304]
## Problem

The throttling e2e tests illuminated a difference in behavior between comet and cometmock. Namely, relaying packets behaves differently. For real comet, a slash action followed by a relay action will only relay the slash packet, whereas for cometmock a slash action followed by a relay action will relay the slash packet, and the corresponding vsc packet derived from the vp change. 

CC @p-offtermatt 

## Closing criteria

Find and fix behavior discrepancy

**Comment by smarshall-spitzbart** [comment]
@p-offtermatt see https://github.com/cosmos/interchain-security/commit/1ed2f56774a0a2c8d31bebe1ba1ac52aa766a99c, https://github.com/cosmos/interchain-security/pull/1230 now passes `make test-e2e-short`, ` make test-e2e-short-cometmock` and `go run ./tests/e2e/... --tc slash-throttle`. Running the slash throttle test case with cometmock will fail, but that's not a part of CI

**Comment by p-offtermatt** [comment]
Thanks for opening the issue and giving the context Shawn!
