### ISSUE TITLE
Inconsistent action names

### ISSUE THREAD

**Issue by p-offtermatt** [cosmos/interchain-security#1322]
## Problem

The action names in https://github.com/cosmos/interchain-security/blob/main/tests/e2e/actions.go are inconsistent:
some are capitalized, some are not.

We should unify this. The best way seems to be making all action names capitalized, but we could investigate what exactly to do here.

Also pay attention to other places where the action names may be used as strings and change them there, e.g. https://github.com/cosmos/interchain-security/blob/ph/json-marshal/tests/e2e/json_utils.go

## Closing criteria

The action names have been unified to one preferred format, and future actions honor the existing convention.

**Comment by neitdung** [comment]
Hi sir @p-offtermatt , can I take this issue?

**Comment by p-offtermatt** [comment]
Yes, gladly! I've assigned you :)
