### ISSUE TITLE
Create guidelines on how to use the e2e testing framework

### ISSUE THREAD

**Issue by p-offtermatt** [cosmos/interchain-security#1334]
Here is a list of things that we should mention or document better. These might also be candidates for refactors, but I am mostly looking to put things here that are solved simply by having some guidance on how to do them.

- [x] StartRelayer vs relayPackets: when to use what?
- [x] ChainState null means we check nothing, not that we think it should be null
- [x] How can the e2e tests be used to produce a local testnet you can try things on (related: https://github.com/cosmos/interchain-security/issues/896)

**Comment by p-offtermatt** [comment]
Anyone is free to add things they would like clarified or documented better in this issue.

**Comment by shaspitz** [comment]
Some random non-trivial things to document w.r.t e2e tests:

- When/why we should specify `--gas` flag for certain actions
- How one should debug e2e tests that fail -> shelling into the docker container, navigating file structure, logs, etc. 
- How one should specify "genesis changes" like setting a non-default param
