### ISSUE TITLE
upgrade integration testing framework for v50

### ISSUE THREAD

**Issue by MSalopek** [cosmos/interchain-security#1349]
v50 upgrade requires changes to integration testing setup.

Namely, packet sniffing that was done as part of `legacy_ibc_testing` directory removal needs to be refactored to support the new `ABCIListener` interface and the changes requried to support `FinalizeBlock` since ABCI++ (CometBFT v0.38) does not support `BeginBlock` and `EndBlock` any more.

Previous and related issues:
* https://github.com/cosmos/interchain-security/pull/1185
* https://github.com/cosmos/ibc-go/pull/4315
* https://github.com/cosmos/ibc-go/pull/4505

## Prerequisites
Work is partially done on [feat/v50-upgrade](https://github.com/cosmos/interchain-security/tree/feat/v50-upgrade).

To complete this issue all testing apps (`app.go` and related `cmd`) must be made operational.

## Partial fixes enabling more work
* https://github.com/cosmos/interchain-security/pull/1367

## Closing criteria
- [ ] refactor integration testing setup in `tests/integration/setup.go` (support new interfaces, update packet/event sniffing)
- [ ] enable e2e tests and make them pass, refactoring where necessary
- [ ] PRs made to [feat/v50-upgrade](https://github.com/cosmos/interchain-security/tree/feat/v50-upgrade)

**Comment by mpoke** [comment]
@MSalopek this issue seems to have been fixed. Is that right?

**Comment by MSalopek** [comment]
Closing as the solution is in `release/v5.x`.

Commits:
* https://github.com/cosmos/interchain-security/commit/781f691e7f89b3b7d560b2dbf6fe4e92fa9cd4bd
* https://github.com/cosmos/interchain-security/commit/506e4523aa9b5adfd1cbb0de56d7869b8aed4bf0
* https://github.com/cosmos/interchain-security/commit/594f532736da11aaea11f3aab2edc2fb6c0e90e5
* https://github.com/cosmos/interchain-security/commit/1b5bec285e7d6e47983347884f059f210bf000e7
* https://github.com/cosmos/interchain-security/commit/28bab0419cf85bb920b72da4f36b01d5c7378006
* https://github.com/cosmos/interchain-security/commit/c533e8ded6853745849c17139fed5d61b0c17cc4
* https://github.com/cosmos/interchain-security/commit/e4c8f975ac895c6512674e31cc22c94e670fb4a4
* https://github.com/cosmos/interchain-security/commit/471b46ca2ba91c7c46fa887f54bec31d721ff49e
