### ISSUE TITLE
Ensure that field lengths are limited

### ISSUE THREAD

**Issue by faddat** [cosmos/interchain-security#1370]
Over a year ago, a researcher named Twitter.com/Ctrl_felix discovered an issue in IBC which is now named banana King after the receive address that he chose in a multi-megabyte IBC transfer.  Felix reported to hacker one but did not hear back, and then twitter.com/getcoldy contacted me for assistance with that.

Over a year ago, when contacted for assistance by Colby, I responded and contacted the informal systems and IBC teams. Somehow, the SDK and comet became involved as well. Unfortunately, nothing was done. We need to check ICS to make sure that all fields have bounds.

**Comment by mpoke** [comment]
Thanks @faddat for opening this issue. Check the fix in https://github.com/cosmos/interchain-security/pull/1460.
