### ISSUE TITLE
Fix removal of the equivocation  proposals

### ISSUE THREAD

**Issue by sainoe** [cosmos/interchain-security#1393]
## Problem

The removal of the equivocation proposals  caused an error during the v14 testnet:

```
curl http://localhost:1317/cosmos/gov/v1beta1/proposals
{
  "code": 2,
  "message": "rpc error: code = Internal desc = rpc error: code = Internal desc = no concrete type registered for type URL /interchain_security.ccv.provider.v1.EquivocationProposal against interface *types.Content: unknown request",
  "details": [
  ]
}
```

## Closing criteria

Make sure the equivocation proposals are deprecated but can still be resolved.

## Problem details

This only shows up when there is an equivocation proposal in the state prior to the upgrade to v14, just like prop 818: https://dev.mintscan.io/cosmos/proposals/818
The CLI returns the same error:
gaiad-v14 q gov proposal 818
Error: rpc error: code = Unknown desc = no concrete type registered for type URL /interchain_security.ccv.provider.v1.EquivocationProposal against interface *types.Content: panic

Credits to @dasanchez for reporting the issue!

**Comment by MSalopek** [comment]
Added to `[release/v2.2.x-provider-lsm](https://github.com/cosmos/interchain-security/tree/release/v2.2.x-provider-lsm)`.

@sainoe This also needs to go to main?

**Comment by sainoe** [comment]
https://github.com/cosmos/interchain-security/pull/1394  was merged into [feat/ics-misbehaviour-handling](https://github.com/cosmos/interchain-security/tree/feat/ics-misbehaviour-handling) that will be merge into `main` shorty.
