### ISSUE TITLE
Create app.go for CosmWasm enabled consumer chain

### ISSUE THREAD

**Issue by mpoke** [cosmos/interchain-security#143]
`app/wasm-consumer/app.go`, should contain the modules necessary for the minimum viable consumer chain (see [`app/consumer/app.go`](https://github.com/cosmos/interchain-security/issues/139)) and in addition the CosmWasm module.

**Comment by marbar3778** [comment]
you should try to setup these go.mods as their own go mods, this will better separate them and will show it should be done.

**Comment by jtremback** [comment]
I believe this has been taken care of in a different repo. Will look into it.

**Comment by jtremback** [comment]
https://github.com/Ethernal-Tech/wasmd/blob/cosmwasm-consumer/app/app.go
