### ISSUE TITLE
Implement calls to `AfterCCValidatorBeginUnbonding`

### ISSUE THREAD

**Issue by danwt** [cosmos/interchain-security#147]
The code should match the spec

https://github.com/cosmos/interchain-security/blob/404529c8866c007bb02ba1309a249e369979486f/x/ccv/consumer/keeper/validators.go#L31-L34

and

```
    else if update.power == 0 {
      // existing validator begins unbonding
      validatorSet.Remove(addr)
      // call AfterCCValidatorBeginUnbonding hook
      AfterCCValidatorBeginUnbonding(addr)
    }
```

https://github.com/cosmos/ibc/blob/ad30596341b3f0901d9520b00f175a8b3c702ce5/spec/app/ics-028-cross-chain-validation/methods.md?plain=1#L1514-L1519

**Comment by mpoke** [comment]
I agree, but it's not a major thing since `Power` is `int64`. Nice catch though.

**Comment by mpoke** [comment]
> > I agree, but it's not a major thing since Power is int64. Nice catch though.
> 
> Heh, not sure I got that. What do you mean?

I mean that `< 1` and `== 0` are equivalent. However, now that I think of it, this is true from `uint64` and not for `int64`. Thus, I think that the implementation is more secured, and we should fix this on the spec (just in case `update.power` is -1, which shouldn't be the case, but still). @danwt  Could you open an issue on the spec side and close this one?

**Comment by danwt** [comment]
Hey sure, good point!, but the issue is about the `AfterCCValidatorBeginUnbonding(addr)` not being called!

**Comment by mpoke** [comment]
Ah, that's not needed. I was added to the spec for completeness. There is nothing in the SDK that consumes this hook.

**Comment by danwt** [comment]
Ah I see.
