### ISSUE TITLE
Create a user-friendly interface for debugging e2e tests

### ISSUE THREAD

**Issue by p-offtermatt** [cosmos/interchain-security#1487]
An issue to collect ideas for a user-friendly interface with the end-to-end tests, inspired by this comment:

> Could we come up with some tool for debugging? 
> For example, run a script to get the logs from the docker containers. 
> Or to query / run transactions on the docker containers.

_Originally posted by @mpoke in https://github.com/cosmos/interchain-security/pull/1466#discussion_r1417166088_

Some more ideas:
Being able to use alice/bob/charlie instead of chain addresses or node endpoints
shing into the containers easily

**Comment by mpoke** [comment]
Closing as the objective should be to deprecate existing e2e tests in favor of the interchain tests.
