### ISSUE TITLE
Fix sender accounts initialization in IBC testing

### ISSUE THREAD

**Issue by sainoe** [cosmos/interchain-security#151]
At the moment all the testing suites need to have sender accounts manually setup like so:
https://github.com/cosmos/interchain-security/blob/404529c8866c007bb02ba1309a249e369979486f/x/ccv/consumer/module_test.go#L90-L91

However it shouldn't be the case since all sender accounts are initialized in `ibc/testing/chain.go`. The bug can be identified when comparing the accounts number stored in the test chains against their value in the account module states.
```
cApp := suite.consumerChain.App.(*appConsumer.App)

acnt := suite.consumerChain.SenderAccount
gotAcnt := cApp.AccountKeeper.GetAccount(suite.consumerChain.GetContext(), acnt.GetAddress())

suite.Require().EqualValues(acnt.GetAccountNumber(), gotAcnt.GetAccountNumber())
```

**Comment by jtremback** [comment]
What impact does this have?
