### ISSUE TITLE
Use consumer UnbondingTime in the tests

### ISSUE THREAD

**Issue by sainoe** [cosmos/interchain-security#153]
Consumer chain clients should be initialized using the [UnbondingTime value](https://github.com/cosmos/interchain-security/blob/404529c8866c007bb02ba1309a249e369979486f/x/ccv/consumer/types/keys.go#L44)  rather than using the [default IBC-GO testing value](https://github.com/cosmos/ibc-go/blob/a71fc1029ad1fc6d377d642781d02ad3cbfa0910/testing/values.go#L27).

https://github.com/cosmos/interchain-security/blob/404529c8866c007bb02ba1309a249e369979486f/x/ccv/provider/provider_test.go#L92

[NewPath](https://github.com/cosmos/ibc-go/blob/a71fc1029ad1fc6d377d642781d02ad3cbfa0910/testing/path.go#L19)
```
func NewPath(chainA, chainB *TestChain) *Path {
	endpointA := NewDefaultEndpoint(chainA)
	endpointB := NewDefaultEndpoint(chainB)
...
}
```

The following [ibc-go condition](https://github.com/cosmos/ibc-go/blob/a71fc1029ad1fc6d377d642781d02ad3cbfa0910/modules/core/02-client/keeper/keeper.go#L310-L314) makes the tests fail when these values aren't equal :
```
expectedUbdPeriod := k.stakingKeeper.UnbondingTime(ctx)
if expectedUbdPeriod != tmClient.UnbondingPeriod {
return sdkerrors.Wrapf(types.ErrInvalidClient, "invalid unbonding period. expected: %s, got: %s",
	expectedUbdPeriod, tmClient.UnbondingPeriod)
}
```

**Comment by mpoke** [comment]
@sainoe Shouldn't https://github.com/cosmos/interchain-security/pull/144 solve this issue?

**Comment by sainoe** [comment]
No it won't. #144 addresses how the `UnbondingTime` value is computed and then stored in the consumer states. 
However this value will still be compared to the consumer client default config which is hardcoded to a 3 weeks duration in the IBC-GO tests. [line](https://github.com/cosmos/ibc-go/blob/681a558e3d2da314313c0edde93b29d59b3b18be/testing/values.go#L27)
