### ISSUE TITLE
Enable restarting the consumer chain 

### ISSUE THREAD

**Issue by mpoke** [cosmos/interchain-security#156]
The consumer chain needs to be able to restart after a shut down (intentional or not). This is also needed for the testnet.  

Related to

- https://github.com/cosmos/interchain-security/issues/125
- https://github.com/cosmos/interchain-security/issues/121

**Comment by jtremback** [comment]
@sainoe I know there's a tiny bit of work ongoing in https://github.com/cosmos/interchain-security/pull/382/files- Will that be the end of this issue?

**Comment by sainoe** [comment]
Yes definitely, I will close it once I'm done with #382

**Comment by mpoke** [comment]
Closing as #382 was merged.
