### ISSUE TITLE
Enable restarting the provider chain

### ISSUE THREAD

**Issue by mpoke** [cosmos/interchain-security#158]
The provider chain needs to be able to restart after a shut down (intentional or not). This is also needed for the testnet.

Related to https://github.com/cosmos/interchain-security/issues/121

**Comment by jtremback** [comment]
@sainoe I know there's a tiny bit of work ongoing in https://github.com/cosmos/interchain-security/pull/382/files- Will that be the end of this issue?

**Comment by sainoe** [comment]
I suggest to leave it open to follow up on the related [hermes relayer issue](https://github.com/informalsystems/hermes/issues/1152).

**Comment by jtremback** [comment]
Can this be closed? This issue has been haunting you @sainoe lol
