### ISSUE TITLE
Partial Set Security: Construct and send the partial sets to the consumers

### ISSUE THREAD

**Issue by insumity** [cosmos/interchain-security#1606]
## Problem

Construct the partial sets that are stored in the `VSCPacket`s that are queued and send to the consumer chain. If the epoch ADR has been implemented, we should combine it with [epochs](https://github.com/cosmos/interchain-security/blob/main/docs/docs/adrs/adr-014-epochs.md).

## Closing criteria

1. Make sure the partial set is also initialized correctly.
2. Thoroughly test

**Comment by p-offtermatt** [comment]
Hey, I think this is done and should be closed/moved to done in the board, right?
