### ISSUE TITLE
Partial Set Security: Compute the Top N validators and opt them in

### ISSUE THREAD

**Issue by insumity** [cosmos/interchain-security#1607]
## Problem

For Top N chains, we automatically opt in validators that are in the top `N%` of validators according to their voting power. Additionally, if a validator belongs to the the bottom `(100 - N)%` validators but later enters (e.g., due to  delegations) the top `N%`, this validator is opted in as well.

## Closing criteria

1. Top `N%` validators in Top N chains should be initially opted in.
2. Validator that enters the top `N%` validator should be opted in.
3. Thoroughly test.

## Problem details

We intend to reuse the soft opt-out logic.

**Comment by p-offtermatt** [comment]
This is done, right? Can we close?
