### ISSUE TITLE
Outline atom gov requirements

### ISSUE THREAD

**Issue by okwme** [cosmos/interchain-security#162]
I think it may be easier to follow a similar tactic to the staking module bez made for the democracy module ([link](https://github.com/cosmos/interchain-security/tree/main/x/ccv/staking)) to create a separate governance system that relies on ATOM votes from a local gov system.

I will refer to this as `atom-gov` and it would require the following tasks afaiu:
* make an empty module like `ccv/staking` and import the gov module from the SDK.
* overwrite the module name so there isn't a collision
* overwrite the EndBlocker so that it has [logic](https://github.com/cosmos/composer/blob/master/x/adminmodule/abci.go) similar to the adminmodule except
   * it hardcodes the cosmos hub governance module account address as the only address allowed to make a proposal
   * all message types are removed besides submit proposal
   * ensure all the other functionality of the gov module can be safely ignored / voided

Another path is
* update https://github.com/cosmos/composer to use cosmos SDK v0.45

Another path is
* create an even simpler version of https://github.com/cosmos/composer where there is no need to add edit or remove admins since it will only ever be the cosmos hub governance module account that should execute proposals this way.

**Comment by okwme** [comment]
minimum viable path would be to disable the upgrade module entirely and use cosmos hub to pass signaling proposal that includes an upgrade height for the consumer chain and perform a manual upgrade.

**Comment by jtremback** [comment]
This is now termed "provider-driven-governance" and has been finished although it is not present in the v1 release because of the lack of ICA.
