### ISSUE TITLE
Epochs: Testnet testing

### ISSUE THREAD

**Issue by insumity** [cosmos/interchain-security#1651]
## Problem

Even with unit, integration, etc. tests we would still need to verify that epochs work as expected on the testnet. This issue is to track this work. 

## Closing criteria

We would need to get in touch with Dante and describe what is new and what we would like to test. We would want to verify that `VSCPacket`s are send once per epoch and that everything works as expected. Also, that the governance `BlocksPerEpoch` parameter can be correctly set.

**Comment by p-offtermatt** [comment]
Related: https://github.com/cosmos/interchain-security/issues/1697, but this has a bigger scope of a "real testnet"

**Comment by mpoke** [comment]
Closing as this is tested as part of the Gaia v16 release.
