### ISSUE TITLE
Epochs: Clean-up old key-assignment code

### ISSUE THREAD

**Issue by insumity** [cosmos/interchain-security#1664]
## Problem

After we move to epochs we won't need the key-assignment code any more. This issue is a reminder to go and clean up the code that has to do with key assignments.
Also, we should update the [key-assignment ADR](https://github.com/cosmos/interchain-security/blob/main/docs/docs/adrs/adr-001-key-assignment.md) to capture those changes.

**Comment by mpoke** [comment]
@insumity Keep in mind that the pruning mechanism is still needed.
