### ISSUE TITLE
Delete large outdated `interchain-securityd` binary

### ISSUE THREAD

**Issue by danwt** [cosmos/interchain-security#176]
At some point the 60MiB binary got [tracked](https://github.com/cosmos/interchain-security/blob/main/interchain-securityd).
Delete it from history. See https://stackoverflow.com/questions/2100907/how-to-remove-delete-a-large-file-from-commit-history-in-the-git-repository

NOTE: AFAIK it requires some human consensus to delete files from history. After the deletion is reflected on github everybody working on the project must sync their local versions. So this is not a 2 minute job.

**Comment by jtremback** [comment]
Oops

**Comment by jtremback** [comment]
Too many people working on it now. This may never be fixed
