### ISSUE TITLE
Feature request: add support for IBC fee middleware

### ISSUE THREAD

**Issue by MSalopek** [cosmos/interchain-security#1782]
## Feature request

At present, the `provider` IBC stack is not able to support IBCFee middleware which prevents incentivizing ICS protocol packets.

It would be beneficial to allow better support for IBCFee so ICS packets could be incentivized, even though the packets originate from an on-chain protocol.

It is possible to use the consumer chain rewards pool or the provider community pool for packet incentivization (this would be [synchonous incentivization](https://ibc.cosmos.network/main/middleware/ics29-fee/msgs#msgpaypacketfee)).

Alternatively, the packets could be [incentivized asynchronously](https://ibc.cosmos.network/main/middleware/ics29-fee/msgs#msgpaypacketfeeasync), but this seems like it would require more work.  

## Closing criteria

- [ ] create an ADR outlining the utility of this feature
- [ ] if the feature is useful, proceed with implementation (track in an EPIC or an issue)

**Comment by mpoke** [comment]
Closing as with the introduction of Epochs, the number of ICS packets is low (1 packet / hour / chain). Also, the IBC fee middleware will be deprecated with IBC v2.
