### ISSUE TITLE
Partial Set Security: Write documentation

### ISSUE THREAD

**Issue by insumity** [cosmos/interchain-security#1785]
Before PSS launches we need to:
- [ ] provide a feature overview
- [ ] provide validator documentation (joining, opting in etc)
- [ ] provide query and transaction documentation (REST, CLI)
- [ ] update the consumer chain onboarding documentation (https://cosmos.github.io/interchain-security/consumer-development/onboarding)
- [ ] add pseudocode on the math behind the power-cap shaping code

**Comment by p-offtermatt** [comment]
Some things to note:
* If all validators opt out of an opt-in chain, it will have a consensus failure and stop
