### ISSUE TITLE
Partial Set Security: Opting in with provider key fails

### ISSUE THREAD

**Issue by p-offtermatt** [cosmos/interchain-security#1813]
## Problem

Surfaced by a validator on the devnet:

> When i tried to join with my provider's key, i got following error in the tx once it got included on chain:
```
failed to execute message; message index: 0: a validator cannot assign the
  default key assignment unless its key on that consumer has already been assigned:
  cannot re-assign default key assignment
```
> Opting in with a different key works. Also you can assign a provider's key after validator has already opted in.

This happens because we are reusing the key assignment logic.
We should change this to allow simply providing the provider key explicitly, and also taking it as the default if no key is given;
or we should at least make sure we have good documentation on this.

## Closing Criteria

We have addressed the issue by fixing the behaviour in question; or we have decided that it is not a problem.

**Comment by mpoke** [comment]
> When i tried to join with my provider's key, i got following error in the tx once it got included on chain. 

Opting in on a consumer with the provider key can be done by just leaving the [consumer key field](https://github.com/cosmos/interchain-security/blob/e196a63d19140489560e483abd1237a3e49312e0/proto/interchain_security/ccv/provider/v1/tx.proto#L255) unset. There is no reason to set the field to the provider key, especially as we recommend validators to not re-use the same keys on different chains. 

Closing as a non-issue.
