### ISSUE TITLE
Unbonding period advisory in `consumer-addition` is written to stdout

### ISSUE THREAD

**Issue by chris-ricketts** [cosmos/interchain-security#1920]
## Problem

Tools/Scripts parsing cli stdout output are broken when unexpected advisories are written to stdout. 

e.g. when using `--output json` and expecting to handle only json if there is a non-error exit code.

[This is done here in the `ccv` module client](https://github.com/cosmos/interchain-security/blob/2960c5b2ea8089bb19290fbf2225a31339fbf601/x/ccv/provider/client/proposal_handler.go#L366)

## Closing criteria

Write the advisory to stderr.

**Comment by MSalopek** [comment]
Thanks for opening your fist issue on ICS!

We're evaluating the solution. So far it seems good.

Thanks!
