### ISSUE TITLE
[Feature]: Query for blocks until next epoch

### ISSUE THREAD

**Issue by mpoke** [cosmos/interchain-security#1940]
### Summary

Query for blocks until next epoch. 

### Problem Definition

It's currently not possible to know when the current epoch ends, which means it's hard for a validator that opts in to know when to look to see the results of its actions.

### Proposed Feature

Add a query to get the number of blocks until the next epoch. 

### Work Breakdown

Add an additional query.

**Comment by p-offtermatt** [comment]
As discussed with @insumity, taking this one over
