### ISSUE TITLE
Update SDK changes to 0.45.6

### ISSUE THREAD

**Issue by mpoke** [cosmos/interchain-security#204]
The branch https://github.com/cosmos/cosmos-sdk/tree/interchain-security-rebase with SDK changes needed by IS should be rabased on  [SDK v0.45.6](https://github.com/cosmos/cosmos-sdk/tree/v0.45.6)

**Comment by mpoke** [comment]
First wait for 
- [] https://github.com/cosmos/cosmos-sdk/pull/12796 to be reviewed and merged

**Comment by marbar3778** [comment]
I would rather identify the staking changes first and if they are breaking. If they are this will not be time well spent, if they are not then coordination with the hub team as to what version will be on the hub at time of launch is needed and then updating to that version. 


Is there a list of changes that were made to the staking module

**Comment by mpoke** [comment]
> Is there a list of changes that were made to the staking module

Not really. Once https://github.com/cosmos/cosmos-sdk/pull/12796 is merged, I want to open a PR against v0.45.1 that will contain all the changes. Mainly, the changes to staking are 
- the signature of `keeper.Slash()`;   
- and the way undelegations, redelegations and validator unbondings complete. 

> what version will be on the hub at time of launch

Probably v0.46. However, the consumer chain also requires some of these changes (the ones targeting evidence and slashing, @sainoe can share more details here) and consumer chains may use SDK v0.45.  

The reason I want to rebase https://github.com/cosmos/cosmos-sdk/tree/interchain-security-rebase on v0.45.6, is that v0.45.6 contains some fixes that solves some issues with the git checks. Not that important though.

**Comment by sainoe** [comment]
@jtremback

**Comment by jtremback** [comment]
@marbar3778 @mpoke I thought that when we talked last week, we decided that it was OK for the Cosmos SDK team to review in its current form, and then we will update to 46 (or 47?) later. Is this the case? If so, @mpoke can you close this issue?
