### ISSUE TITLE
Clean up slash-log state

### ISSUE THREAD

**Issue by insumity** [cosmos/interchain-security#2093]
## Problem

The `provider` module still stores state under `SlashLogBytePrefix`.`SlashLogBytePrefix` is used to construct the `SlashLogKey` that is used in `SetSlashLog` and `GetSlashLog` methods. `SetSlashLog` is used [here](https://github.com/cosmos/interchain-security/blob/main/x/ccv/provider/keeper/relay.go#L334) while `GetSlashLog` is **only** used in an integration test, so the fact that we set something but we have no getters to read it makes this unusable. Additionally, the whole slashing for equivocation evidence chunk where `SetSlashLog` is called is not really used. Equivocation evidence is to be submitted through `MsgSubmitConsumerDoubleVoting` messages.

This means that we can remove everything associated with `SlashLogBytePrefix`.

**Comment by ukane-philemon** [comment]
> ## Problem
> 
> The `provider` module still stores state under `SlashLogBytePrefix`.`SlashLogBytePrefix` is used to construct the `SlashLogKey` that is used in `SetSlashLog` and `GetSlashLog` methods. `SetSlashLog` is used [here](https://github.com/cosmos/interchain-security/blob/main/x/ccv/provider/keeper/relay.go#L334) while `GetSlashLog` is **only** used in an integration test, so the fact that we set something but we have no getters to read it makes this unusable. Additionally, the whole slashing for equivocation evidence chunk where `SetSlashLog` is called is not really used. Equivocation evidence is to be submitted through `MsgSubmitConsumerDoubleVoting` messages.
> 
> This means that we can remove everything associated with `SlashLogBytePrefix`.

`SetSlashLog` is used [here](https://github.com/cosmos/interchain-security/blob/8e102247c1bf52efc5c8ebcd43bc415f6ba23276/x/ccv/provider/keeper/relay.go#L341). Code might have been updated since OP posted.

**Comment by ukane-philemon** [comment]
@insumity since double voting would send a `MsgSubmitConsumerDoubleVoting` message, I don't see a test case that ensures that. Or am I missing something?

**Comment by mpoke** [comment]
Closing as duplicate of https://github.com/cosmos/interchain-security/issues/1502
