### ISSUE TITLE
Deduplicate power-shaping parameters

### ISSUE THREAD

**Issue by insumity** [cosmos/interchain-security#2103]
## Problem

As mentioned in this [comment](https://github.com/cosmos/interchain-security/pull/2079#discussion_r1689314023), power shaping parameters appear in multiple proto messages (e.g., in [`MsgConsumerAddition`](https://github.com/cosmos/interchain-security/blob/v5.1.0/proto/interchain_security/ccv/provider/v1/tx.proto#L169), [`MsgConsumerModification`](https://github.com/cosmos/interchain-security/blob/v5.1.0/proto/interchain_security/ccv/provider/v1/tx.proto#L305), [`ConsumerAdditionProposal`](https://github.com/cosmos/interchain-security/blob/v5.1.0/proto/interchain_security/ccv/provider/v1/provider.proto#L94)).
It would be nice to get rid of those duplications and simplify the codebase.
This issue is mostly a reminder to verify that those duplications do not exist after we complete the Permissionless work.

**Comment by mpoke** [comment]
This is fixed in ICS v6.0.0 with the introduction of the permissionless ICS feature.
