### ISSUE TITLE
Inactive Vals: Test rewards in the consumer denom

### ISSUE THREAD

**Issue by p-offtermatt** [cosmos/interchain-security#2128]
"_[...]_ in the consumer chain token" is this actually tested? I only see:
```IsNativeDenom:       true, // check for rewards in the provider denom```
in the tests.

_Originally posted by @insumity in https://github.com/cosmos/interchain-security/pull/2079#discussion_r1704100066_

**Comment by sainoe** [comment]
Solved by https://github.com/cosmos/interchain-security/pull/2290.
