### ISSUE TITLE
Introduce a query to return the consumer valset before spawn time

### ISSUE THREAD

**Issue by sainoe** [cosmos/interchain-security#2159]
## Problem

Currently, if you query the validators for a consumer chain that hasn’t launched yet (the spawn time didn’t pass) it returns an empty set. This is because the first time the `ConsumerValSet` is set is when creating the consumer genesis at spawn time. 

## Closing criteria

Extend the [QueryConsumerChainOptedInValidators](https://github.com/cosmos/interchain-security/blob/main/proto/interchain_security/ccv/provider/v1/query.proto#L106C7-L106C42) query so that if the chain is not launched yet, then we use the currently opted in validators.

**Comment by MSalopek** [comment]
Please merge this issue with #2161
