### ISSUE TITLE
Introduce quality gate for merging PR's into main

### ISSUE THREAD

**Issue by danwt** [cosmos/interchain-security#216]
We need to put hard limits

- fmt
- units pass
- integration passes
- linters pass
- coverage ??
- other code metrics ?? 

?? = maybe

**Comment by danwt** [comment]
@sainoe do you permissions for this in the repo? To enforce that all checks need to pass.

**Comment by sainoe** [comment]
Idnk where you enforce that in the repo settings. Where should I look?

**Comment by danwt** [comment]
I think it's just in general. If you can't see it you might not have perms.

**Comment by jtremback** [comment]
![Image](https://user-images.githubusercontent.com/1335122/183522692-ace28d2f-144a-40f6-9cbb-5c0c509a9d36.png)
