### ISSUE TITLE
Permissionless: Introduce queries for retrieving consumer chains

### ISSUE THREAD

**Issue by insumity** [cosmos/interchain-security#2160]
For Permissionless ICS, we would like to support the following 2 queries:

### 1. Retrieve all consumers chains in a _parameterized_ way
We would like a query similar (or could be the same but modified) to `query provider list-consumer-chains` that returns a list of all the consumer chains. For each consumer chain, we would like to see its `phase` (is it `Launched`, `Initialized`, etc.), as well as its associated `ConsumerMetadata` (i.e., `description`, `metadata`, etc.).

We would like this query to be **parameterizable** on the `phase`, in the sense that you could ask for "all the consumer chains that are `Launched`," etc.

### 2. Retrieve most of the information of a specific consumer chain
We would like a query (e.g., `query provider consumer-chain`) that given a `consumerId` returns the `phase`, `chainId`, `ownerAddress`, everything under `ConsumerMetadata`, everything under `ConsumerInitializationParameters`, and everything under the `PowerShapingParameters` of that chain.

**Comment by sainoe** [comment]
Closed by #2172 &  #2179.
