### ISSUE TITLE
Move all end-to-end tests to special folder

### ISSUE THREAD

**Issue by mpoke** [cosmos/interchain-security#219]

**Comment by smarshall-spitzbart** [comment]
Started working on this today. 

Proposed hierarchy of testing:
- Unit tests for simple standalone functionality, and CRUD operations on consumer/provider keeper (native go testing package)
- Unit tests with mocked external keepers for a little more complex functionality, but still no interchain functionality (uses native go testing package, and testify/mock)
- e2e tests in their own directory for testing interchain functionality, things where advancing blocks would be useful, handshakes, packet relays, etc. (uses IBC testing suite)
- integration tests for testing highest level of functionality (real nodes, queries, txs, docker)
- diff testing?

#267 is still WIP but, but gives a good idea of what the first two bullet points would look like.

**Comment by danwt** [comment]
Thanks @smarshall-spitzbart the above is very clear. We should probably put the info in the top level README (or CONTRIBUTING.md) when the PRs are done
