### ISSUE TITLE
Make `gosec` pass

### ISSUE THREAD

**Issue by danwt** [cosmos/interchain-security#223]
The linter gosec fails

https://github.com/cosmos/interchain-security/runs/7282519806?check_suite_focus=true#step%3A4%3A516=

we need to make it pass. A big part of this is making sure all errors are handled. For v0.1 we can just check each error!=nil and panic or bubble up the error. 

See the readme instructions for how to run linters locally

https://github.com/cosmos/interchain-security/blob/657aaea0a6ed97f3a04d906186d353c56bef8d5e/README.md?plain=1#L69-L97

https://github.com/securego/gosec

For linter problems in /integration-tests, we can disable the checks.

**Comment by smarshall-spitzbart** [comment]
Makes sense 👍 

On disabling these checks for integration tests - Is there a config file seen by the cloud builds to disable certain folders from linting? Achieving the same thing as [this](https://github.com/securego/gosec#excluding-test-files-and-folders). Alternatively I can [annotate each vulnerability instance](https://github.com/securego/gosec#annotating-code) that should be ignored, which seems like the better practice solution

**Comment by danwt** [comment]
Great question @smarshall-spitzbart, feel free to choose which way. If using the directory exclude approach you would probably have to edit this file

https://github.com/cosmos/interchain-security/blob/main/.github/workflows/gosec.yml
