### ISSUE TITLE
Move validation into the message handlers

### ISSUE THREAD

**Issue by insumity** [cosmos/interchain-security#2275]
## Problem

Currently, we validate messages with `ValidateBasic` (e.g., see [`MsgAssignConsumerKey`](https://github.com/cosmos/interchain-security/blob/v6.0.0/x/ccv/provider/types/msg.go#L73)).  However, this [way of validating is deprecated](https://docs.cosmos.network/main/build/building-modules/msg-services#validation). This issue is a reminder that we should move validation to the message handlers (e.g., in [`AssignConsumerKey`](https://github.com/cosmos/interchain-security/blob/v6.0.0/x/ccv/provider/keeper/msg_server.go#L52)).

**Comment by mpoke** [comment]
Closing as duplicate. See https://github.com/cosmos/interchain-security/issues/2149
