### ISSUE TITLE
UnboundMaturePackets Returning Error

### ISSUE THREAD

**Issue by smarshall-spitzbart** [cosmos/interchain-security#228]
#225 implements changes necessary for gosec tests to pass. One such change is no longer ignoring the error that is returned from [UnbondMaturePackets](https://github.com/cosmos/interchain-security/blob/main/x/ccv/consumer/keeper/relay.go#L78) when the provider channel is not set in the consumer's [end block routine](https://github.com/cosmos/interchain-security/blob/main/x/ccv/consumer/module.go#L185). 

Due to the fact that [we no longer ignore this error](https://github.com/cosmos/interchain-security/blob/make-gosec-pass/x/ccv/consumer/module.go#L187) in #225, and instead panic, the keeper tests fail. The test suite is calling the end block routine while setting up the chains for testing, which causes the panic.

One option is to assert the provider channel is populated before calling UnboundMaturePackets in the end block routine, and otherwise move on without panic. 
```go
_, ok := am.keeper.GetProviderChannel(ctx)
if !ok {
	return []abci.ValidatorUpdate{}
}
err = am.keeper.UnbondMaturePackets(ctx)
if err != nil {
	panic(err)
}
```

Any opinion on that @mpoke @danwt ?

Relavant PR: https://github.com/cosmos/interchain-security/pull/146

**Comment by mpoke** [comment]
Nice catch @smarshall-spitzbart. Yeah, `UnbondMaturePackets` should be a noop if there is no established channel to the provider, i.e., 
```golang
func (k Keeper) UnbondMaturePackets(ctx sdk.Context) error {
	channelID, ok := k.GetProviderChannel(ctx)
	if !ok {
		return nil
	}

	store := ctx.KVStore(k.storeKey)
	maturityIterator := sdk.KVStorePrefixIterator(store, []byte(types.PacketMaturityTimePrefix))
	defer maturityIterator.Close()

	// ... 
}
```

**Comment by danwt** [comment]
Yes nice catch and simple solution @smarshall-spitzbart
