### ISSUE TITLE
`validatorUnbondingCanComplete` must take into account (re)bonded validators

### ISSUE THREAD

**Issue by danwt** [cosmos/interchain-security#232]
By the time a mature VSC is received on the provider side mapping to a validator unbonding operation the validator can already be rebonded!

We must take this into account in the code. Changes will be needed at least here

https://github.com/cosmos/cosmos-sdk/blob/c783aea68fbd856c2b188b2d467a7fa5cb4df1e6/x/staking/keeper/unbonding.go#L326-L346

```go
func (k Keeper) validatorUnbondingCanComplete(ctx sdk.Context, id uint64) (found bool, err error) {
	val, found := k.GetValidatorByUnbondingId(ctx, id)
	if !found {
		return false, nil
	}


	if !val.IsMature(ctx.BlockTime(), ctx.BlockHeight()) {
		val.UnbondingOnHold = false
		k.SetValidator(ctx, val)
	} else {
		// If unbonding is mature complete it
		val = k.UnbondingToUnbonded(ctx, val)
		if val.GetDelegatorShares().IsZero() {
			k.RemoveValidator(ctx, val.GetOperator())
		}


		k.DeleteUnbondingIndex(ctx, id)
	}


	return true, nil
}
```

In the above, if the validator is already rebonded `k.UnbondingToUnbonded` can be called triggering a panic.

I am really confirmed about the following case, in addition to what is explicit above. Consider:

1. A validator unbonds which causes VSC `0` to go out
2. The validator rebonds
3. The validator unbonds which causes VSC `1` to go out
4. Maturity for `0` comes in, and the `if !val.IsMature(ctx.BlockTime(), ctx.BlockHeight()) ` branch is entered
5. val.UnbondingOnHold is set false
6. The validator unbonding for `1` completes BEFORE maturity for `1` is received

I will make a PR soon.

Found with diff testing - although, it's interesting because in the diff model I do not model explicity all the data structures. Because of that, the diff model will search the validator unbonding queue for a validator with `opID == opID` before doing anything, which avoids the problem. Still though, the model is able to generate the example case.

**Comment by danwt** [comment]
Any fix must take care of state cleanup, which is a bit nuanced. See also this issue

- https://github.com/cosmos/interchain-security/issues/103

for taking care of leaks.

**Comment by danwt** [comment]
Was fixed by

- https://github.com/cosmos/cosmos-sdk/commit/67c81635b48358eea240a881c7f5d88e4f06616e

**Comment by mpoke** [comment]
> Was fixed by
>
> https://github.com/cosmos/cosmos-sdk/commit/67c81635b48358eea240a881c7f5d88e4f06616e

Fixed by https://github.com/cosmos/cosmos-sdk/pull/12796

**Comment by danwt** [comment]
Closing for now as fixed by https://github.com/cosmos/cosmos-sdk/pull/12796
