### ISSUE TITLE
Depreciated Proto Package

### ISSUE THREAD

**Issue by smarshall-spitzbart** [cosmos/interchain-security#236]
While fixing up the ```golangci-lint``` errors in #235, it was found that the proto package used in [proposal_test.go](https://github.com/cosmos/interchain-security/blob/main/x/ccv/provider/types/proposal_test.go#L8) is depreciated. 

Attempting to use the suggested ```google.golang.org/protobuf/proto``` package url disallows the file from being compiled, since the newer version of [proto.Equal](https://github.com/cosmos/interchain-security/blob/main/x/ccv/provider/types/proposal_test.go#L119) requires that ```types.CreateConsumerChainProposal``` implements ```ProtoReflect```.

It seems that we need to compile pb files using a newer version of ```protoc```. Maybe there's an easy solution that I'm missing, but it doesn't seem as easy as [changing a version number](https://github.com/cosmos/interchain-security/blob/make-golangci-pass/Makefile#L27) in the makefile.

Most relevant PR I could find for the issue: https://github.com/cosmos/interchain-security/pull/92

@marbar3778 Any ideas here?

**Comment by marbar3778** [comment]
the cosmos ecosystem still uses go proto APIv1, protoreflect it API v2. We are working towards migrating but for now we have to either use gogo/proto or the old library for gloat protobuf

**Comment by jtremback** [comment]
Should this issue be closed @marbar3778 @smarshall-spitzbart ? It sounds like a wontfix
