### ISSUE TITLE
Test Validator Downtime in Integration Tests

### ISSUE THREAD

**Issue by smarshall-spitzbart** [cosmos/interchain-security#256]
We need to integration test the voting power of validators when a downtime has occurred. This should be tested for both a downtime observed on a consumer chain, and a downtime observed on a provider chain.

**Comment by danwt** [comment]
Hey, I don't have experience simulating network partitions locally but a quick search turned up

- https://wiki.linuxfoundation.org/networking/netem linux util
- https://github.com/jepsen-io/jepsen jepsen distr sys network sim
- https://github.com/worstcase/blockade blockage docker network partition sim

I'm just putting here for curiosities sake, I'm not necessarily advocating adding a dependency

**Comment by smarshall-spitzbart** [comment]
> Hey, I don't have experience simulating network partitions locally but a quick search turned up
> 
> * https://wiki.linuxfoundation.org/networking/netem linux util
> * https://github.com/jepsen-io/jepsen jepsen distr sys network sim
> * https://github.com/worstcase/blockade blockage docker network partition sim
> 
> I'm just putting here for curiosities sake, I'm not necessarily advocating adding a dependency

Nice finds! There's probably multiple ways this issue could have been solved, those links seem like viable tools for the problem. Jehan had used network namespaces previously, and found [this article](https://adil.medium.com/container-networking-under-the-hood-network-namespaces-6b2b8fe8dc2a) which ended up walking us through the exact steps  we needed
