### ISSUE TITLE
`StopConsumerChainProposal` to unlock unbondings locked with `LockUnbondingOnTimeout`

### ISSUE THREAD

**Issue by mpoke** [cosmos/interchain-security#261]
Let A be a consumer chain that was proposed with `LockUnbondingOnTimeout = true` (the default is `false`). In case a timeout occurs on the CCV channel between consumer A and the provider, then A is stopped (for security reasons) and all the pending unbonding operations (e.g., undelegations) will be **_locked_**. This means that these unbonding operation will not complete. 

Due to the changes in PR https://github.com/cosmos/interchain-security/pull/254, a proposal `StopConsumerChainProposal(chainId)` will be dropped if there is no consumer with `chainId`. This means that `StopConsumerChainProposal` cannot be used to **_unlock_** those unbondings (since consumer A was already removed when the CCV channel timed out). To solve this, I think we should handle `StopConsumerChainProposal`s even for non existing chain IDs.

**Comment by jtremback** [comment]
This basically just adds another case for us to test, right? Instead of StopConsumerChainProposal with nonexistent ChainId being undefined behavior and disallowed, we now have to make sure it all works properly.

Personally, for v0.1, I think we should make it so that `LockUnbondingOnTimeout` can only equal `false`.

**Comment by mpoke** [comment]
> This basically just adds another case for us to test, right? Instead of StopConsumerChainProposal with nonexistent ChainId being undefined behavior and disallowed, we now have to make sure it all works properly.

Yes, but it already works properly. Just looked over the code: it shouldn't be a problem to call `StopConsumerChainProposal(chainId)` with a nonexisting `chainId`.

> Personally, for v0.1, I think we should make it so that LockUnbondingOnTimeout can only equal false.

I agree.

**Comment by danwt** [comment]
Are we releasing with `LockUnbondingOnTimeout`? I remember some discussion about this being completely removed as a concept.

**Comment by jtremback** [comment]
Looking into this

**Comment by jtremback** [comment]
Here is `StopConsumerChain`:

```
func (k Keeper) StopConsumerChain(ctx sdk.Context, chainID string, lockUbd, closeChan bool) (err error) {
	// check that a client for chainID exists
	if _, found := k.GetConsumerClientId(ctx, chainID); !found {
		// drop the proposal
		return nil
	}
```

Looks like the proposal is dropped if the clientID is not found. Personally I'm not sure right now whether this means that proposals for consumer chains that have already been timed out will never be able to be unlocked as this issue suggests, but it seems like that's a possibility.

**Comment by jtremback** [comment]
Ah yes, we hardcode `lockUbdOnTimeout` when consumer chains are created

```
func (k Keeper) HandleConsumerAdditionProposal(ctx sdk.Context, p *types.ConsumerAdditionProposal) error {
	if !ctx.BlockTime().Before(p.SpawnTime) {
		// lockUbdOnTimeout is set to be false, regardless of what the proposal says, until we can specify and test issues around this use case more thoroughly
		return k.CreateConsumerClient(ctx, p.ChainId, p.InitialHeight, false)
	}
```

Should probably consider removing it entirely, or figuring out what we want to do.

**Comment by jtremback** [comment]
I'm going to make the call that we should remove this field entirely until we decide to bring it back.

**Comment by mpoke** [comment]
Closing as no longer needed.
