### ISSUE TITLE
Handle EmitEvent in CCV modules

### ISSUE THREAD

**Issue by mpoke** [cosmos/interchain-security#279]
Requirements to close:

- [ ] remove unnecessary `EmitEvent`s, e.g., https://github.com/cosmos/interchain-security/blob/eaa7f6e7ef98fa16b38e6213a194506dc9d50f26/x/ccv/provider/module.go#L364
- [ ] add relevant `EmitEvent`s (e.g., needed for checking invariants during testnet)

**Comment by jtremback** [comment]
Closed in favor of https://github.com/cosmos/interchain-security/issues/356
