### ISSUE TITLE
Replace hardcoded constants with params

### ISSUE THREAD

**Issue by mpoke** [cosmos/interchain-security#280]
Identify hardcoded constants, e.g., https://github.com/cosmos/interchain-security/blob/eaa7f6e7ef98fa16b38e6213a194506dc9d50f26/x/ccv/types/utils.go#L6

and remove unwanted ones (i.e., replace with params).

**Comment by jtremback** [comment]
Should go into app.go actually, and be passed in NewKeeper or similar

**Comment by MSalopek** [comment]
Should we also consider using a linter like `golangci-lint` to pick up on stuff like in the future?

**Comment by jtremback** [comment]
These should all be replaced by params, pretty straightforward.

https://github.com/cosmos/interchain-security/blob/main/x/ccv/consumer/keeper/distribution.go#L17
https://github.com/cosmos/interchain-security/blob/main/x/ccv/consumer/keeper/distribution.go#L22
https://github.com/cosmos/interchain-security/blob/main/x/ccv/consumer/types/keys.go#L24

These two:

https://github.com/cosmos/interchain-security/blob/main/x/ccv/provider/types/params.go#L16
https://github.com/cosmos/interchain-security/blob/main/x/ccv/provider/types/params.go#L19

are only used here:

https://github.com/cosmos/interchain-security/blob/main/x/ccv/provider/types/params.go#L66

and they seem to be placeholders that affect nothing. IMO I would move them inline to the function.

**Comment by jtremback** [comment]
I can't believe that's it. @mpoke Do you think I'm missing any?

**Comment by mpoke** [comment]
```bash
> ack "const " x

x/ccv/types/utils.go
6:const TimeDelay = 4 * 7 * 24 * time.Hour

x/ccv/provider/types/params.go
13:const (

x/ccv/utils/utils.go
18:const TrustingPeriodFraction = 2

x/ccv/consumer/types/params.go
10:const DefaultBlocksPerDistributionTransmission = 1000

x/ccv/consumer/types/keys.go
10:const (

x/ccv/consumer/keeper/distribution.go
17:const TransferTimeDelay = 1 * 7 * 24 * time.Hour // 1 weeks
22:const ConsumerRedistributeFrac = "0.75"
```

**Comment by jtremback** [comment]
`const TrustingPeriodFraction = 2` should be made a param as well.

**Comment by mpoke** [comment]
> `const TrustingPeriodFraction = 2` should be made a param as well.

And the default should be 3/2 as is the case on many Cosmos chains, i.e., `TrustingPeriod = 2/3 UnbondingPeriod`
