### ISSUE TITLE
Delete consumer genesis from provider

### ISSUE THREAD

**Issue by mpoke** [cosmos/interchain-security#282]
Delete the consumer genesis once the CCV channel for the chainID is OPEN since we no longer need to store it on provider chain.

**Comment by mpoke** [comment]
When exactly can we delete this?

**Comment by jtremback** [comment]
As soon as the channel comes up I guess? We can probably skip fixing this for at least a year and take the maybe 1000kb at most hit to storage for now.

**Comment by mpoke** [comment]
I agree that is not urgent. The problem that I see is that you need 2/3+ of the voting power to start the consumer chain. Let's say that this happens and the CCV channel is established. We delete the consumer genesis from the provider and then one validator from the remaining 1/3 of the voting power wants to start the consumer binary. It must start from genesis, right? 

I think we can close this issue since we remove the genesis state when removing a consumer chain. I think it's okay to store a genesis state for every registered consumer.
