### ISSUE TITLE
Democracy governance whitelisting

### ISSUE THREAD

**Issue by jtremback** [cosmos/interchain-security#284]
The democracy module described [here](https://github.com/cosmos/interchain-security/issues/141) works. We now need to make sure that the consumer chain governance cannot pass proposals that would be dangerous for the provider chain.

Here is a matrix containing all the parameters that the consumer chain governance should be able to change: https://docs.google.com/spreadsheets/d/1s7IGkxIjvebFu0guC5iFC4gWaEOJLBWx2QQHik9WmYo/edit?pli=1#gid=0 (thanks @okwme and @Sam-Interchain)

Implement a mechanism to prevent the democracy module from passing certain proposals, and input the whitelist into this mechanism.

Note, you will likely need to allow/disallow passing of any proposal of a given type (eg chain upgrade proposals), as well as looking into proposals of a certain type and allow/disallowing them more granularly (eg parameter changes).

Conditions of satisfaction:
- It is possible to encode this whitelisting functionality either as code in the consumer chain binary (might be easier), or in a serialized form (nice, if it is possible)
- Demonstrate that some gov proposals are not possible to execute (easier) or even create (nice, if it is possible)
- Demonstrate that some gov proposals are still possible to execute

**Comment by mpoke** [comment]
@jtremback @stana-ethernal  I think this issue was fixed by https://github.com/cosmos/interchain-security/pull/364, right? 

@jtremback Should we open an issue to enable upgrading the consumer through consumer governance as long as the upgrade doesn't touch specific modules (e.g., ccv, slashing, evidence).

**Comment by stana-ethernal** [comment]
> @jtremback @stana-ethernal I think this issue was fixed by #364, right?
yes, it is fixed
