### ISSUE TITLE
Implement provider-driven governance

### ISSUE THREAD

**Issue by jtremback** [cosmos/interchain-security#285]
@okwme says:

> The primary proposal type that imo should be performed by ATOM token holders is the upgrade proposal. Our messaging is that ATOM validators don't need to worry about gov on these consumer chains because they have their own gov tokens. This is true except for factors that impact the validator directly. Upgrades need to be prepared and performed by validators so I think it's important they happen on the hub where validators are still meant to be active.
> 
> This would be possible by leveraging the adminmodule inside of the composer repo: https://github.com/cosmos/composer/tree/master/x/adminmodule
> If the Cosmos Hub gov module account were listed in the whitelist then the cosmos hub gov module could send out proposal + vote msgs using interchain accounts. That way it is voted on the hub and if it passes it is submitted to the consumer chain and immediately passed.

We need to implement the ability to allow the provider chain to pass governance proposals on the consumer, for example upgrade proposals.

**Comment by mpoke** [comment]
@jtremback I think https://github.com/cosmos/interchain-security/issues/162 is related.
