### ISSUE TITLE
Closing non-CCV channels on provider

### ISSUE THREAD

**Issue by mpoke** [cosmos/interchain-security#293]
The provider CCV module should close channels attempting to complete the opening handshake if there is already an established CCV channel, see https://github.com/cosmos/interchain-security/blob/f3a996699756bc223a168cb0b8886a355204c19e/x/ccv/provider/keeper/keeper.go#L275

I see the following problem with the current implementation: `SetConsumerChain` is called by `OnChanOpenConfirm`, which means the error returned here https://github.com/cosmos/interchain-security/blob/f3a996699756bc223a168cb0b8886a355204c19e/x/ccv/provider/keeper/keeper.go#L279 will abort the execution of `ChannelOpenConfirm` here https://github.com/cosmos/ibc-go/blob/05c4bfbbebb20d1cc078ddf1d29dadc766d9251b/modules/core/keeper/msg_server.go#L306. As a result, all the changes done by `channelKeeper.ChanCloseInit` (i.e., moving the channel to `CLOSED`) will be reverted.

**_Potential solution:_** 
The calls to `channelKeeper.ChanCloseInit` should be defer to `EndBlock`.

**Comment by mpoke** [comment]
@AdityaSripal do you agree?

**Comment by jtremback** [comment]
Is this a bug or is it just garbage collection?
