### ISSUE TITLE
Implementation and spec divergence

### ISSUE THREAD

**Issue by danwt** [cosmos/interchain-security#299]
The spec and implementation allow different committed block states, given the same transactions.

Consider an execution, per the spec:

```
a validator unbonding maturity arrives on provider
the maturity is processed, setting refCnt = 0
the staking module EndBlock processes the validator and it becomes UNBONDED becaue refCnt = 0

End result: validator committed state is UNBONDED
```

([code](https://github.com/cosmos/ibc/blob/0a43605fe869e1cf004103dd0f6994e9d8b81055/spec/app/ics-028-cross-chain-validation/methods.md?plain=1#L1293))

Consider an execution, per the code:

```
a validator unbonding maturity arrives on provider
the maturity is stored for later processing
the staking module EndBlock processes the validator but it stays in UNBONDING becaue refCnt = 1
the maturity is processed setting refCnt = 0

End result: validator committed state is UNBONDING
```

 ([code](https://github.com/cosmos/interchain-security/blob/3416e4c1a40e70d0daf08e193289a2848c30f62f/x/ccv/provider/keeper/relay.go#L61))

**Comment by danwt** [comment]
I created this other issue which was a false positive, because I hadn't properly understood the root cause of a trace.

- https://github.com/cosmos/interchain-security/issues/298

**Comment by mpoke** [comment]
Nice catch @danwt. The spec needs to be updated. Could you please open an issue on cosmos/ibc?

**Comment by jtremback** [comment]
Looks like the creation of the issue on IBC spec resolved the issue here
