### ISSUE TITLE
Improve coverage around starting/stopping/restarting

### ISSUE THREAD

**Issue by jtremback** [cosmos/interchain-security#306]
Our coverage around the transitions in the protocol is spotty.

**What currently exists:**

- Implicit coverage around happy path, basic case consumer chain startup in e2e and integration tests because otherwise the tests wouldn't work.
- channel_init_test.go
  - TestConsumerGenesis:
    - checks certain values in a genesis exported from a consumer after happy path setup are correct
    - runs InitGenesis and then sets the test up again, which I believe may simulate a consumer restart
    - checks various values in the restarted consumer chain
    - sends a VSC packet,
    - then exports and restarts the genesis again, this time filling in InitialValSet
    - NOTE: it's not clear to me what degree of coverage this test provides, seems to check a lot of things but I don't know if it checks everything and it is only in one scenario.
  - Other tests: Appear to be relatively complete unit tests 
- There are no unit tests for the provider equivalent to the tests of the consumer's IBC handshake methods in channel_init_test.go
- stop_consumer_test.go: 
  - TestStopConsumerChain: Creates a bunch of state related to a consumer chain and then stops the chain, checks that the state is removed
  - TestStopConsumerChainProposal: Checks various outcomes of a consumer chain stopping gov proposal
  - TestStopConsumerOnChannelClosed: Checks that the IBC channel is closed when the consumer chain is stopped.

**What we should have:**

- Differential testing or MBT around the interleavings of CCV's IBC handshake steps with consumer and provider restarts, pending vsc and slashing packets, and possibly other events that I am forgetting right now. 
  - @danwt recommends that we use a different model than the one used for protocol operation to avoid it getting too big. 
  -  Someone with a good understanding of IBC handshake steps might be able to make the fastest progress on this- @mpoke any appetite for this? Maybe I start up a rough version so that you can easily drop in and write logic without getting bogged down on engineering details.
  - Can this include timeouts or is that too much? If we don't want to include timeouts here, how do we cover them better?
- Integration tests of scenarios we especially care about to "prove that they work".
  - Sovereign to consumer transition. This will also need to run a third chain that is connected to the consumer chain over IBC to check that the IBC connection on the third chain stays up after the transition.
  - Basic restarting of provider and consumer chains in the integration testnet. This is already partially tested by the unit tests, and may be tested by the diff tests, but it would be nice to do it "for real".
  - Worst case scenario consumer chain failure. Consumer chain stops completely and we need to wait for channel to timeout- what's the longest that unbondings on the provider are frozen for? Can we test the validator set taking action by fabricating VSCMature packets or something?
- Improving unit tests. This is lower priority because most things should be covered by diff tests
  - Adding the missing provider-side handshake unit tests
  - Going over everything with a fine-tooth comb and checking that there aren't missing cases.
  - More extensive coverage of anything which cannot be fit into the diff tests.

Am I missing anything?

**Comment by danwt** [comment]
> recommends that we use a different model than the one used for protocol operation to avoid it getting too big.

Indeed. 

Consider the initial state `S` of the current 'core' model. If we create a separate e.g. handshake/init model and show it eventually reaches `S` (given some assumptions) then the models are connected via argument and there's no need to actually have them share any code.

**Comment by mpoke** [comment]
> > recommends that we use a different model than the one used for protocol operation to avoid it getting too big.
> 
> Indeed.
> 
> Consider the initial state `S` of the current 'core' model. If we create a separate e.g. handshake/init model and show it eventually reaches `S` (given some assumptions) then the models are connected via argument and there's no need to actually have them share any code.

Currently, diff-testing is set with a single consumer. Clearly, for testing the _Initialization_ and _Consumer Chain Removal_ subprotocols, we need more consumers. As already mentioned by @jtremback, these tests should enable the interleaving of different actions possible in these subprotocols (e.g., a relayer submits a `ChanOpenInit` message) with actions possible in the _Validator Set Update_ and _Consumer Initiated Slashing_ subprotocols. For example, concern 4.04 from the [quality assurance plan](https://github.com/cosmos/interchain-security/blob/main/docs/quality_assurance.md#provider-chain-correctness) requires that unbonding operations complete even if a channel handshake fails. As a result, I don't know how easy would be to keep the models completely separated.

**Comment by mpoke** [comment]
> Someone with a good understanding of IBC handshake steps might be able to make the fastest progress on this- @mpoke any appetite for this? Maybe I start up a rough version so that you can easily drop in and write logic without getting bogged down on engineering details.

Sure. I could do this. The only barrier is that I have no experience with Typescript, so I'll need help there.

**Comment by smarshall-spitzbart** [comment]
Unit testing part of original post will be completed by #342

**Comment by mpoke** [comment]
@MSalopek @p-offtermatt is this issue still relevant?

**Comment by p-offtermatt** [comment]
Closing since difftest model was deprecated in favor of MBT, may reopen if we want this in the MBT model
