### ISSUE TITLE
CCV channel init e2e tests should be unit tests

### ISSUE THREAD

**Issue by smarshall-spitzbart** [cosmos/interchain-security#309]
Many of the tests in ```e2e-tests/channel_init_test.go``` should actually be unit tests and moved to ```provider/ibc_module_test.go``` and ```consumer/ibc_module_test.go```. Especially the one testing the OnChan… handlers.

This migration will take an additional level of test setup, in that the IBC testing suite has a lot of background niceties that unit tests would not have (setting up channels in-mem, connections, etc.)

**Comment by jackzampolin** [comment]
have y'all looked into https://github.com/strangelove-ventures/ibctest for the e2e testing

**Comment by smarshall-spitzbart** [comment]
Cool stuff! This would align with integration tests per the semantics of this repo. Integration tests were first built before my time here. But I believe the decision to use a hand-rolled testing framework had to do with the code they were building off of, and what worked the quickest at the time
