### ISSUE TITLE
Test full unbonding functionality in integration tests

### ISSUE THREAD

**Issue by smarshall-spitzbart** [cosmos/interchain-security#311]
https://github.com/cosmos/interchain-security/issues/94 added a simple check that validator powers are changed when an ```unbond``` tx is submitted. We still need to test token liquidity after unbonding period has elapsed, and any anything else that's related to full unbonding hooks

This will require genesis file manipulation, see ```genesisChanges``` in ```integration-tests/config.go``` as example

**Comment by danwt** [comment]
Echoing the comment here

- https://github.com/cosmos/interchain-security/issues/509#issuecomment-1332338982

I think testing this with integration tests is not a valuable use of time. It's already fairly thoroughly covered by diff tests and @MSalopek is improving that even more.

**Comment by danwt** [comment]
I'm going to close for now, please reopen and justify as you see fit.

**Comment by smarshall-spitzbart** [comment]
As mentioned in the other issue, integration tests for unbonding functionality would be a sanity check that the real system works. I'm fine closing this issue so long as full unbonding is being validated in the testnet. @jtremback or @mpoke could you confirm this is the case?

**Comment by jtremback** [comment]
re-closing in favor of [#361](https://github.com/cosmos/interchain-security/issues/361)
