### ISSUE TITLE
difftest core: model and test Redelegate operations

### ISSUE THREAD

**Issue by danwt** [cosmos/interchain-security#318]
The diff testing model for the 'core' (normal operation) includes operations for deletage/undelegate but not redelegate.

Redelegate should be modelled and tested.

## Closing criteria

- [ ] Add a redelegate action to model.ts
- [ ] Change the go driver to take redelegate actions

## Resources

- Diff testing core model [README](https://github.com/cosmos/interchain-security/blob/ab19d8402fb7c16a4be8ae8002ff77a25cc25d08/diff-tests/core/README.md)
- SDK Redelegate operation [code](https://github.com/cosmos/cosmos-sdk/blob/main/x/staking/keeper/msg_server.go#L269-L335)

**Comment by danwt** [comment]
@jtremback, @MSalopek this could be a good first one for getting into the diff testing.

**Comment by p-offtermatt** [comment]
Closing since we deprecated the difftest model, may reopen if we need this in the MBT model
