### ISSUE TITLE
difftest core: model and test Unjail operations

### ISSUE THREAD

**Issue by danwt** [cosmos/interchain-security#319]
The diff testing model for the 'core' (normal operation) includes operations slashing (and therefore jailing) but not unjailing.

Unjailing should be modelled and tested.

## Closing criteria

- [ ] Add an unjail action to the model
- [ ] Add unjail data to trace.go
- [ ] Use and test unjail actions in the driver

## Resources

- Diff testing core model [README](https://github.com/cosmos/interchain-security/blob/ab19d8402fb7c16a4be8ae8002ff77a25cc25d08/diff-tests/core/README.md)

**Comment by danwt** [comment]
@jtremback, @MSalopek this could be a good first one for getting into the diff testing.

See also https://github.com/cosmos/interchain-security/issues/318

**Comment by p-offtermatt** [comment]
Closing since difftest model was deprecated in favor of MBT, may reopen if we want this in the MBT model
