### ISSUE TITLE
use expected_keepers for staking hooks

### ISSUE THREAD

**Issue by tac0turtle** [cosmos/interchain-security#329]
Is there a reason why staking hooks template is used over StakingHooks interface like 

https://github.com/cosmos/cosmos-sdk/blob/2a813177b207d85078263fe5900d6912b5c8dd24/x/slashing/types/expected_keepers.go#L61?

**Comment by mpoke** [comment]
@tac0turtle Is this issue still relevant?

**Comment by tac0turtle** [comment]
I would say yes, since the hook template file was not merged

**Comment by mpoke** [comment]
@sainoe Do you know how to address this?

**Comment by sainoe** [comment]
Yes, I can change this
