### ISSUE TITLE
Staking changes that do not change the validator set

### ISSUE THREAD

**Issue by mpoke** [cosmos/interchain-security#33]
This issue was pointed to me by Cezara.

The issue appears when the voting power of the validator set remains the same, but the delegations change. For example, let `V` be a validator and `D` one of its delegators. If during a block `B`, `D` starts unbonding `x` tokens from `V` and another delegator `D'` bonds `x` tokens to `V`, then by the end of `B`, the voting power of `V` remains unchanged. If no other changes happen, then the staking module sends no validator set update to Tendermint. In the context of CCV, this means that the provider chain sends no `ValidatorSetChangePacket` to the consumer chain, which means no ACK and thus, `D` never receives its `x` tokens. 

**Solution**: If there are any unbonding operations initiated during a block, then the provider CCV module MUST send a `ValidatorSetChangePacket` even if the list of validator updates obtained from the staking module is empty.

**Comment by mpoke** [comment]
The fix described about would require a change in the `ValidateBasic` method of the `ValidatorSetChangePacketData`, i.e., https://github.com/cosmos/interchain-security/blob/c4ce132b75087818873e769a828ccb4db36df74e/x/ccv/types/ccv.go#L17

**Comment by mpoke** [comment]
A fix for this issue is specified in https://github.com/cosmos/ibc/pull/646

**Comment by danwt** [comment]
I think the scenario should also occur with one delegator (so D' = D).

**Comment by mpoke** [comment]
> I think the scenario should also occur with one delegator (so D' = D).

I agree. The solution mention in the description would handle this case also.

**Comment by danwt** [comment]
Sweet. Just confirming myself as it's easier to test with only one
