### ISSUE TITLE
Make symbol names consistent

### ISSUE THREAD

**Issue by danwt** [cosmos/interchain-security#331]
I think we would benefit from making a pass through the code and making all like variables names/ function names ect a bit more consistent/precise.

Some examples off the top of my head

- CreateConsumerChainProposal sounds like it creates a proposal but it actually handles one
- CreateConsumerClient has asymmetry with StopConsumerChain
- UnbondingPeriod/UnbondingTime/UnbondingDuration
- ValidatorSetUpdate/ValidatorSetChange/VSC
- UnbondingCanComplete should now be more like 'decrement ref cnt' (similar for PutUnbondingOnHold)

I will add some examples as I come across them again.

**Comment by jtremback** [comment]
Thanks for putting this list together. Agree on most of these

**Comment by smarshall-spitzbart** [comment]
Agreed on your points. A PR I'm working on right now will address the first two you mentioned. 

Regarding
> CreateConsumerClient has asymmetry with StopConsumerChain

do you mean that StopConsumerChain does not clean up all the relevant state that is created in CreateConsumerClient? Curious what problem asymmetry causes here

**Comment by smarshall-spitzbart** [comment]
Working on unit tests rn and I have a method called ```TestHandleCreateConsumerChainProposal```, oof 😆 

How does changing ```CreateConsumerChainProposal``` to ```ConsumerAdditionProposal``` sound?

**Comment by danwt** [comment]
> ConsumerAdditionProposal

Good enough!

**Comment by mpoke** [comment]
> Working on unit tests rn and I have a method called `TestHandleCreateConsumerChainProposal`, oof 😆
> 
> How does changing `CreateConsumerChainProposal` to `ConsumerAdditionProposal` sound?

In the [spec](https://github.com/cosmos/ibc/blob/main/spec/app/ics-028-cross-chain-validation/data_structures.md#ccv-data-structures) is called `SpawnConsumerChainProposal`

**Comment by smarshall-spitzbart** [comment]
> In the [spec](https://github.com/cosmos/ibc/blob/main/spec/app/ics-028-cross-chain-validation/data_structures.md#ccv-data-structures) is called SpawnConsumerChainProposal

Imo the main confusion is starting with a verb, which is still the case with ```SpawnConsumerChainProposal```

**Comment by danwt** [comment]
Closing as finished criteria are not strong enough. We should reopen for similar in future.
