### ISSUE TITLE
expand .golangci-lint yaml

### ISSUE THREAD

**Issue by MSalopek** [cosmos/interchain-security#333]
In the future we could consider expanding our linter rules and running them as pre-commit hooks.

The rules can be discussed as we go along and changed if we deem a new rule is needed or some rule is making too much noise.

We could use https://gist.github.com/MSalopek/191fc6e493286aab33448506d2fecebe as a starting point (used for some minor cleanup operations).

The full reference is available here:
- https://github.com/golangci/golangci-lint/blob/master/.golangci.reference.yml

It could be beneficial to have slightly different linting rules for tests to reduce unnecessary linting errors/warning.

**Comment by danwt** [comment]
Hey, I agree with this. Please feel free to update the golangci-lint.yml as you see fit.
