### ISSUE TITLE
Find workaround for failing sonar builds when making PR from forks

### ISSUE THREAD

**Issue by MSalopek** [cosmos/interchain-security#334]
For PR #332 SonadrCloud build fails after fetching dependencies.
- https://github.com/cosmos/interchain-security/runs/8229050761?check_suite_focus=true

Since the PR was made from a fork, it is possible that not all env variables are set correctly.

@danwt

**Comment by danwt** [comment]
It's probably something to with how secrets are configured

https://github.com/cosmos/interchain-security/blob/b81a07d58cdee75529204773c26d90afd2432c0e/.github/workflows/build.yml#L28-L29

I think @marbar3778 was the one who set up the secrets. Do I remember right? Are you please able to help?


cc @dusan-ethernal 

Resource

- https://community.sonarsource.com/t/github-action-ci-build-fail-with-set-the-sonar-token-env-variable/38997/3

**Comment by marbar3778** [comment]
secrets are not injected when a fork interacts with your repo. this is due to security settings of GitHub

**Comment by danwt** [comment]
Cool, I guess this is won't fix then, for now.

We can open a new issue for an alternative/ work around.

**Comment by danwt** [comment]
Reopened: we should find a workaround, because allowing people to make PRs from forks is a good thing.

**Comment by mpoke** [comment]
Closing for now.
