### ISSUE TITLE
`ccvTimeoutTimestamp` param

### ISSUE THREAD

**Issue by jtremback** [cosmos/interchain-security#338]
It should be moved into the `tests/` folder to reduce the size of the main codebase and reduce potential confusion.

**Comment by mpoke** [comment]
It is also used here https://github.com/cosmos/interchain-security/blob/5e3ff16033d045551f71e76425659f0989a81833/x/ccv/utils/utils.go#L79

**Comment by jtremback** [comment]
Very good point. Must have missed that. It is used on every send. 

Still, I would make a few changes.

`types/utils.go` should not be its own file. The function is so short that it should just be done inline where it is used.
`const TimeDelay = 4 * 7 * 24 * time.Hour` should not be a magic number any more. It should be put into a param called `IBCTimeoutTimestamp`. This will need to be passed into `SendIBCPacket` because it's not a function on the keeper struct and does not have access to the params stuff.

**Comment by mpoke** [comment]
> It should be put into a param called IBCTimeoutTimestamp.

For consistency, I'd use the names from the [spec](https://github.com/cosmos/ibc/blob/main/spec/app/ics-028-cross-chain-validation/data_structures.md#ccv-state), i.e., `ccvTimeoutTimestamp`. We need to differentiate it from the transfer timeout timestamp, i.e., `transferTimeoutTimestamp`, see https://github.com/cosmos/interchain-security/blob/b6aff82c471b4d86b990c80aeee4401442ae7671/x/ccv/consumer/keeper/distribution.go#L17
