### ISSUE TITLE
`params.Enabled` on the consumer is basically unused and should be deleted.

### ISSUE THREAD

**Issue by jtremback** [cosmos/interchain-security#339]
If `params.Enabled` is set to `false` in the genesis.json, then the consumer chain will not return a validator set on startup. Since the consumer chains have a disabled staking module, this will lead to a chain that is unable to start, making this a useless parameter.

If `params.Enabled` is set to `false` during running of the consumer chain, nothing will happen except that the consumer's CCV genesis state will no longer be correctly exported.

It is not useful and should be completely removed.

**Comment by smarshall-spitzbart** [comment]
Here's a comment that suggests `enabled` is a necessary part of the IBC testing suite https://github.com/cosmos/interchain-security/blob/main/x/ccv/consumer/keeper/params_test.go#L17
