### ISSUE TITLE
InitGenesis on consumer should return a list of validator updates

### ISSUE THREAD

**Issue by mpoke** [cosmos/interchain-security#34]
In the context of CCV, we need to make the following changes on the **consumer chain**:
 - The staking `InitGenesis` does not return a list of validator updates (required due to this [line](https://github.com/cosmos/cosmos-sdk/blob/dd0d71272bbb9f49e256e8edc13531b8c5face28/types/module/module.go#L330)).
 - ~~If the `GenesisState` was exported (i.e., it contains a list with the powers of the last validator set), the staking `InitGenesis` must provide this list to the CCV `InitGenesis`. **_This enables a normal chain to become a consumer chain, thus it may not be needed for V1._**~~
 - ~~The CCV `InitGenesis` must implement the logic from the`ApplyAndReturnValidatorSetUpdates` method of the staking module (see [here](https://github.com/cosmos/cosmos-sdk/blob/master/x/staking/keeper/val_state_change.go#L112)) to create a list of validator updates (i.e., a diff between the last validator set, if any, and the new validator set from the ProviderConsensusState). This list of validator updates is returned to the consensus engine.~~

**Correction**:
- The CCV `InitGenesis` must **_return the entire set of initial validators_**, not just a diff. 
- The `ProviderConsensusState` contains **_only the hash_** of the initial validator set. Thus, the genesis state must contain the initial validator set. 
- In the case of **_a new consumer chain_**, the process that creates a governance proposal to add the chain as a consumer chain must anyway create a GenesisState for the consumer chain (it needs to add the hash to the proposal); since the GenesisState MUST contain a ConsensusState of the provider chain, it can easily also contain the validator set associated to that ConsensusState. 
- In the case of **_an already existing consumer chain_**, it's a bit more complicated (see https://github.com/cosmos/interchain-security/pull/30#discussion_r801839849)

**Comment by mpoke** [comment]
This issue is addressed by PR https://github.com/cosmos/interchain-security/pull/30

**Comment by mpoke** [comment]
The `ProviderConsensusState` contains only the hash of the initial validator set. Thus, the genesis state must contain the initial validator set.

**Comment by jtremback** [comment]
Good to close then?
