### ISSUE TITLE
No reference to consumer-chain-tool or wasmd  

### ISSUE THREAD

**Issue by mpoke** [cosmos/interchain-security#343]
There is no reference in README.md to https://github.com/informalsystems/consumer-chain-tool and https://github.com/informalsystems/wasmd.

**Comment by jtremback** [comment]
We are currently following the strategy of putting consumer chain teams directly in touch with @stana-ethernal and @dusan-ethernal to help them one on one. Making it easy to start a consumer by yourself is a whole documentation project and we should address it holistically when the time comes. Closing for now
