### ISSUE TITLE
No make test-all

### ISSUE THREAD

**Issue by mpoke** [cosmos/interchain-security#345]
Currently, the Makefile has only a `test` target, i.e., 
```
# run all unit and e2e tests using make
make test
```
that also includes the diff testing (which takes ~66s).

We should add another target, i.e., `make test-all`, that performs all the tests. This target will be useful before opening a PR. `make test` should be fast since it's used during dev.

**Comment by MSalopek** [comment]
@danwt 
I agree with the suggestions.

I would prefer to call it `make test-short` instead of `test-fast` since that's what I've been seeing in previous projects.

It's not necessarily a "faster" test, it simply runs a shorter list of tests.

**Comment by danwt** [comment]
Even better!
