### ISSUE TITLE
Fix protobuf make-gen dependency issue

### ISSUE THREAD

**Issue by danwt** [cosmos/interchain-security#347]
There is an issue currently when running `make proto-gen` from a fresh system (no pulled docker).

We should fix, or find a workaround and make a new issue.

We could try bumping this to 1.18

https://github.com/cosmos/interchain-security/blob/b47ae2a83c4b90d8e925de5e589e1f5141a064f5/scripts/protocgen.sh#L22

@MSalopek

**Comment by MSalopek** [comment]
Will try tidy for 1.18.

The PR where this is happening: https://github.com/cosmos/interchain-security/pull/332/files

**Comment by MSalopek** [comment]
I figured it out by checkecking what was done on cosmos/sdk.

We can update only `buf.build/googleapis/googleapis` and not touch other deps (which are fine).

The correct procedure (or so it seems) is:
```bash
$: cd proto
$: buf mod update --only buf.build/googleapis/googleapis
```

With this, the proto build works as expected and there are no unnecessary deps added.

Not sure if we need to do `buf push` though.

**Comment by danwt** [comment]
Nice! Good find.
