### ISSUE TITLE
Create issue template for this repo

### ISSUE THREAD

**Issue by danwt** [cosmos/interchain-security#349]
## Problem

Issues pile up and some issues don't have a clear closing criteria.

## Closing criteria

Define a GH [issue template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository) that prompts people to define a closing criteria for their issue.

I think admin rights are needed for this (@mpoke  or @jtremback )

**Comment by jtremback** [comment]
@danwt Do you have a good example of an issue template that you like?

**Comment by jtremback** [comment]
Done
