### ISSUE TITLE
Find out what data explorers will want to query from consumers (for first release).

### ISSUE THREAD

**Issue by danwt** [cosmos/interchain-security#353]
## Problem

Explorers may want to query data on the consumer chain that we do not have.

## Description

We might need to make more data available on the consumer (and possibly provider), for explorer and full node API UX.

Currently only ValidatorUpdates are shipped to the consumer

```
type ValidatorUpdate struct {
	PubKey crypto.PublicKey `protobuf:"bytes,1,opt,name=pub_key,json=pubKey,proto3" json:"pub_key"`
	Power  int64            `protobuf:"varint,2,opt,name=power,proto3" json:"power,omitempty"`
}
```

which does not tell you a whole lot.

Also, now, with key delegation

- https://github.com/cosmos/interchain-security/issues/26

the link between provider keys and consumer keys may become more complex. We probably don't want that to become too opaque. Please see [related comment](https://github.com/cosmos/interchain-security/issues/26#issuecomment-1240964050).

## Closing criteria

This issue should be closed when we have a clear idea of exactly what data is needed for good query/explorer experience.

**Comment by jtremback** [comment]
Closed in favor of https://github.com/cosmos/interchain-security/issues/356
