### ISSUE TITLE
CCV state observability (queries and events for block explorers and other frontends)

### ISSUE THREAD

**Issue by jtremback** [cosmos/interchain-security#356]
# Problem
No attention has been paid so far to making CCV's state easily observable by the cli, block explorers, and other types of interfaces and frontends.

NOTE: This issue is combining material from https://github.com/cosmos/interchain-security/issues/353, https://github.com/cosmos/interchain-security/issues/324, and https://github.com/cosmos/interchain-security/issues/279. I have integrated the discussion from these issues into this one.

There are two types of state observability I can think of right now.

1. Queries: These query the current state of the database.
2. Events: many things in CCV are pretty transient and don't leave a lot of state around. For example, slashing packets will result in a slashing but it won't be possible to figure out which consumer chain they came from after the fact. By logging an event we can allow users to index it and find out.

There are two directions to approach this from

1. Figure out which state it is easy to make observable. This is the low hanging fruit since it is mostly a matter of adding boilerplate. A good starting point for this is to look at the database state that we serialize for the genesis files. Also events can be pretty liberally sprinkled around. 

2. Figure out how to fix block explorers and other frontends which are broken by CCV. This is mostly relevant on the consumer chain, where we removed the staking module. For example, here is this weirdly broken block explorer, where somehow one of the validators has a moniker and the other doesn't: 
<img width="661" alt="image" src="https://user-images.githubusercontent.com/1335122/189240987-652838e9-a5e1-489e-b2b0-c7d7aa285a33.png">

For number 2, there is the additional question of how best to fix missing staking module stake, and whether we should ship non-essential information (i.e. validator monikers) in the VSCPackets to make consumer queries work better. Probably not, but I can maybe see the argument for it. If we don't, then we will have to accept that some frontends will need to make an additional query to the provider chain to work correctly.

# Subtasks

1. Come up with a list of easy to implement queries in the comments below. Lots of good material in [this PR](https://github.com/cosmos/interchain-security/pull/264/), which has to do with the genesis files which are similar, being another form of state serialization. @sainoe Let's talk about this angle together soon. I've already put together a list of easy queries in this [issue](https://github.com/cosmos/interchain-security/issues/324). I will put that list in the comments below to be added to it. Of course, then the queries will need to be implemented as well. @MSalopek has already started work on it.

2. Make a PR adding events. Since these are so easy to drop in, it's probably best to just do it and then discuss whether more or less are required afterwards in the code review.

3. Do some research about how various block explorers on the consumer are broken, and how they can be fixed. One of the testnet validators is going to send me some information about queries which are failing on their internal tools, and maybe the Hypha team can help look into how Big Dipper is broken.

# Closing criteria

This is a pretty big issue, but I wanted to bring everything together. It doesn't have crisp closing criteria, and I will make a judgement call about when to close it. Probably once we've gotten basic PRs in for subtasks 1 and 2, and done some research on 3, I will close this issue and make new ones summing up any remaining work.

**Comment by jtremback** [comment]
Here are some low hanging state queries

**Provider**
- Active consumer chains
- Pending consumer chain starts
- Pending consumer chain stops

**Consumer**
- get next dist block height
- pending distribution fee amounts -> total, provider, consumer
- dump current validator set

Later:
- @mpoke I think that it should be possible to enable a query on the provider where someone can tell the latest height is that unbonding operations have completed from. So, for example, if I started unbonding at block 10,003, I can see that someone who started unbonding at block 10,002 just had their unbonding complete, so I will be able to get my money out soon. Any thoughts?

**Comment by danwt** [comment]
I think any key delegation solution should ultimately store a mapping from consumer validator keys to the respective provider key _on the consumer as well as the provider_. This seems like something that will be wanted from UX right?
 
Alternatively, we store it only on the provider and thus people must query the provider to find out the relationship.

Any thoughts @sainoe @jtremback ?

**Comment by mpoke** [comment]
> I think that it should be possible to enable a query on the provider where someone can tell the latest height is that unbonding operations have completed from. So, for example, if I started unbonding at block 10,003, I can see that someone who started unbonding at block 10,002 just had their unbonding complete, so I will be able to get my money out soon. Any thoughts?


@jtremback see https://github.com/cosmos/interchain-security/issues/324#issuecomment-1239260312

**Comment by jtremback** [comment]
@dasanchez can you get more details on the query? Perhaps the exact url and body of the http request? All that the error message tells us is that staking is not there. We need the exact things that it is querying staking for

**Comment by dasanchez** [comment]
The block explorer is using the RPC and gPRC endpoints of our validator node:
- `http://consumer.stg.earthball.xyz:26657`
- `http://consumer.stg.earthball.xyz:9090`
I don't know what the actual http request is, but I'll see if I can dig it up.

**Comment by dasanchez** [comment]
@jtremback Also, it looks like the provider chain block explorer can't recognize the proposal for starting the 2nd consumer chain (not sure if that belongs in this issue).
http://ics-bigdipper.stg.earthball.xyz/proposals

**Comment by dasanchez** [comment]
Yet another detail:
The bdjuno backend for Big Dipper had trouble issues parsing the genesis file for the consumer chain, so we ended up using the provider genesis file for the consumer block explorer (that's why it says "provider" on the top right corner). It was looking for a `gov` section that was not there.

**Comment by dasanchez** [comment]
> @dasanchez can you get more details on the query? Perhaps the exact url and body of the http request? All that the error message tells us is that staking is not there. We need the exact things that it is querying staking for

We tracked it down, it's a gRPC query:
```
grpcurl -plaintext provider.stg.earthball.xyz:9090 cosmos.staking.v1beta1.Query/Validators
grpcurl -plaintext consumer.stg.earthball.xyz:9090 cosmos.staking.v1beta1.Query/Validators
```
The first command works, the second one doesn't.

**Comment by jtremback** [comment]
Thanks! Very helpful

**Comment by MSalopek** [comment]
> > @dasanchez can you get more details on the query? Perhaps the exact url and body of the http request? All that the error message tells us is that staking is not there. We need the exact things that it is querying staking for
> 
> We tracked it down, it's a gRPC query:
> 
> ```
> grpcurl -plaintext provider.stg.earthball.xyz:9090 cosmos.staking.v1beta1.Query/Validators
> grpcurl -plaintext consumer.stg.earthball.xyz:9090 cosmos.staking.v1beta1.Query/Validators
> ```
> 
> The first command works, the second one doesn't.

Consumers don't implement the staking module. The valset is the same as the one on the provider.

You can only get the tendermint validator set from the consumer, but that does not hold any validator metadata (moniker, contacts etc).

We could document how to combine data from provider and consumer to get a pretty validator set. Adding a separate query on our end would require us to keep validator metadata in state which is not optimal.

**Comment by jtremback** [comment]
I think we can close this for now. Good work @MSalopek !
