### ISSUE TITLE
`getUnderlyingClient` is used incorrectly 

### ISSUE THREAD

**Issue by mpoke** [cosmos/interchain-security#358]
# Problem

In the following line https://github.com/cosmos/interchain-security/blob/86beefe81dc1af7cc741dac4fe79dbc7b41a61ca/x/ccv/provider/keeper/keeper.go#L269 `chainId` is incorrect since the first return value of `getUnderlyingClient` is a client ID, see https://github.com/cosmos/interchain-security/blob/86beefe81dc1af7cc741dac4fe79dbc7b41a61ca/x/ccv/provider/keeper/keeper.go#L457

As a result, the check here https://github.com/cosmos/interchain-security/blob/86beefe81dc1af7cc741dac4fe79dbc7b41a61ca/x/ccv/provider/keeper/keeper.go#L275 will never fail, which means that the Unique CCV Channel property may be violated. 

# Closing criteria

Fix how `getUnderlyingClient` is used.

**Comment by smarshall-spitzbart** [comment]
Great catch, I'm gonna lump a fix for this into #342, since that PR will add unit tests for the provider's OnChanOpenConfirm (which calls the code you've referenced)

**Comment by smarshall-spitzbart** [comment]
In close location to the code you've referenced, I noticed a spec <-> implementation divergence.

In the event that a CCV channel for a consumer chain already exists, [we simply return an error](https://github.com/cosmos/interchain-security/blob/86beefe81dc1af7cc741dac4fe79dbc7b41a61ca/x/ccv/provider/keeper/keeper.go#L276), but the spec mentions that the CCV channel should be closed, see [here](https://github.com/cosmos/ibc/blob/main/spec/app/ics-028-cross-chain-validation/methods.md#ccv-pcf-coconfirm1). 

Is this a bug? I couldn't find a place in ibc core that the channel closing would be done automatically

**Comment by smarshall-spitzbart** [comment]
Nvm, found explanation here https://github.com/cosmos/interchain-security/pull/328
