### ISSUE TITLE
Swap names of 'integration' and 'e2e' tests

### ISSUE THREAD

**Issue by danwt** [cosmos/interchain-security#359]
# Problem

Currently our 'integration tests' are really more like e2e tests and our 'e2e tests' are really more like integration tests.

# Closing criteria

Swap the names of these two things

**Comment by jtremback** [comment]
Bikeshedding, and will confuse everyone for a while after the switch

**Comment by danwt** [comment]
🤷

**Comment by danwt** [comment]
I suggest we reopen this. It's confusing people! I've just spoken with @ivan-gavran and heard it!

I don't think it would take long to fix.

**Comment by mpoke** [comment]
Requirements:
- changing names
- informing users of testing framework
