### ISSUE TITLE
Small changes to be applied before V1 release

### ISSUE THREAD

**Issue by mpoke** [cosmos/interchain-security#36]
This issue keeps track of a list of relatively small changes that need to be applied to the code:

- [ ] Remove EmitEvent from CCV code, e.g., https://github.com/cosmos/interchain-security/blob/eccbfaae9cdc39a769d94814eece02a2eafe333f/x/ccv/child/module.go#L337

- [ ] Check counterparty port id during the channel handshake, i.e., https://github.com/cosmos/interchain-security/blob/eccbfaae9cdc39a769d94814eece02a2eafe333f/x/ccv/parent/module.go#L236 and https://github.com/cosmos/interchain-security/blob/eccbfaae9cdc39a769d94814eece02a2eafe333f/x/ccv/child/module.go#L221

- [ ] Remove hardcoded constants. For example: https://github.com/cosmos/interchain-security/blob/main/x/ccv/types/utils.go#L6

- [x] Implement one consistent scheme for key prefixes. Iota is probably best (see https://github.com/cosmos/interchain-security/issues/18)

- [x] Correct this bug and increment the ID in the proper place https://github.com/cosmos/interchain-security/blob/main/x/ccv/parent/keeper/relay.go#L113

- [ ] Delete the child genesis once the CCV channel for the chainID is OPEN since we no longer need to store it on parent chain.
- [ ] keeper.go and other large files could be broken up

**Comment by jtremback** [comment]
Thanks Marius, I've been procrastinating this, but I may set up a github board for this stuff because i have a bunch of these too

**Comment by mpoke** [comment]
Close as the tasks here were split in different issues: https://github.com/cosmos/interchain-security/issues/279, https://github.com/cosmos/interchain-security/issues/280, https://github.com/cosmos/interchain-security/issues/281, https://github.com/cosmos/interchain-security/issues/282
