### ISSUE TITLE
Document why pending consumer initiated slash requests are sent in reverse order to provider

### ISSUE THREAD

**Issue by danwt** [cosmos/interchain-security#368]
# Problem

Pending slash requests are sent in reverse order

https://github.com/cosmos/interchain-security/blob/d995b56976d4a650bbc690b9001a8614dc067240/x/ccv/consumer/keeper/relay.go#L167-L181

This is confusing because the reason is not documented.

# Closing criteria

Document the code so that the reader isn't confused.

**Comment by mpoke** [comment]
I agree, this is not clear. It is documented in the [spec](https://github.com/cosmos/ibc/blob/main/spec/app/ics-028-cross-chain-validation/methods.md#ccv-ccf-sndpeslash1) (see the Note), i.e.,
> Iterating over pending SlashRequests in reverse order ensures that validators that are down for multiple blocks during channel initialization will be slashed for the latest downtime evidence.


Basically we send a slash request for the most recent infraction height.

**Comment by mpoke** [comment]
No longer the case after https://github.com/cosmos/interchain-security/pull/448
