### ISSUE TITLE
Simplify how unbondings are matured.

### ISSUE THREAD

**Issue by danwt** [cosmos/interchain-security#369]
# Problem

I think we now have an overly complicated mechanism of completing unbondings when we receive maturities. Currently, the staking module has a refCnt for each operation, which we increment `once` from the provider module. Then we wait for all maturities from relevant consumers and then decrement `once` from the provider module.

I think this can be simplified to increment `k times` from the provider module - once for each relevant consumer. Then we simply decrement `once` per consumer maturity.

# Closing criteria

Make a simplification.

## Priority

I think this is an ultra low priority issue because everything already works (🖕 🪵 )

**Comment by mpoke** [comment]
> I think this can be simplified to increment k times from the provider module - once for each relevant consumer. Then we simply decrement once per consumer maturity.

@danwt why would this be simpler?

**Comment by danwt** [comment]
Right now we implement a ref count on top of a ref count but we don't need to. The one in the staking module is sufficient. I think making the change would give us a net reduction in LOC, and need less state. It would also be simpler to think about

https://github.com/cosmos/interchain-security/blob/e5f4ea5c00d571a024c2a0bd6903ac77d42dfb38/x/ccv/provider/keeper/relay.go#L50-L60

https://github.com/cosmos/interchain-security/blob/e5f4ea5c00d571a024c2a0bd6903ac77d42dfb38/x/ccv/provider/keeper/relay.go#L73-L86

https://github.com/cosmos/interchain-security/search?q=UnbondingConsumerChains


https://github.com/cosmos/interchain-security/blob/e5f4ea5c00d571a024c2a0bd6903ac77d42dfb38/x/ccv/provider/keeper/proposal.go#L158-L168

**Comment by mpoke** [comment]
> Currently, the staking module has a refCnt for each operation, which we increment once from the provider module. Then we wait for all maturities from relevant consumers and then decrement once from the provider module.

The reason we have this `refCnt` is because [staking.PutUnbondingOnHold](https://github.com/cosmos/cosmos-sdk/blob/59f3c3c3daa969cb730f18b086e8ced5af73109c/x/staking/keeper/unbonding.go#L359) could be called by any numbers of SDK modules (not only by the CCV module), i.e., 
```golang
// PutUnbondingOnHold allows an external module to stop an unbonding operation,
// such as an unbonding delegation, a redelegation, or a validator unbonding.
// In order for the unbonding operation with `id` to eventually complete, every call
// to PutUnbondingOnHold(id) must be matched by a call to UnbondingCanComplete(id).
```

> I think this can be simplified to increment k times from the provider module - once for each relevant consumer. Then we simply decrement once per consumer maturity.

How would you do that and keep the general functionality described above?

**Comment by danwt** [comment]
I don't understand your last comment. The refCnt in the staking module is sufficient to me, but we have an additional implicit ref cnt `if len(unbondingOp.UnbondingConsumerChains) == 0` in the provider module and I don'pt think we need it.

**Comment by mpoke** [comment]
How else are you checking on how many consumer chains the unbonding period already elapsed?

**Comment by mpoke** [comment]
Do you mean calling `PutUnbondingOnHold` once for every `VSCPacket` sent to a consumer chain and calling `UnbondingCanComplete` once for every `MaturedVSCPacket` received from a consumer chain? I don't see that a simplification. Just introduces another attack surface where a consumer chain could send two `MaturedVSCPacket` for the same `VSCPacket`.

**Comment by danwt** [comment]
My guesstimate is that it would result in a net loss of code and logic. I think it would be a simplification.

Well pointed out about the attack surface but I'm not sure it's reasonable to think that way. If we suppose duplicate maturations are possible we may as well also suppose the consumer will just tombstone every validator. Consider if binance did this for the 174 validators below it. They'd have control. If you really wanted you cover this, we could just store a map <chainId, greatestVSCIDMaturityReceived> on the provider and compute the equivalent of `.UnbondingConsumerChains` for a given unbondingOp from that. That would anyways be more space efficient than what we currently have.

**Comment by mpoke** [comment]
As you mention in the issue description, this is very low priority, we have other things to focus on now. Also, I'm not convinced by your arguments that it's worth the trouble to change code that is working. As a result, I'll drop this for now. I also suggest closing the issue for now.
