### ISSUE TITLE
Tidy up docs directory

### ISSUE THREAD

**Issue by danwt** [cosmos/interchain-security#377]
# Problem

People don't read docs/ directories because they are usually unorganized and out of date. It is hard to work on docs for the same reasons. Ours is unorganized and partially out of date. We should improve it.

# Closing criteria

Remove anything that is outdated or abandonded. Make sure things that are up to date and used are in sensible places.

# Concretely

We have e.g. https://github.com/cosmos/interchain-security/tree/main/docs/unbonding-hooks which is abandonware? We have https://github.com/cosmos/interchain-security/tree/main/docs/figures which dont' have a clear use. Ect.

**Comment by mpoke** [comment]
The figures are needed here https://github.com/cosmos/interchain-security/blob/main/docs/quality_assurance.md#interchain-security-workflow
