### ISSUE TITLE
Integration or e2e tests around custom params

### ISSUE THREAD

**Issue by shaspitz** [cosmos/interchain-security#387]
# Problem
Following (currently open) PRs to make hardcoded constants into params, there will be a decent amount of customizability around the params for provider/consumer chains. I see _some_ unit tests for this functionality, but I don't see a proper integration test which validates that these parameters are customizable from genesis, and can actually be set to non-default values. 

It seems from [here](https://github.com/cosmos/interchain-security/blob/main/x/ccv/provider/keeper/proposal.go#L207) that we currently give consumers default parameters (outside of what's specified in the `ConsumerAdditionProposal`), is this the functionality we want? 

What about provider parameters? Do we want an integration test with custom genesis parameters, which we then validate are correctly loaded into the provider binaries at runtime? 

# Closing criteria
Determine how much customizability there should be for providers and consumer params from genesis, and develop new integration tests if applicable.

**Comment by smarshall-spitzbart** [comment]
Related to this, we need to unit test valid and non valid cases for https://github.com/cosmos/interchain-security/blob/more-params/x/ccv/consumer/types/params.go#L78

**Comment by shaspitz** [comment]
This issue is no longer relevant, in that e2e tests would fail if we weren't able to set params to non-default values. See "genesis changes" in e2e test config
