### ISSUE TITLE
`ccvTimeoutTimestamp` should be included in consumer addition proposal

### ISSUE THREAD

**Issue by smarshall-spitzbart** [cosmos/interchain-security#388]
# Problem
This PR https://github.com/cosmos/interchain-security/pull/376 enables the provider and the consumers to have different CCV timeout periods. This could have negative implications on security, if a consumer chain is able to make this timeout parameter dangerously small. Note that a consumer could have changed this hardcoded parameter before #376 

We should better expose this parameter to provider validators when a consumer chain is being spawned, and perhaps include the parameter in the consumer addition proposal. We should also not allow this parameter to be changed through consumer governance. 

# Closing criteria
Fix the issues described above

**Comment by jtremback** [comment]
As we discussed today, this should probably just go in the regular consumer param section and defaults. The genesis.json for a new consumer needs to be checked carefully.
