### ISSUE TITLE
`GenesisState.Validate()` is outdated

### ISSUE THREAD

**Issue by mpoke** [cosmos/interchain-security#395]
# Problem

https://github.com/cosmos/interchain-security/pull/264 extended the `GenesisState` for both provider and consumer. These new fields are not validated in `GenesisState.Validate()`, neither on [consumer](https://github.com/cosmos/interchain-security/blob/2766b1c8e4276b4e29cf56c1e635b5807c191248/x/ccv/consumer/types/genesis.go#L58) nor on [provider](https://github.com/cosmos/interchain-security/blob/2766b1c8e4276b4e29cf56c1e635b5807c191248/x/ccv/provider/types/genesis.go#L40). 

# Closing criteria

All the field in `GenesisState` are properly validated.

**Comment by jtremback** [comment]
@sainoe is this done?

**Comment by sainoe** [comment]
Will close it when #525 is merged.
