### ISSUE TITLE
Relation between time related params is not clear

### ISSUE THREAD

**Issue by mpoke** [cosmos/interchain-security#396]
# Problem

At the moment ICS has the following time-related params:
- `providerUnbondingPeriod`
- `providerCCVTimeout`
- `consumerUnbondingPeriod`
- `consumerCCVTimeout`
- `consumerTransferTimeout`
- `BlocksPerDistributionTransmission`

Soon, https://github.com/cosmos/interchain-security/issues/278 and https://github.com/cosmos/interchain-security/issues/283, will introduce two more params on the provider side. 

# Closing criteria

Have a clear understanding on the relation between these params.

**Comment by mpoke** [comment]
Some inequalities:
- `providerCCVTimeout` > `consumerUnbondingPeriod`, otherwise the CCV channel will timeout
- `providerUnbondingPeriod` > `consumerUnbondingPeriod`, otherwise the user experience will be affected
- `consumerTransferTimeout` < `BlocksPerDistributionTransmission` * average block time, to make it easier to reason about the distribution subprotocol
- `consumerCCVTimeout` should be large enough to not close the CCV channel unnecessarily, e.g.,  `consumerCCVTimeout` ~ `providerCCVTimeout`

**Comment by jtremback** [comment]
Yea, this is a docs issue.

**Comment by jtremback** [comment]
We'll pull you in when we are preparing the first consumer's governance @mpoke and you can figure it all out. Closing for now.

**Comment by mpoke** [comment]
@jtremback I'd prefer to keep this one open for now. The relation between all these time params is still not clear to me.

**Comment by smarshall-spitzbart** [comment]
One more relation to consider. As we talked about in slack, the order of VSCMatured and Slash packets matter, to maintain the slashable consumer misbehavior system property. 

The worst case scenario (rough calculation) of how long a slash packet could be delayed once https://github.com/cosmos/ibc/pull/869 is implemented, is: `SlashMeterReplenishPeriod / SlashGasAllowance`. This max period should be considered when setting a timeout period for VSCMatured packets
