### ISSUE TITLE
Democracy consumer is not fully e2e tested

### ISSUE THREAD

**Issue by smarshall-spitzbart** [cosmos/interchain-security#397]
# Problem
The democracy consumer app does not run against the standard suite of e2e tests. Since this is an extension to the minimum functionality consumer, it should be ran against the same test cases as the minimum functionality consumer

# Closing criteria
Have all e2e tests run against normal consumer AND gov consumer. What about integration and diff?

**Comment by jtremback** [comment]
Will this be easily solved through the test portability work you are doing rn?

**Comment by smarshall-spitzbart** [comment]
This issue _should_ be easily solved by copying the pattern of `tests/e2e/instance_test.go` for both the democracy consumer and regular consumer. However when I run the democ consumer against the standard e2e tests I get this odd error coming from multiple tests
```
signature verification failed; please verify account number (0) and chain-id (testchain2): unauthorized
```

This might be related to https://github.com/cosmos/interchain-security/issues/151? (which still has a TODO comment in code)

@sainoe has the issue outlined in #151 produced similar errors in the past?

**Comment by sainoe** [comment]
Yes it looks like a similar issue. The democracy module creates more accounts than a MVCC. It probably changes the account numbers. You should check if this test setup is still correct.

https://github.com/cosmos/interchain-security/blob/9dda4b606a7a71e7f6426feb5603600b66790a05/tests/e2e/setup_test.go#L112-L115

Btw where is located `tests/e2e/instance_test.go` ?
