### ISSUE TITLE
Create PR template

### ISSUE THREAD

**Issue by danwt** [cosmos/interchain-security#398]
# Problem

We dont' have a PR template so we lose time by dealing with inconsistencies and missing information.

# Closing criteria

Create a useful PR template.

**Comment by danwt** [comment]
@MSalopek  I assigned you based on your enthusiasm here 

https://github.com/cosmos/interchain-security/issues/383#issuecomment-1277660637

Feel free to unassign yourself :)

**Comment by mpoke** [comment]
The PR template should contain the following task list for any changes that add/ modify state:

- proto files
- key.go and tests
- keeper.go and tests
- delete when stoping the consumer chain (if related)
- export and import genesis
- genesis validation
