### ISSUE TITLE
Test CCV packets timing out 

### ISSUE THREAD

**Issue by sainoe** [cosmos/interchain-security#400]
# Problem
The [OnTimeoutPacket](https://github.com/cosmos/interchain-security/blob/27e55b4f5cb2a087ce002d42dc8d99cf1154f0c5/x/ccv/provider/keeper/relay.go#L105) method doesn't have any tests yet.

# Closing criteria
Create  the e2e and unit tests to verify that a provider chain can graciously handle a CCV packet timing out (without shuting down).
# TODOs
- [x] Labels have been added for issue
- [ ] Issue has been added to the ICS project

**Comment by jtremback** [comment]
Closed in favor of #362
