### ISSUE TITLE
Root cause duplicate `sdkerrors.Register` firing due to ibc-go

### ISSUE THREAD

**Issue by danwt** [cosmos/interchain-security#403]
# Problem

I ran into a test failure while working on my keymap branch

- https://github.com/cosmos/interchain-security/tree/9a8441e9033c5515aee8e6a90ea767c87f14f06e

```
pwd
# /Users/danwt/Documents/work/interchain-security/x/ccv/provider/keeper
go test -fuzz FuzzKeyMapSerializationAndDeserialization -fuzztime 2m keymap_test.go
```

```
// ...
panic: error with code 2 is already registered: "invalid identifier"

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/types/errors.Register({0x10600cc5c, 0x4}, 0x2, {0x10601a285, 0x12})
	/Users/danwt/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.2-0.20220901181011-06d4a64bf808/types/errors/errors.go:163 +0x33c
github.com/cosmos/ibc-go/v3/modules/core/24-host.init()
	/Users/danwt/go/pkg/mod/github.com/informalsystems/ibc-go/v3@v3.0.0-beta1.0.20220816140824-aba9c2f2b943/modules/core/24-host/errors.go:12 +0x80
exit status 2
FAIL	command-line-arguments	1.153s
```

# Closing criteria

Fix or work around the issue

# TODOs
- [x] Labels have been added for issue
- [x] Issue has been added to the ICS project

**Comment by danwt** [comment]
It's referencing code here

https://github.com/informalsystems/ibc-go/blob/f442721c7ea7ce69a4aadaf24808b2b250d89628/modules/core/24-host/errors.go#L7-L12

```
//...
// SubModuleName defines the ICS 24 host
const SubModuleName = "host"


// IBC client sentinel errors
var (
	ErrInvalidID     = sdkerrors.Register(SubModuleName, 2, "invalid identifier")
	ErrInvalidPath   = sdkerrors.Register(SubModuleName, 3, "invalid path")
	ErrInvalidPacket = sdkerrors.Register(SubModuleName, 4, "invalid packet")
)
```

But I can't see where it's referenced a second time.

**Comment by smarshall-spitzbart** [comment]
I've solved this issue before by tracking down which two imported packages had conflicting errors registered, then I only used one of those two imports

**Comment by danwt** [comment]
Thanks I'll try to find the conflict. Was it easy to find in your case? I did a grep and didn't find it.

**Comment by smarshall-spitzbart** [comment]
I believe the pattern is to name these files `errors.go`, I found the conflict in my case from searching `errors.go` in vscode and looking through the various referenced source code

**Comment by danwt** [comment]
Regex: `sdkerrors.Register\((.+?),\s2`

**Comment by danwt** [comment]
I think it's some kind of diamond problem because the error is coming from this line firing twice

https://github.com/informalsystems/ibc-go/blob/f442721c7ea7ce69a4aadaf24808b2b250d89628/modules/core/24-host/errors.go#L12

Somehow maybe also the original ibc-go (not our fork) is also pulled and fires

https://github.com/cosmos/ibc-go/blob/54ec2f256581d3a1db8cb311af50bbbb45e8e060/modules/core/24-host/errors.go#L12

**Comment by smarshall-spitzbart** [comment]
Hmm yea I have noticed that different areas around our repo reference different versions (v1, v2 etc.) of the IBC package

**Comment by jtremback** [comment]
This seems like it was only relevant for the old key assignment code. Closing for now
