### ISSUE TITLE
Jailing circuit breaker

### ISSUE THREAD

**Issue by jtremback** [cosmos/interchain-security#404]
# Problem
I'd like to find a way to mitigate the worst-case scenario possible in ICS. This scenario is one where an attacker sneaks code into a consumer chain which is able to send many downtime or double signing packets at once. The attacker then creates 175 validators just below the Hub's active set, and slashes every real validator at once. These validators are then jailed, and control of the chain passes over to the attacker's 175 validators, enabling them to steal all tokens bridged to the Hub over IBC.

To mitigate this scenario, it would be good to put a circuit breaker into the slashing packet receiving code on the provider. This circuit break would make it impossible to jail more than x% (probably between 1-5% would be good) of the power on the provider per hour. This would make the provider takeover attack take around a day, allowing the remaining validators to be alerted and halt the chain.

The design of this feature is not too difficult but will require some thought. Here's a naive design:

- When a slashing packet comes in, add it to a queue
- Every hour, an endblocker process checks the queue
- If the first slash packet in the queue is for a validator with more than x%, take it off the queue and slash/jail the validator
- If the first slash packet in the queue is less than x%, take another one off the queue and slash the validator. Repeat until x% is reached.

I'm not sure if this is correct/optimal tbh

# Closing criteria

When this feature is implemented.

# TODOs
- [x] Labels have been added for issue
- [x] Issue has been added to the ICS project

**Comment by smarshall-spitzbart** [comment]
Nice writeup, two different solutions I'm thinking about are as follows:

- Limit the time it takes for a high volume of slash packets to actually affect validator voting power (throttling), this is what you've described above
- Alternatively, set a threshold for which a certain # of slash packets, or a certain amount of slashed voting %, triggers the provider chain to halt. Validators could then evaluate the situation, and take steps from there. Implementing proper recovery from the halt would likely be a lot of work, but maybe we don't implement that?

Just throwing out some ideas, your throttling mechanism or some variation of it seems like a reasonable way forward

**Comment by jtremback** [comment]
I'd like to avoid the possibility for malicious consumer code to halt the provider

**Comment by smarshall-spitzbart** [comment]
That was just an idea, it was not feasible. 

https://github.com/cosmos/ibc/pull/869 is implemented in such a way that the jailing always happens atomically, but a validator with a large % voting power would cause the slash meter to go negative, meaning no more slash packets will be handled until the meter is replenished to a positive value

**Comment by smarshall-spitzbart** [comment]
@danwt just brought up a great point that if we're talking about the scenario where many slash packets are being received by the provider in a short period of time, we should consider the potential size of the packet queue. 

Is there a param we could set s.t we start to drop slash packets when an unreasonable amount are being received by a certain chain? Unreasonable being defined as: it would infeasible to store all those packets on chain.

An alternative (besides halting the provider when too many packets come in), is to close the channel to consumers that are spamming slash packets

**Comment by alexanderbez** [comment]
Just posting this here for awareness, there is a plan and intent to have a more general circuit breaker built-in the SDK: https://github.com/cosmos/cosmos-sdk/issues/926
