### ISSUE TITLE
TrustingPeriodFraction should be a fraction

### ISSUE THREAD

**Issue by smarshall-spitzbart** [cosmos/interchain-security#408]
# Problem
#393 made this parameter an sdk "param". But it has always existed as an integer, acting as a denominator to calculate trusting periods. This param makes more sense as a fraction, but will require a way to encode a numerator and denominator into json on genesis. 

We could try using `ibctmtypes.Fraction` or two separate params for numerator and denominator

Related to this, the default for the new fraction should be 2/3 per https://github.com/cosmos/ibc-go/blob/main/docs/architecture/adr-026-ibc-client-recovery-mechanisms.md, i.e.,

> we recommend that the trusting period for the 07-tendermint client be set to 2/3 of the UnbondingPeriod.

# Closing criteria
 Make this param a fraction, be able to encode that fraction in json, set new recommended default

# TODOs
- [x] Labels have been added for issue
- [x] Issue has been added to the ICS project

**Comment by mpoke** [comment]
Alternatively, we can use the same approach as for `ConsumerRedistributionFrac`.

**Comment by smarshall-spitzbart** [comment]
> Alternatively, we can use the same approach as for `ConsumerRedistributionFrac`.

Ah yes, this seems best 👍

**Comment by danwt** [comment]
I would suggest a 'scalar' or 'multiplier' in [0,1] or whatever appropriate interval.

**Comment by jtremback** [comment]
Yea, `ConsumerRedistributionFrac` is a stringified decimal eg "0.75"
