### ISSUE TITLE
Research ways in which consumer chain governance can mess with the provider chain

### ISSUE THREAD

**Issue by jtremback** [cosmos/interchain-security#41]
- There are things that consumer chain governance can do to mess up the provider chain’s consensus. For example, they can set the unbonding period to a very long time, which will make it so that nobody on the provider chain can unbond. We should look into making sure that no such dangerous value is possible to be modified by consumer governance.

- There may be dangerous parameters other than the unbonding period
    - slashingKeeper.DowntimeJailDuration()

**Comment by danwt** [comment]
Related: do we oblige consumer chains to have the same unbonding period as the provider from genesis?

**Comment by mpoke** [comment]
> Related: do we oblige consumer chains to have the same unbonding period as the provider from genesis?

This is related to this issue https://github.com/cosmos/ibc/issues/673

**Comment by jtremback** [comment]
I think we can table this for now. Our reference implementation will be the CosmWasm consumer chain, and it will not have parameter governance at first.

For custom consumer chains that can modify the parameters with governance, this should be dealt with on a case by case basis. They will not be approved by Cosmos Hub governance if they are potentially harmful.
