### ISSUE TITLE
Diff test setup seems incorrect

### ISSUE THREAD

**Issue by smarshall-spitzbart** [cosmos/interchain-security#411]
# Problem
In places such as [CreateConsumerClient](https://github.com/cosmos/interchain-security/blob/consumer-unbonding-param/x/ccv/provider/keeper/proposal.go#L65), the IBC `ClientState.UnbondingPeriod` is set to the unbonding period of the counterparty chain, not the native unbonding period.

In [diff tests](https://github.com/cosmos/interchain-security/blob/consumer-unbonding-param/tests/difference/core/driver/setup.go#L522), the client state unbonding period for the provider is set to the unbonding period for the provider. 

One of two places is incorrect, and judging by the TODO in the diff test code, there might be a deeper issue with how unbonding periods are configured.

I'm running into such issues while developing #410, so it may be useful to fix diff tests separately from that PR

# Closing criteria
Fix discrepancy between diff tests and other uses of client state unbonding period

# TODOs
- [x] Labels have been added for issue
- [x] Issue has been added to the ICS project

**Comment by danwt** [comment]
Thanks, this should be addressed by https://github.com/cosmos/interchain-security/pull/412
