### ISSUE TITLE
Fix early returning iterator

### ISSUE THREAD

**Issue by danwt** [cosmos/interchain-security#433]
# Problem

https://github.com/cosmos/interchain-security/blob/c8a762c7b4c19d9b127abc9529395d2b3cff269d/x/ccv/provider/keeper/relay.go#L356-L357

I think it should return false, rather than true.

https://github.com/cosmos/interchain-security/blob/c8a762c7b4c19d9b127abc9529395d2b3cff269d/x/ccv/provider/keeper/keeper.go#L200-L202

# Closing criteria

Fix the iteration if necessary, _and add a regression test_

# TODOs
- [x] Labels have been added for issue
- [x] Issue has been added to the ICS project

**Comment by mpoke** [comment]
Nice catch @danwt. IMO the fix entails changing the if condition to 
```golang
if !cb(ctx, channelID, chainID)
```
in order to be consistent with the other iterators.

**Comment by mpoke** [comment]
Could be worthwhile to also create a UT for `EndBlockCCR` to catch these types of errors. The e2e tests have only one consumer chain.
