### ISSUE TITLE
Root cause strange duplicate calls to CreateConsumerClient in integration tests

### ISSUE THREAD

**Issue by danwt** [cosmos/interchain-security#438]
# Problem

In my working branch at 776402c8e256300d3a9e1b27a71b6fcd235f297a I have noticed that calls to CreateConsumerClient and `HandleConsumerAdditionProposal` are firing multiple times during the integration test (happyPath). I would bet this is happening on main too but I haven't checked.

Integration test log https://pastebin.com/raw/Q4Zcx5jr
validator alice log (relevant parts only ) https://pastebin.com/raw/nQdnWyKq

# Closing criteria

Do root cause analysis and fix the issue if there is one. It could be a false positive.

# TODOs
- [x] Labels have been added for issue
- [ ] Issue has been added to the ICS project

**Comment by danwt** [comment]
Note:

The HandleSpawnProposal is used as a handler both when the proposal is _submitted_ to the gov module, _and_ when the proposal passes. (The first time, there is no state change committed to store).

**Comment by danwt** [comment]
cc @MSalopek for interest

**Comment by mpoke** [comment]
@danwt is this issue still relevant?

**Comment by danwt** [comment]
Let's close it for now and see if it crops up again, the way proposals are processed has changed a lot since opening.
