### ISSUE TITLE
Remove unused function `IterateSlashAcks`

### ISSUE THREAD

**Issue by danwt** [cosmos/interchain-security#445]
# Problem

https://github.com/cosmos/interchain-security/blob/6c0d718d8c59339d112feb5850589258a504756e/x/ccv/provider/keeper/keeper.go#L627-L646

Is only used in a test.

# Closing criteria

Delete the function and relevant parts of test code.

# TODOs
- [x] Labels have been added for issue
- [x] Issue has been added to the ICS project

**Comment by smarshall-spitzbart** [comment]
There's at least a few more keeper methods that're only used in tests, and a lot of them have been merged recently or are in open PRs. I don't think this is a problem imo as the additional exposed state often allows for better tests. I'm all for marking the methods with a comment stating they are only used in tests

**Comment by danwt** [comment]
It seems like a slight anti pattern, especially since these iterators ect are quite a few lines. Nevertheless it's not our most pressing issue right now. Let's keep using them and for our next project we can think if we could do things differently and not have the need for them in the first place 🤷
