### ISSUE TITLE
Document iteration in `ConsumerAdditionPropsToExecute`

### ISSUE THREAD

**Issue by danwt** [cosmos/interchain-security#446]
# Problem

The function uses iterators with callbacks

https://github.com/cosmos/interchain-security/blob/6c0d718d8c59339d112feb5850589258a504756e/x/ccv/provider/keeper/proposal.go#L329-L334

and it's a bit unclear whether or not it is written as intended because of the `return true` and `return false`. I suspect it's correct because the proposals are ordered timestamp ascending. If that's true it would be good to have a comment there.

# Closing criteria

Add comments to the code to make the iteration pattern clearer.

# TODOs
- [x] Labels have been added for issue
- [x] Issue has been added to the ICS project

**Comment by danwt** [comment]
See 

- https://github.com/cosmos/interchain-security/issues/513

for a possible related issue.

**Comment by smarshall-spitzbart** [comment]
Closed in #459 by adding comments
