### ISSUE TITLE
Improve the diagnosis info spat out by the integration tests

### ISSUE THREAD

**Issue by danwt** [cosmos/interchain-security#450]
# Problem

The information that the integration tests dumps when a test fails isn't sufficient to easily diagnose the problem.

# Closing criteria

Improve the diagnosis info that is output

# TODOs
- [x] Labels have been added for issue
- [x] Issue has been added to the ICS project 

# Detail

We have 

https://github.com/cosmos/interchain-security/blob/d9a002ff8845a660e437d087c9bac1c6a0779589/tests/integration/main.go#L109-L115

which is great, however, it would be better to also have the following

1. Display which action number/index occurred
2. Display which test group the action belongs to
3. Consolidate the use of println, log, pretty print to make sure everything is flushed on fail, and to the correct stdout/stderr pipes. IMO maybe it can all go in stdout. What I want is to easily be able to `tee` the running integration tests and get all the information, but currently something is lost when `tee`ing.

**Comment by danwt** [comment]
@MSalopek if you are still working on the integration tests and are interested then I think making this enhancement would be very useful.

**Comment by MSalopek** [comment]
I would prefer outputting all logs to file and simply tailing a file if you want to see what's happening.

There can be one file per test run.

**Comment by danwt** [comment]
As a bonus I'd add

- For each `cmd` that is executed, output the stringified version verbatim, this can help see what's going on.

**Comment by MSalopek** [comment]
> As a bonus I'd add
> 
> * For each `cmd` that is executed, output the stringified version verbatim, this can help see what's going on.

You get that with `--verbose` flag already

**Comment by danwt** [comment]
Somewhat improved by 

- https://github.com/cosmos/interchain-security/commit/fb83bb7dbeef3532ef779adeb63b58b547189f21#diff-53099983e732ac07494be0904760fe652c4480a8d95146d46387807999e27ed5

good enough for now.
