### ISSUE TITLE
Provider genesis state validation 

### ISSUE THREAD

**Issue by mpoke** [cosmos/interchain-security#46]
The validation of a child state (within a provider chain genesis state) validates the chain ID as a client ID, see https://github.com/cosmos/interchain-security/blob/c4ce132b75087818873e769a828ccb4db36df74e/x/ccv/parent/types/genesis.go#L34

**Comment by jtremback** [comment]
Could use some more context on this one

**Comment by mpoke** [comment]
It's a minor thing. I would expect `ClientIdentifierValidator` should be used for validating client IDs and not chain IDs.
