### ISSUE TITLE
Usage of JSON for storing Provider VSC updates in Cosmos SDK store

### ISSUE THREAD

**Issue by andrey-kuprianov** [cosmos/interchain-security#481]
_Surfaced from @informalsystems audit of [Interchain Security](https://github.com/cosmos/interchain-security/) at commit dc19c57_

# Problem

In [ccv/provider/keeper/keeper.go](https://github.com/cosmos/interchain-security/blob/dc19c57f71fb1adb38a5b73db0bdd3a95d99f713/x/ccv/provider/keeper/keeper.go), JSON is used to encode pending VSC changes in function [AppendPendingVSC()](https://github.com/cosmos/interchain-security/blob/dc19c57f71fb1adb38a5b73db0bdd3a95d99f713/x/ccv/provider/keeper/keeper.go#L699-L721):

# Closing criteria

Use protobuf to serialize/deserialize VSC packets

# TODOs
- [x] Labels have been added for issue
- [x] Issue has been added to the ICS project 

# Detail

```go
// AppendPendingVSC adds the given ValidatorSetChange packet to the list
// of pending ValidatorSetChange packets stored under chain ID
func (k Keeper) AppendPendingVSC(ctx sdk.Context, chainID string, packet ccv.ValidatorSetChangePacketData) {
	packets, _ := k.GetPendingVSCs(ctx, chainID)
	// append works also on a nil list
	packets = append(packets, packet)

	store := ctx.KVStore(k.storeKey)
	var data [][]byte
	for _, p := range packets {
		pdata, err := p.Marshal()
		if err != nil {
			panic("failed to marshal ValidatorSetChange packet data")
		}
		data = append(data, pdata)
	}
	buf := &bytes.Buffer{}
	err := json.NewEncoder(buf).Encode(data)
	if err != nil {
		panic("failed to encode json")
	}
	store.Set(types.PendingVSCsKey(chainID), buf.Bytes())
}
```

Pending VSCs are accordingly decoded from JSON in function [GetPendingVSCs()](https://github.com/cosmos/interchain-security/blob/dc19c57f71fb1adb38a5b73db0bdd3a95d99f713/x/ccv/provider/keeper/keeper.go#L673-L697), each time a pending VSC needs to be appended (while the CCV channel is not yet established), or consumed (once it's established).

Usage of JSON (a textual format) to encode/decode binary data for storage in Cosmos SDK store is unjustified, inefficient, and may lead to subtle encoding/decoding bugs, and, subsequently, to panics in the EndBlocker. We recommend to replace JSON encoding/decoding with the standard Cosmos SDK store-by-key and retrieve-by-iterator operations, using `ValsetUpdateId` as the key.

**Comment by danwt** [comment]
Thank you, protobuf should probably be used, indeed.

**Comment by jtremback** [comment]
IMO, alphabetized JSON is a completely valid and deterministic format, and thousands of hours of work could have been saved if Cosmos had settled on this standard years ago. But yes, we should be consistent.
