### ISSUE TITLE
Check if any of the cryptographicIdentity util methods are equivalent

### ISSUE THREAD

**Issue by danwt** [cosmos/interchain-security#486]
# Problem

When writing any code involving keys or addresses it is hard to know the exact meanings of each type required in a method signature. The cryptographic utilities implement helpers to get those types. Some of those types _may refer to the same thing_. 

# Closing criteria

Check if any of the return values from the crypto identity methods are equivalent, and if they are, document them as such

https://github.com/cosmos/interchain-security/blob/main/testutil/crypto/crypto.go

# TODOs
- [x] Labels have been added for issue
- [x] Issue has been added to the ICS project

**Comment by smarshall-spitzbart** [comment]
My hunch is that some of the utils do return equivalents. At least, I was able to use multiple different types of addresses when making a first pass at #473. The new util file is still a huuuuge improvement from before 🙏

**Comment by smarshall-spitzbart** [comment]
Note that https://github.com/cosmos/interchain-security/pull/473 was closed because it got too behind. A future PR could use that PR as inspiration but use the utils correctly, maybe fix this issue in the same PR

**Comment by danwt** [comment]
Note, this issue is related to https://github.com/cosmos/interchain-security/issues/572

**Comment by mpoke** [comment]
@danwt does https://github.com/cosmos/interchain-security/pull/672 address this issue?

**Comment by danwt** [comment]
Will be superseded by pending solution to https://github.com/cosmos/interchain-security/issues/572
