### ISSUE TITLE
Delete or use consumer addition proposal GenesisHash and BinaryHash fields

### ISSUE THREAD

**Issue by danwt** [cosmos/interchain-security#487]
# Problem

These fields seem to be unused

https://github.com/cosmos/interchain-security/blob/fb83bb7dbeef3532ef779adeb63b58b547189f21/x/ccv/provider/types/provider.pb.go#L48-L50

# Closing criteria

~~Remove the fields or use them~~
EDIT: Add comment explaining the purpose of these fields, see https://github.com/cosmos/interchain-security/issues/487#issuecomment-1321789297

# TODOs
- [x] Labels have been added for issue
- [x] Issue has been added to the ICS project

**Comment by sainoe** [comment]
These fields are meant to be used off-chain to validate consumer chain proposals against their associated binary and genesis file.

**Comment by mpoke** [comment]
We should add a comment explaining that better.
