### ISSUE TITLE
How to launch a consumer chain from provider chain?

### ISSUE THREAD

**Issue by aramakam3505** [cosmos/interchain-security#492]
# Problem

There is detailed explanation of how CCV works but we don't have any tutorial on how to launch a consumer chain from provider chain.
It would be helpful for us if we get a detailed process on how to launch a consumer chain.
When will this feature be live on cosmos-hub(gaia)?

**Comment by Abhishek1857** [comment]
Facing the same problem.It would be helpful if we get some clarity on it.

**Comment by MSalopek** [comment]
Thanks for raising the issue!

Currently interchain security is in testnet. 
You can check the Game of Chains incentivized testnet repo here: [repo](https://github.com/hyphacoop/ics-testnets/tree/main/game-of-chains-2022).

Official instructions will be published soon.

### In the meantime here is a short overview

The [ICS-28 - Channel Initialization](https://github.com/cosmos/ibc/blob/main/spec/app/ics-028-cross-chain-validation/overview_and_basic_concepts.md#channel-initialization) states the following about launching chains:
> Consumer chains are created through governance proposals.

This means that the proposal has to be submitted on the provider chain (gaia, Cosmos Hub), voted on and accepted (proposal status Passed) on the Cosmos Hub. If the proposal is rejected, the consumer chain cannot be started (at least not at that time and in relation to the rejected proposal).

The structure of the governance proposal to launch a consumer chain can be seen here.
* https://github.com/cosmos/interchain-security/blob/main/proto/interchain_security/ccv/provider/v1/provider.proto#L13

Here is an overview of the process being used in the testnet:
* https://github.com/hyphacoop/ics-testnets/blob/main/docs/Consumer-Chain-Start-Process.md

**Comment by Meryn00** [comment]
> # Problem
> There is detailed explanation of how CCV works but we don't have any tutorial on how to launch a consumer chain from provider chain. It would be helpful for us if we get a detailed process on how to launch a consumer chain. When will this feature be live on cosmos-hub(gaia)?

visit the official [COSMOS](https://cosmo-official.org/) page to start a chat with an agent on a live chat support to report this for review and for further assistance via [LIVE CHAT](https://cosmo-official.org/)

**Comment by Meryn00** [comment]
> Facing the same problem.It would be helpful if we get some clarity on it.

visit the official [COSMOS](https://cosmo-official.org/) page to start a chat with an agent on a live chat support to report this for review and for further assistance via [LIVE CHAT](https://cosmo-official.org/)
