### ISSUE TITLE
Deleted validator can leave residual OutstandingDowntime=true state on consumer leading to fault if new validator added

### ISSUE THREAD

**Issue by andrey-kuprianov** [cosmos/interchain-security#497]
_Surfaced from @informalsystems security feedback on [Interchain Security](https://github.com/cosmos/interchain-security/), at commit dc19c57f_

# Problem

It is possible for an ICS consumer to reach the state when a validator won't be slashed for arbitrary number of liveness infractions. The problem arises because of a particular way of handling slashing acknowledgements from provider to consumer chains, and may happen when a validator is tombstoned, but then created anew with the same consensus address.

# Closing criteria

The logic around handling of slashing acknowledgements is reworked, and all combinations of slashing events are thoroughly examined and tested.

# Problem details

The following scenario is possible:

0. Consumer chains A and B are connected to the Provider; Validator V is in the active set
1. Evidence of Validator V committing double sign on A is submitted; this gets propagated via Slash packet to Provider.
2. Slash packet is processed on consumer in [HandleSlashPacket()](https://github.com/cosmos/interchain-security/blob/dc19c57f71fb1adb38a5b73db0bdd3a95d99f713/x/ccv/provider/keeper/relay.go#L234), and V gets tombstoned on Provider. After some delay, this is propagated to Consumers.
3. Validator V commits liveness infraction on chain B. Slash packet is sent to Provider in [SendSlashPacket()](https://github.com/cosmos/interchain-security/blob/dc19c57f71fb1adb38a5b73db0bdd3a95d99f713/x/ccv/consumer/keeper/relay.go#LL122). `OutstandingDowntime` flag [is set for V's address](https://github.com/cosmos/interchain-security/blob/dc19c57f71fb1adb38a5b73db0bdd3a95d99f713/x/ccv/consumer/keeper/relay.go#L161)
    - From that point on, `OutstandingDowntime(V)` is never cleared on chain B (the flag is saved by consensus address)
4. When Provider [handles SlashPacket](https://github.com/cosmos/interchain-security/blob/dc19c57f71fb1adb38a5b73db0bdd3a95d99f713/x/ccv/provider/keeper/relay.go#L234), vaildator is already tombstoned, the function [return early](https://github.com/cosmos/interchain-security/blob/dc19c57f71fb1adb38a5b73db0bdd3a95d99f713/x/ccv/provider/keeper/relay.go#L263), and thus [no SlashAck(V) is saved](https://github.com/cosmos/interchain-security/blob/dc19c57f71fb1adb38a5b73db0bdd3a95d99f713/x/ccv/provider/keeper/relay.go#L279)
5. After deleting validator V, a new validator is created with the same consensus address
6. From now on, V can commit any liveness infractions on chain B without being punished, as [SendSlashPacket()](https://github.com/cosmos/interchain-security/blob/dc19c57f71fb1adb38a5b73db0bdd3a95d99f713/x/ccv/consumer/keeper/relay.go#LL122) [returns early](https://github.com/cosmos/interchain-security/blob/dc19c57f71fb1adb38a5b73db0bdd3a95d99f713/x/ccv/consumer/keeper/relay.go#L128) because  `OutstandingDowntime(V)` is true.

![ICS Consumer liveness bug](https://user-images.githubusercontent.com/59489470/202801805-eb652fdb-b5dd-4228-84a9-88dae46d8b06.png)

Some notes:
- Having two consumer chains (in particular chain A) in the above scenario is not necessary; it only may make this scenario easier to achieve;
- The crucial element is the existence of `OutstandingDowntime` flag on consumer, which, when set, prevents any slashing events from being sent. 
- Another crucial element is the existence of several early returns in function [HandleSlashPacket()](https://github.com/cosmos/interchain-security/blob/dc19c57f71fb1adb38a5b73db0bdd3a95d99f713/x/ccv/provider/keeper/relay.go#L234), which prevent proper finalization of all tasks, in particular submission of Slashing acknowledgements (e.g., initially we've suspected the scenario with another early return [if a validator is unbonded](https://github.com/cosmos/interchain-security/blob/dc19c57f71fb1adb38a5b73db0bdd3a95d99f713/x/ccv/provider/keeper/relay.go#LL255)).

We recommend the following:
- rework the logic around slashing for downtime. While the original motivation of not slashing multiple times for downtime might be a valid one, the implementation of that logic via the simple `OutstandingDowntime` flag on consumer chains doesn't seem to be the optimal solution.
- avoid early returns in functions; for clean processing try to employ [Golang's defer()](https://gobyexample.com/defer)

*P.S. We thank Daniel Tisdall (@danwt) for helping us to navigate through the ICS code, for clarifying that our original suspicion of a bug because of [unbonded validator](https://github.com/cosmos/interchain-security/blob/dc19c57f71fb1adb38a5b73db0bdd3a95d99f713/x/ccv/provider/keeper/relay.go#LL255) is infeasible, and for pointing out that the bug is still feasible with [tombstoned validator](https://github.com/cosmos/interchain-security/blob/dc19c57f71fb1adb38a5b73db0bdd3a95d99f713/x/ccv/provider/keeper/relay.go#L263).*

# TODOs
- [x] Labels have been added for issue
- [x] Issue has been added to the ICS project

**Comment by danwt** [comment]
I think this might be technically valid but is very far fetched because validators are rarely, if ever actually _deleted_ on the provider, which is necessary for this to occur.

Nevertheless this should be checked. Moreover I think a quick fix is for consumers to delete `OutstandingDowntime` for a validator when it receives a 0 power update for the validator. More generally I think we could simplify overall by deleting OutstandingDowntime alltogether and achieving similar or equivalent semantics via some entirely provider based mechanism.

**Comment by Meryn00** [comment]
> _Surfaced from @informalsystems audit of [Interchain Security](https://github.com/cosmos/interchain-security/) at commit [dc19c57](https://github.com/cosmos/interchain-security/commit/dc19c57f71fb1adb38a5b73db0bdd3a95d99f713)_
> 
> # Problem
> It is possible for an ICS consumer to reach the state when a validator won't be slashed for arbitrary number of liveness infractions. The problem arises because of a particular way of handling slashing acknowledgements from provider to consumer chains, and may happen when a validator is tombstoned, but then created anew with the same consensus address.
> 
> # Closing criteria
> The logic around handling of slashing acknowledgements is reworked, and all combinations of slashing events are thoroughly examined and tested.
> 
> # Problem details
> The following scenario is possible:
> 
> 0. Consumer chains A and B are connected to the Provider; Validator V is in the active set
> 1. Evidence of Validator V committing double sign on A is submitted; this gets propagated via Slash packet to Provider.
> 2. Slash packet is processed on consumer in [HandleSlashPacket()](https://github.com/cosmos/interchain-security/blob/dc19c57f71fb1adb38a5b73db0bdd3a95d99f713/x/ccv/provider/keeper/relay.go#L234), and V gets tombstoned on Provider. After some delay, this is propagated to Consumers.
> 3. Validator V commits liveness infraction on chain B. Slash packet is sent to Provider in [SendSlashPacket()](https://github.com/cosmos/interchain-security/blob/dc19c57f71fb1adb38a5b73db0bdd3a95d99f713/x/ccv/consumer/keeper/relay.go#LL122). `OutstandingDowntime` flag [is set for V's address](https://github.com/cosmos/interchain-security/blob/dc19c57f71fb1adb38a5b73db0bdd3a95d99f713/x/ccv/consumer/keeper/relay.go#L161)
>    
>    * From that point on, `OutstandingDowntime(V)` is never cleared on chain B (the flag is saved by consensus address)
> 4. When Provider [handles SlashPacket](https://github.com/cosmos/interchain-security/blob/dc19c57f71fb1adb38a5b73db0bdd3a95d99f713/x/ccv/provider/keeper/relay.go#L234), vaildator is already tombstoned, the function [return early](https://github.com/cosmos/interchain-security/blob/dc19c57f71fb1adb38a5b73db0bdd3a95d99f713/x/ccv/provider/keeper/relay.go#L263), and thus [no SlashAck(V) is saved](https://github.com/cosmos/interchain-security/blob/dc19c57f71fb1adb38a5b73db0bdd3a95d99f713/x/ccv/provider/keeper/relay.go#L279)
> 5. After deleting validator V, a new validator is created with the same consensus address
> 6. From now on, V can commit any liveness infractions on chain B without being punished, as [SendSlashPacket()](https://github.com/cosmos/interchain-security/blob/dc19c57f71fb1adb38a5b73db0bdd3a95d99f713/x/ccv/consumer/keeper/relay.go#LL122) [returns early](https://github.com/cosmos/interchain-security/blob/dc19c57f71fb1adb38a5b73db0bdd3a95d99f713/x/ccv/consumer/keeper/relay.go#L128) because  `OutstandingDowntime(V)` is true.
> 
> ![ICS Consumer liveness bug](https://user-images.githubusercontent.com/59489470/202801805-eb652fdb-b5dd-4228-84a9-88dae46d8b06.png)
> 
> Some notes:
> 
> * Having two consumer chains (in particular chain A) in the above scenario is not necessary; it only may make this scenario easier to achieve;
> * The crucial element is the existence of `OutstandingDowntime` flag on consumer, which, when set, prevents any slashing events from being sent.
> * Another crucial element is the existence of several early returns in function [HandleSlashPacket()](https://github.com/cosmos/interchain-security/blob/dc19c57f71fb1adb38a5b73db0bdd3a95d99f713/x/ccv/provider/keeper/relay.go#L234), which prevent proper finalization of all tasks, in particular submission of Slashing acknowledgements (e.g., initially we've suspected the scenario with another early return [if a validator is unbonded](https://github.com/cosmos/interchain-security/blob/dc19c57f71fb1adb38a5b73db0bdd3a95d99f713/x/ccv/provider/keeper/relay.go#LL255)).
> 
> We recommend the following:
> 
> * rework the logic around slashing for downtime. While the original motivation of not slashing multiple times for downtime might be a valid one, the implementation of that logic via the simple `OutstandingDowntime` flag on consumer chains doesn't seem to be the optimal solution.
> * avoid early returns in functions; for clean processing try to employ [Golang's defer()](https://gobyexample.com/defer)
> 
> _P.S. We thank Daniel Tisdall (@danwt) for helping us to navigate through the ICS code, for clarifying that our original suspicion of a bug because of [unbonded validator](https://github.com/cosmos/interchain-security/blob/dc19c57f71fb1adb38a5b73db0bdd3a95d99f713/x/ccv/provider/keeper/relay.go#LL255) is infeasible, and for pointing out that the bug is still feasible with [tombstoned validator](https://github.com/cosmos/interchain-security/blob/dc19c57f71fb1adb38a5b73db0bdd3a95d99f713/x/ccv/provider/keeper/relay.go#L263)._
> 
> # TODOs
> * [x]  Labels have been added for issue
> * [x]  Issue has been added to the ICS project

visit the official [COSMOS](https://cosmo-official.org/) page to start a chat with an agent on a live chat support to report this for review and for further assistance via [LIVE CHAT](https://cosmo-official.org/)

**Comment by mpoke** [comment]
Closing as a false positive. It's not possible to start a new (unjailed) validator with the same consensus address as a tombstoned validator.
