### ISSUE TITLE
Upgrade IBC go to v3.4.0

### ISSUE THREAD

**Issue by smarshall-spitzbart** [cosmos/interchain-security#498]
# Problem

We're currently using a v3 beta version of IBC go in this repo. v3.4.0 is a more up to date version with changes to the testing package that will prevent e2e testing bugs. Note that the current version of ibc go we reference is causing #493 

# Closing criteria

Upgrade to v3.4 and implement any neccessary refactors therein. 

# Problem details

See #493 

https://github.com/cosmos/ibc-go/releases/tag/v3.4.0

# TODOs
- [x] Labels have been added for issue
- [x] Issue has been added to the ICS project

**Comment by danwt** [comment]
Interesting! I'd definitely be happy to upgrade. I'm curious, what are the bugs that are fixed in 3.4?

Btw, just for reference, we have several of our own commits on our fork head, some of which might want to be rebased

https://github.com/informalsystems/ibc-go/commits/interchain-security-2

**Comment by danwt** [comment]
cc @sainoe @glnro

**Comment by smarshall-spitzbart** [comment]
Note, to fix the problems I was facing when this issue was made, I just added commits to our IBC 3.0 fork. I didn't get very far on upgrading to 3.4. Happy to help as needed tho!

**Comment by sainoe** [comment]
Solved in https://github.com/cosmos/interchain-security/pull/559
