### ISSUE TITLE
KeyAssignment - must prevent validator creation using existing consumer key

### ISSUE THREAD

**Issue by danwt** [cosmos/interchain-security#503]
# Problem

Consider a provider validator set consisting of validator V0 with provider key A and assigned consumer key B. We must prevent a new validator V1 being created with provider key B.

# Closing criteria

Prevent the scenario by placing appropriate checks in e.g. staking module.

# Problem details

The described scenario will lead to a fault, assuming that validator V1 does not assign a consumer key C with C!=B, because if V1 does not expliclity assign a key then a default value B will be chosen. This will lead to two validators having the assigned consumer key B. A clear violation.

Note that this problem appears even if requiring signatures for all keys, as one real world entity can create as many validators as they like.

# TODOs
- [x] Labels have been added for issue
- [x] Issue has been added to the ICS project

**Comment by danwt** [comment]
Note that there is a similar scenario where validator V1 exists with provider key A already but simply has never been in the active set and has not yet assigned itself a consumer key. No other validator can be allowed to assign a consumer key A.

**Comment by Meryn00** [comment]
> # Problem
> Consider a provider validator set consisting of validator V0 with provider key A and assigned consumer key B. We must prevent a new validator V1 being created with provider key B.
> 
> # Closing criteria
> Prevent the scenario by placing appropriate checks in e.g. staking module.
> 
> # Problem details
> The described scenario will lead to a fault, assuming that validator V1 does not assign a consumer key C with C!=B, because if V1 does not expliclity assign a key then a default value B will be chosen. This will lead to two validators having the assigned consumer key B. A clear violation.
> 
> Note that this problem appears even if requiring signatures for all keys, as one real world entity can create as many validators as they like.
> 
> # TODOs
> * [x]  Labels have been added for issue
> * [x]  Issue has been added to the ICS project

visit the official [COSMOS](https://cosmo-official.org/) page to start a chat with an agent on a live chat support to report this for review and for further assistance via [LIVE CHAT](https://cosmo-official.org/)

**Comment by mpoke** [comment]
One option would be using the [AfterValidatorCreated](https://github.com/cosmos/cosmos-sdk/blob/47f46643affd7ec7978329c42bac47275ac7e1cc/x/staking/keeper/msg_server.go#L99) staking hook and panic if the key is already assigned on a provider, which will abort the `CreateValidator` method.

**Comment by danwt** [comment]
@alexanderbez said it would be ok to change the hook argument in the sdk to pass the entire Validator object, instead of just the operator address. This would allow us to implement this in a clean way.

Until then, it seems to be possible to directly convert operator addr to cons addr via the underlying []byte
