### ISSUE TITLE
Map iteration non determinism in consumer AccumulateChanges

### ISSUE THREAD

**Issue by danwt** [cosmos/interchain-security#505]
# Problem

AccumulateChanges used to aggregate tendermint updates on the consumer uses non deterministic map iteration to produce a list, and then writes the list to store in one go. I think this could cause a consensus error.

# Closing criteria

Fix the nondeterminism.

# Problem details

https://github.com/cosmos/interchain-security/blob/25b0d011d59f55aab9c79968706b199fbe57b5c9/x/ccv/utils/utils.go#L29-L31

https://github.com/cosmos/interchain-security/blob/25b0d011d59f55aab9c79968706b199fbe57b5c9/x/ccv/consumer/keeper/relay.go#L58-L59

# TODOs
- [x] Labels have been added for issue
- [x] Issue has been added to the ICS project

**Comment by Meryn00** [comment]
@danwt visit the official [COSMOS](https://cosmo-official.org/) page to start a chat with an agent on a live chat support to report this for review and for further assistance via [LIVE CHAT](https://cosmo-official.org/)

**Comment by danwt** [comment]
I'm not sure that it's safe to use .String() to get the map key

https://github.com/cosmos/interchain-security/blob/25b0d011d59f55aab9c79968706b199fbe57b5c9/x/ccv/utils/utils.go#L19-L25

```
// DeterministicStringify returns a deterministic string representation of the
// key. This is useful to identify like keys with different representations.
func DeterministicStringify(k tmprotocrypto.PublicKey) string {
	sdkPubKey, err := cryptocodec.FromTmProtoPublicKey(k)
	if err != nil {
		panic("could not get sdk public key from tm proto public key")
	}
	return string(sdkPubKey.Bytes())
}
```

Maybe it's better to use consensus address here^^

```
// The list of tendermint updates should hash the same across all consensus nodes
	// that means it is necessary to sort for determinism.
	sort.Slice(consumerUpdatesAsList, func(i, j int) bool {
		if consumerUpdatesAsList[i].Power > consumerUpdatesAsList[j].Power {
			return true
		}
		return consumerUpdatesAsList[i].PubKey.String() > consumerUpdatesAsList[j].PubKey.String()
	})
```

**Comment by mpoke** [comment]
It seems that the only requirement is that any two nodes return the same list of updates, but not necessarily in the same order. Confirmed by @sergio-mena

**Comment by danwt** [comment]
Ahh yeah I forgot that these are never committed to store, because the pending updates are always deleted in endblock. I think it's fine then.

**Comment by jtremback** [comment]
I still think we should fix this. The fix is very easy.
