### ISSUE TITLE
Refactor more integration tests to consider multiple consumers

### ISSUE THREAD

**Issue by shaspitz** [cosmos/interchain-security#506]
# Problem
#475 is a good start to making our integration tests consider multiple consumers. But further work is needed. 

# Closing criteria
Build out and improve integration setup code, and integration tests themselves to consider multiple consumers. This issue can potentially be split into more granular ones if needed.  

# Problem details
Regarding integration setup:
- #475 refactors `CCVTestSuite.SetupTest()`, and `CCVTestSuite.SetupCCVChannel()` to be functional for multiple consumers. 
- `CCVTestSuite.SetupTransferChannel()` and various other helpers still need to be refactored for multiple consumers

Regarding integration tests themselves:
- #475 makes `TestRelayAndApplySlashPacket` consider multiple consumers, but all other integration tests still use a single consumer

# TODOs
- [x] Labels have been added for issue
- [x] Issue has been added to the ICS project

**Comment by danwt** [comment]
Hey, can this be closed yet?

**Comment by smarshall-spitzbart** [comment]
This issue is not solved yet, and pretty important imo. Most e2e tests still consider only one consumer

**Comment by MSalopek** [comment]
Tests have multiple consumers and test key assignment features on one of the consumers.

Closing as completed. I cannot find the issue that solved this because there were many issues adding small changes + a large cosmos-sdk v47 refactor.
