### ISSUE TITLE
Consumer chain removal sub-protocol fails to remove some chains

### ISSUE THREAD

**Issue by ivan-gavran** [cosmos/interchain-security#513]
Surfaced from @informalsystems  audit of [Interchain Security](https://github.com/cosmos/interchain-security/) at commit https://github.com/cosmos/interchain-security/commit/dc19c57f71fb1adb38a5b73db0bdd3a95d99f713

# Problem
[`EndBlockCCR`](https://github.com/cosmos/interchain-security/blob/dc19c57f71fb1adb38a5b73db0bdd3a95d99f713/x/ccv/provider/keeper/relay.go#LL311C6-L311C7) removes chains which timed out. However, when iterating through all chains, it stops as soon as it finds one chain that did not time out, falsely assuming that the chains are ordered by their time of arrival <=> expiration time.

# Closing criteria

The bug is confirmed and fixed.

# Problem details

Please describe the problem in all detail.

[This part of the code](https://github.com/cosmos/interchain-security/blob/dc19c57f71fb1adb38a5b73db0bdd3a95d99f713/x/ccv/provider/keeper/relay.go#L318-L325) might be wrong:
   - it breaks out of iteration as soon as it finds one init timeout that has not expired (citing the assumption that they are ordered-implicitly-by the time of arrival)
   ```go
	k.IterateInitTimeoutTimestamp(ctx, func(chainID string, ts uint64) bool {
		if currentTimeUint64 > ts {
			// initTimeout expired
			chainIdsToRemove = append(chainIdsToRemove, chainID)
			// continue to iterate through all timed out consumers
			return true
		}
		// break iteration since the timeout timestamps are in order
		return false
	})
   ```
   - looking into the [iteration function](https://github.com/cosmos/interchain-security/blob/dc19c57f71fb1adb38a5b73db0bdd3a95d99f713/x/ccv/provider/keeper/keeper.go#L803-L803), it uses the [`KVStorePrefixIterator`](https://github.com/cosmos/interchain-security/blob/dc19c57f71fb1adb38a5b73db0bdd3a95d99f713/x/ccv/provider/keeper/keeper.go#L805-L805). This iterator _iterates over keys in ascending order_.
   - but keys are simply a concatenation of a fixed prefix and the `chainID` as given in the proposal, thus, they do not encode the order of arrival
   - thus, whether or not the function does what it promises to do, depends on the alphabetical order of `chainID`s

I added [a test illustrating the problem](https://github.com/cosmos/interchain-security/commit/9294f7482d894678fc03bf56d4042f10bc550490) in my fork of the repo.

# TODOs
- [x] Labels have been added for issue
- [x] Issue has been added to the ICS project

**Comment by danwt** [comment]
Nice job, thanks!

**Comment by ivan-gavran** [comment]
@danwt , a similar pattern can be found [just below](https://github.com/cosmos/interchain-security/blob/9294f7482d894678fc03bf56d4042f10bc550490/x/ccv/provider/keeper/relay.go#L364), when iterating over VSC send timestamps. There, only a first send timestamp is checked, again assuming that the first in the iteration is also the first chronologically.  However, the assumption is probably justified there, because the key consists of the part which is fixed per-chain and the `vscID`, where the sequence of `vscID`s is an ascending sequence of natural numbers.

While this does not seem to be a problem, I am raising the issue here
a) so that you can double check my "no-problem" justification
b) to call your attention this somewhat unclear part of the code. Namely, 
  - what if in some future refactoring `vscId`s are generated as random keys? 
  - it might just be useful to have an explicit function `GetTheOldest..`, instead of accomplishing the same by iterating and stopping immediately after the first element.

**Comment by danwt** [comment]
Another possibly related issue

- https://github.com/cosmos/interchain-security/issues/446
