### ISSUE TITLE
Run happy path integration tests only on push/merge to main

### ISSUE THREAD

**Issue by MSalopek** [cosmos/interchain-security#514]
# Problem
Integration tests are run for all PRs, and on each push to an opened PR. This results in long pipeline run times which may not be desireable.

Since we have significant e2e and unittest coverage it would be beneficial to run integration tests once the PR is actually merged into the main branch. That way we can have long running (> 20 minutes) and more complex tests without any time constraints. This would turn integration tests into more of a simulation that we run on each merge to main to confirm expected behaviour in semi-real world scenarios.

We could set it up so that failure to execute integration tests results in some emails being sent out to maintainers and code owners, just so we are aware that something is wrong.

It is still expected that integration tests pass for each PR. This can be solved by running a subset of the integration tests for i.e. running only happy path steps.

It would be best to setup some workflows that can be run manually and have a `nightly` test run which will run after everyone finishes their work for the day. The `nightly` run should run all tests and pull from `main` branch

# Closing criteria
Integration tests are running on push/merge to main instead of each PR.

# TODOs
- [x] Labels have been added for issue
- [ ] Issue has been added to the ICS project

**Comment by smarshall-spitzbart** [comment]
Along with what's already mentioned, the important thing is that integration tests are not commented out/skipped during the CI process. This is currently the case AFAIK
