### ISSUE TITLE
difftest core: Amend diff model with throttle changes (normal operation)

### ISSUE THREAD

**Issue by danwt** [cosmos/interchain-security#533]
# Problem

The slash throttle PR changes the way things work under normal operation (and abnormal operation). The diff test model should be changed to account for this.

# Closing criteria

Update the diff test core model so that the tests pass using the throttle when the Replenish Period and Allowance params are large.

# Problem details

The throttle should work almost as normal when the slash allowance is very large. 

# TODOs
- [x] Labels have been added for issue
- [x] Issue has been added to the ICS project

**Comment by danwt** [comment]
cc @smarshall-spitzbart

**Comment by smarshall-spitzbart** [comment]
Looks good, this issue is about using diff tests as a regression test, and will need to be fixed before #462 is merged. Whereas #534 is future work to test the throttling logic (not regression testing)

**Comment by danwt** [comment]
See https://github.com/cosmos/interchain-security/pull/571
