### ISSUE TITLE
difftest core: Amend diff model with throttle changes once spec has been updated

### ISSUE THREAD

**Issue by danwt** [cosmos/interchain-security#534]
# Problem

The slash throttle PR changes the way things work when there are a lot of incoming slash requests. The diff test model should be changed to account for this, after the upstream canonical spec has been changed.

# Closing criteria

After the ICS spec has been updated to account for throttling, the diff model should be updated to match.

# Problem details

See

- https://github.com/cosmos/interchain-security/issues/533

# TODOs
- [x] Labels have been added for issue
- [x] Issue has been added to the ICS project

**Comment by danwt** [comment]
cc @smarshall-spitzbart

**Comment by smarshall-spitzbart** [comment]
@mpoke @MSalopek I see this is marked as high priority. Which issue should I put effort into first: this one, or https://github.com/cosmos/interchain-security/issues/615?

**Comment by mpoke** [comment]
@smarshall-spitzbart This one should have priority as the other is just documentation.

**Comment by smarshall-spitzbart** [comment]
It might be beneficial to introduce all throttle related changes to the ICS spec before tackling this issue

**Comment by mpoke** [comment]
@smarshall-spitzbart is this issue fixed?

**Comment by smarshall-spitzbart** [comment]
> @smarshall-spitzbart is this issue fixed?

This issue hasn't been completed. Maybe it's being worked on by @sainoe or @MSalopek? Lmk if I should make this my priority

**Comment by p-offtermatt** [comment]
Closing since difftest model was deprecated in favor of MBT, may reopen if we want this in the MBT model
