### ISSUE TITLE
Use consistent VSC/VSU/ValsetUpdate symbol names

### ISSUE THREAD

**Issue by danwt** [cosmos/interchain-security#535]
# Problem

The terms val set update / val set change and their abbreviations are used in various ways all over the codebase and spec and docs. We should pick one term and stick with it.

# Closing criteria

Change all occurences of the like terms to a unified term.

# Problem details

See

- https://github.com/cosmos/interchain-security/issues/331

for an old issue which wasn't specific enough.

Note, this is very low priority.

# TODOs
- [x] Labels have been added for issue
- [ ] Issue has been added to the ICS project

**Comment by smarshall-spitzbart** [comment]
Closing since this is a duplicate of #608
