### ISSUE TITLE
At least one instance of incorrect iteration in the codebase- there may be more

### ISSUE THREAD

**Issue by jtremback** [cosmos/interchain-security#537]
# Problem

Some iterator(s) in the codebase iterate over keys which include a length prefix. This means that the length prefix is ordering the iteration, not the actual value in the key. We need to find out if this could cause any problems. For example, there are indexes with keys that have time in them, but the time is prefixed by a length. This may be ok, or it may cause incorrect ordering, depending on serialization details.

For example, in this function:

```
func (k Keeper) IteratePendingConsumerAdditionProps(ctx sdk.Context, cb func(spawnTime time.Time, prop types.ConsumerAdditionProposal) bool) {
	iterator := k.PendingConsumerAdditionPropIterator(ctx)
	defer iterator.Close()

	for ; iterator.Valid(); iterator.Next() {
		key := iterator.Key()
		spawnTime, _, err := types.ParsePendingCAPKey(key)
		if err != nil {
			panic(fmt.Errorf("failed to parse pending client key: %w", err))
		}

		var prop types.ConsumerAdditionProposal
		k.cdc.MustUnmarshal(iterator.Value(), &prop)

		if !cb(spawnTime, prop) {
			return
		}
	}
}
```
We think we are iterating in order of time, but we are really iterating in order of the serialized length of the timestamps.

# Closing criteria

Someone needs to study the iterators and figure out how to remove uncertainty. 

For example- don't use length prefixes on any key that needs to be iterated over in order. 

Or- don't use length prefixes at all. They are only used to enable parsing values back out of a key (otherwise you can just hash values to a constant length in a key). Values in keys could be stored alongside the values in the value instead of needing to parse the key.

Another fix- don't break out of iterations, making the order not matter

**Comment by smarshall-spitzbart** [comment]
#592 is related, but tracked as separate issue with more focus. This issue will be closed by #583
