### ISSUE TITLE
Confirm logging behavior

### ISSUE THREAD

**Issue by smarshall-spitzbart** [cosmos/interchain-security#541]
# Problem
Reviving https://github.com/cosmos/interchain-security/issues/198. We only log in [one place](https://github.com/cosmos/interchain-security/blob/d66eaec0dd84affbf43bb348b8e06088030b2269/x/ccv/consumer/keeper/relay.go#L219) AFAIK. We need to confirm the behavior of such logging, then we can add logging where needed.

# Closing criteria

Answer the below questions, then open a new issue on specific places we can add logging

# Questions to answer

- Is our `k.Logger` hooked up correctly to actually view logs?
- does `k.Logger.Error` panic the binary?
- Are we using the correct, or most up to date cosmos sdk logging system?

**Comment by MSalopek** [comment]
Thanks for bringing this up!

> Is our k.Logger hooked up correctly to actually view logs?

The words "logs" and "logging" are used in multiple contexts. You can have logs show up in your tx output, or you can have logs you can see on the terminal (in log files etc).

Where do you expect to view the logs?

**Comment by smarshall-spitzbart** [comment]
@MSalopek I'm referring to binary logs here, only accessible to validators or someone running a full node

**Comment by smarshall-spitzbart** [comment]
> Is our k.Logger hooked up correctly to actually view logs?
does k.Logger.Error panic the binary?
Are we using the correct, or most up to date cosmos sdk logging system?

1 and 3 are yes ✅ , just need to answer point 2
