### ISSUE TITLE
Return IBC err ack when val not found for slash packet

### ISSUE THREAD

**Issue by smarshall-spitzbart** [cosmos/interchain-security#546]
# Problem

#542 will close #414 by adding more clarity around validation vs handling. Where recv packet validation will return an ibc err ack upon failure, while recv packet handling would panic upon any system critical failure.

#542 is intended be refactoring (no functionality changes), whereas this issue is concerned with changing provider functionality to return an IBC err ack on recv slash packet validation when the validator from the packet is not found or unbonded.

# Closing criteria

Change functionality of provider as described below, test new functionality properly.

# Problem details

Currently, when the validator from a recv slash packet is not found or unbonded, we simply log an error and drop the packet. There is no err ack that is returned to the consumer. We should return an err ack in this case, by adding a check to `validateSlashPacket()`

Note that changing this functionality seems trivial, but there are a good amount of tests that non-trivially rely on current provider functionality, `TestConsumerPacketSendExpiredClient` as example.

**Comment by mpoke** [comment]
@smarshall-spitzbart what would be the benefit / impact of solving this issue?

**Comment by smarshall-spitzbart** [comment]
Returning an ibc err ack would [offboard the consumer](https://github.com/cosmos/interchain-security/blob/cb6f856f1da105ad8f7e3f2803cd7a7dc49447fb/x/ccv/consumer/keeper/relay.go#L284).

However, with throttling fully implemented, the worst case scenario for spammed slash packets from a consumer is just wasted computation, and high fees paid by relayers. Ie. there's no security threat here. 

Also, offboarding consumers comes with it's own pros/cons.

I'll close this issue, feel free to re-open if you disagree
