### ISSUE TITLE
Provider and Consumer's `OnAcknowledgementPacket` should only log an error

### ISSUE THREAD

**Issue by shaspitz** [cosmos/interchain-security#547]
# Problem

[OnAcknowledgementPacket](https://github.com/cosmos/interchain-security/blob/d66eaec0dd84affbf43bb348b8e06088030b2269/x/ccv/consumer/keeper/relay.go#L213) currently closes the CCV channel in the event that an IBC err ack is returned from the provider. If CCV is working as intended, these paths should never be executed. Therefore a returned err ack is probably a symptom of a deeper bug that needs to be addressed manually.

# Closing criteria

Either only log an error in OnAcknowledgementPacket, or halt the consumer. Let users know that there's a critical bug to be addressed, without polluting state by executing automatic recovery logic.

**Comment by smarshall-spitzbart** [comment]
Edit: this issue also applies to the provider's `OnAcknowledgementPacket` method, and should be changed for the same reasons

**Comment by mpoke** [comment]
@jtremback This is a product discussion. Should a critical bug (e.g., marshaling errors) result in the consumer shutting down?

**Comment by smarshall-spitzbart** [comment]
Note if we're able to implement epochs, we could elegantly halt the consumer upon receiving an err ack, be able to patch the consumer binary with no state migrations, and resume the consumer once fixed. Any epoch packets constructed before/during the halt would be queued up, and ready to send once the consumer is back up

**Comment by mpoke** [comment]
Closing as non-issue. The behavior is as intended.
