### ISSUE TITLE
Document precise cases when assigning a consumer key K is allowed

### ISSUE THREAD

**Issue by danwt** [cosmos/interchain-security#555]
# Problem

The rules for assigning a key are not completely trivial due to needing to make things secure. This needs to be documented.

# Closing criteria

Document clearly somewhere

# Problem details

None

# TODOs
- [x] Labels have been added for issue
- [x] Issue has been added to the ICS project

**Comment by mpoke** [comment]
@danwt Could you provide more details here? To what rules do you refer?
