### ISSUE TITLE
IterateInitTimeoutTimestamp should iterate consumer timeouts in insertion order

### ISSUE THREAD

**Issue by MSalopek** [cosmos/interchain-security#561]
# Problem
Before the code audit the expected behaviour was that `IterateInitTimeoutTimestamp` iterates over consumer timeout timestamps in insertion order (from lowest to highest timestamp).

#513 raised an issue pointing out that the iteration actually happens in alphabetic ascending order in this case, so some consumers were never removed. 

# Closing criteria
Make `IterateInitTimeoutTimestamp` iterate over timestamps in insertion order. To achieve this, insertions into the Store will have to be updated.

# TODOs
- [x] Labels have been added for issue
- [x] Issue has been added to the ICS project

**Comment by mpoke** [comment]
Fixed by https://github.com/cosmos/interchain-security/pull/549
