### ISSUE TITLE
Add type tag to VSCMatured / SlashPackets

### ISSUE THREAD

**Issue by jtremback** [cosmos/interchain-security#567]
# Problem

We do not check the type before unmarshaling packets on the provider. We just try to unmarshal as one type, and if it fails, try as another type. This works for now, but is brittle and error prone.

# Closing criteria

A type tag is implemented to distinguish packet types.

# Problem details

On lines https://github.com/cosmos/interchain-security/blob/main/x/ccv/provider/ibc_module.go#L175-L189

We unmarshal without really knowing the type of packets on our CCV channel. This works, but is very sketchy.

Our two packet types are

```
type VSCMaturedPacketData struct {
	// the id of the VSC packet that reached maturity
	ValsetUpdateId uint64 `protobuf:"varint,1,opt,name=valset_update_id,json=valsetUpdateId,proto3" json:"valset_update_id,omitempty"`
}
```

and

```
type SlashPacketData struct {
	Validator types.Validator `protobuf:"bytes,1,opt,name=validator,proto3" json:"validator" yaml:"validator"`
	// map to the infraction block height on the provider
	ValsetUpdateId uint64 `protobuf:"varint,2,opt,name=valset_update_id,json=valsetUpdateId,proto3" json:"valset_update_id,omitempty"`
	// tell if the slashing is for a downtime or a double-signing infraction
	Infraction types1.InfractionType `protobuf:"varint,3,opt,name=infraction,proto3,enum=cosmos.staking.v1beta1.InfractionType" json:"infraction,omitempty"`
}
```

The only actual difference between these two types is that SlashPacketData has a Validator field. InfractionType has `omitempty` so could be omitted, and ValsetUpdateId exists on both. It could be very easy for the one of these to parse as the other with some minor code changes.

We should come up with a [tagging scheme](https://serde.rs/enum-representations.html) and use it.

# TODOs
- [x] Labels have been added for issue
- [x] Issue has been added to the ICS project

**Comment by MSalopek** [comment]
We already use a wrapper structure on the consumer side: https://github.com/cosmos/interchain-security/blob/main/proto/interchain_security/ccv/consumer/v1/consumer.proto#L84.

Might be useful to use the same principle - we unmarshal the wrapper, check the type/tag and only then umarshal the embedded data.

**Comment by smarshall-spitzbart** [comment]
Note that this issue could also make the way that we queue throttled packets a lot cleaner.
