### ISSUE TITLE
Create single send function

### ISSUE THREAD

**Issue by mpoke** [cosmos/interchain-security#57]
The code needed to send a packet is duplicated throughout the implementation, e.g., [here](https://github.com/cosmos/interchain-security/blob/df6f8c567a4a62e91b031a7e308db06a094f5aaf/x/ccv/parent/keeper/relay.go#L27) and [here](https://github.com/cosmos/interchain-security/blob/df6f8c567a4a62e91b031a7e308db06a094f5aaf/x/ccv/child/keeper/relay.go#L111). We should have one single function for sending packets, e.g.,
```go
func (k Keeper) SendPacket(ctx sdk.Context, channelID string, packetData []byte) error {
  channel, ok := k.channelKeeper.GetChannel(ctx, types.PortID, channelID)
  if !ok {
    return sdkerrors.Wrapf(channeltypes.ErrChannelNotFound, "channel not found for channel ID: %s", channelID)
  }
  channelCap, ok := k.scopedKeeper.GetCapability(ctx, host.ChannelCapabilityPath(types.PortID, channelID))
  if !ok {
    return sdkerrors.Wrap(channeltypes.ErrChannelCapabilityNotFound, "module does not own channel capability")
  }

  // get the next sequence
  sequence, found := k.channelKeeper.GetNextSequenceSend(ctx, types.PortID, channelID)
  if !found {
    return sdkerrors.Wrapf(
	channeltypes.ErrSequenceSendNotFound,
	"source port: %s, source channel: %s", types.PortID, channelID,
    )
  }
  packet := channeltypes.NewPacket(
    packetData, sequence,
    types.PortID, channelID,
    channel.Counterparty.PortId, channel.Counterparty.ChannelId,
    clienttypes.Height{}, uint64(ccv.GetTimeoutTimestamp(ctx.BlockTime()).UnixNano()),
  )
  if err := k.channelKeeper.SendPacket(ctx, channelCap, packet); err != nil {
    return err
  }
  return nil
```

**Comment by mpoke** [comment]
@sainoe It would be great to have a general keeper.go file, i.e., `x/ccv/keeper/keeper.go` that contains all the functionalities common for both the consumer and the provider chain, such as the `SendPacket` function. For that, we need to have a common `Keeper`. Currently, each chain type has its own `Keeper` struct defined ([here](https://github.com/cosmos/interchain-security/blob/df58493d0470963db6df40c1c8aa14e218df631d/x/ccv/child/keeper/keeper.go#L26) and [here](https://github.com/cosmos/interchain-security/blob/df58493d0470963db6df40c1c8aa14e218df631d/x/ccv/parent/keeper/keeper.go#L31)). However, the two struct must have some common fields, e.g.,
```
type Keeper struct {
  storeKey         sdk.StoreKey
  cdc              codec.BinaryCodec
  paramSpace       paramtypes.Subspace
  scopedKeeper     capabilitykeeper.ScopedKeeper
  channelKeeper    ccv.ChannelKeeper
  portKeeper       ccv.PortKeeper
  connectionKeeper ccv.ConnectionKeeper
  clientKeeper     ccv.ClientKeeper
  accountKeeper    ccv.AccountKeeper
  slashingKeeper   ccv.SlashingKeeper
  feeCollectorName string
}
``` 
What do you think?

**Comment by sainoe** [comment]
I can see some clear benefits to have a common Keeper. However we need to evaluate the development cost to add a third keeper and KV store into the code design. Any thoughts on this @AdityaSripal ?

**Comment by mpoke** [comment]
After discussing with both @jtremback and @sainoe, we decided to just create a utility function for sending packets over IBC, i.e., 
```go
func SendPacketOverIBC(
	ctx sdk.Context,
	scopedKeeper capabilitykeeper.ScopedKeeper,
	channelKeeper ccv.ChannelKeeper,
	channelID string,
	portID string,
	packetData []byte,
) error
```
