### ISSUE TITLE
Improve tests to make sure we are using different keys for Operator Address and Cons Address

### ISSUE THREAD

**Issue by danwt** [cosmos/interchain-security#572]
# Problem

Our unit and e2e tests frequently use the same bytes for validator operators and consensus addres. That means we dont' properly test paths where they should be treated differently.

# Closing criteria

Improve the tests and cryptotestutils to use different bytes for each type.

# Problem details

The best way to achieve this is to make both addresses stem from different private keys.

See 

- https://github.com/cosmos/interchain-security/pull/462#discussion_r1041366884

for originating context

# TODOs
- [x] Labels have been added for issue
- [x] Issue has been added to the ICS project

**Comment by sainoe** [comment]
Solved in #672
