### ISSUE TITLE
Create minimum runnable consumer chain

### ISSUE THREAD

**Issue by jtremback** [cosmos/interchain-security#59]
We need to create a canonical consumer chain which will act as a reference implementation for installing CCV into a consumer chain.

We are also creating a consumer chain running CosmWasm, which will be used by projects who do not want to touch Cosmos-SDK code and can implement all logic as a smart contract.

I think it makes sense for these two roles to be fulfilled by one binary. This way we can consolidate efforts, and the installed CosmWasm module makes the reference implementation more realistic. Here's a specification of this chain:

-----

For this consumer chain configuration, we are avoiding everything that could cause a problem. This configuration does not have goverance, and there is no way to change parameters (other than a chain update). There is an optional native token, but it is not a staking token. If the native token is enabled, there is a modified mint module with a fixed inflation percentage as a parameter. If the native token is not enabled, then there are no inflationary rewards on the chain.

Fees can be paid in the native token, or in a token transferred over IBC (such as the Atom). Fees and inflation rewards (fees only if the native token is not enabled), are split in a configurable percentage. One part goes to the provider chain, and the other part goes to a special module on the consumer chain. This module can be customized, but by default it will send the coins on to a configurable personal address or multi-sig.

Changes from a normal Cosmos-SDK chain:

- Staking module is disabled
- Governance module is disabled
- Distribution module is disabled, and funds flow through the CCV module to be sent to the provider chain
- Consumer redistribute module sends fees and rewards to an address configured in params
- Staking module functions called by slashing module are provided by the CCV module
- Mint module has a fixed inflation percentage, and can be disabled
- Genutil module is disabled
- CCV module is enabled
- CosmWasm module is installed

**Comment by mpoke** [comment]
> Mint module has a fixed inflation percentage, and can be disabled

So the Mint module on the consumer chain will not use information about the validator set or about the total staked amount, right? 

In the case the consumer chain has its own token, how will the inflation rewards be calculated? In other words, the fixed inflation percentage is a percentage of what? 

Currently, the Mint module needs `StakingTokenSupply()` and `BondedRatio()`. In the case of Interchain Security, the staking token is the provider chain token and the bonded ratio is the ratio of bonded provider tokens. This info could easily be passed to the consumer chain through VSC packets, which would enable the consumer chain to inflate its own token based on the e.g., ATOM. Is that something we want to do?

**Comment by mpoke** [comment]
> Governance module is disabled

Without governance, how easy would be for a consumer chain to update? Would the validators need social consensus to decide when to run the upgraded binary? Even in the case of a CosmWasm chain, is there an easy way for the smart contract to be updated, i.e., the consumer chain to update the application logic?

**Comment by okwme** [comment]
Governance is a requirement for our initial user, it's part of the minimum viable product.

**Comment by mpoke** [comment]
Related to https://github.com/cosmos/interchain-security/issues/66

**Comment by jtremback** [comment]
> Governance is a requirement for our initial user, it's part of the minimum viable product.

@okwme I just want to clarify, this is about work sequencing, not what we will launch with. I have renamed it to "minimum runnable consumer chain" to clear that up. Most of the stuff in this issue is well underway. Installing the ["democracy module"](https://github.com/cosmos/interchain-security/issues/66) in this chain will complete our MVP.

**Comment by mpoke** [comment]
This was closed as the issue of different consumer chains is addressed in #139, #141, #143
