### ISSUE TITLE
Diagnose GOC halt 

### ISSUE THREAD

**Issue by smarshall-spitzbart** [cosmos/interchain-security#595]
# Problem

Lots of slack discussion, this is me documenting efforts to fully diagnose why the GOC halt happened. 

# Closing criteria
Be able to consistently replicate the GOC bug, and confirm that a specific patch prevents the bug from occurring.

# Problem details

Our best guess at what happened is a deadlock caused by writing within iterators. Unfortunately, there are a good amount of unit and e2e tests covering the suspect code. But the halt/hang only occurred in the testnet.

**Comment by smarshall-spitzbart** [comment]
First step is to try out e2e, unit tests, and diff tests with a goleveldb backend

**Comment by smarshall-spitzbart** [comment]
Looks like https://github.com/cosmos/cosmos-sdk/issues/14296 is almost certainly the culprit, as we open two iterators in the GOC version of of throttling. I'll try to consistently replicate the deadlock from our code, then we can move on

**Comment by jtremback** [comment]
This is done, right?

**Comment by smarshall-spitzbart** [comment]
yes, will be closed by #462
