### ISSUE TITLE
Add custom static analysis rules to our CI

### ISSUE THREAD

**Issue by danwt** [cosmos/interchain-security#597]
# Problem

We are not making use of existing tools specialized to the sdk which might help us improve quality.

# Closing criteria

- Integrate our fork of gosec - https://github.com/cosmos/gosec - catches various SDK specific lints (https://github.com/cosmos/gosec/tree/master/rules/sdk)
- Integrate odekes consensuswarn - https://github.com/orijtech/consensuswarn - says if a PR has breaking changes to code called by BeginBlock/DeliverTx/EndBlock
- Integrate @ivan-gavran 's custom codeQL rules used during the code audit

into our ci

# TODOs
- [x] Labels have been added for issue
- [x] Issue has been added to the ICS project

**Comment by danwt** [comment]
Regarding codeQL:

I believe there are default rules in the standard codeql library, I’ve never actually looked at them myself.

We use a github action which takes this standard library and applies it our codebase. 
You can see an example of one of our runs https://github.com/cosmos/interchain-security/actions/runs/3689813964/jobs/6246174795
I’m not sure where

Here is a useful overview

https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/about-code-scanning-with-codeql#about-codeql-queries

and here is description of the codeQL library system

https://codeql.github.com/docs/codeql-cli/about-codeql-packs/

Here are the queries I believe GH uses by default

https://github.com/github/codeql/tree/codeql-cli/v2.11.6/go/ql/src

**Comment by mpoke** [comment]
Not relevant at the moment.
