### ISSUE TITLE
Iteration through `PacketMaturityTime`s assumes maturity time order

### ISSUE THREAD

**Issue by mpoke** [cosmos/interchain-security#598]
# Problem

`PacketMaturityTime`s are stored on the consumer under a key with the format `prefix | vscID`. As a result, the iteration is in the order of `vscID`s and not `maturityTimes` as [expected](https://github.com/cosmos/interchain-security/blob/3e339eaad34f37f4757049df775ea2c9a8fe941e/x/ccv/consumer/keeper/relay.go#L123). Since the `unbondingPeriod` on the consumer can be updated, ordering by `vscID`s is not the same as ordering by `maturityTimes`.

# Closing criteria

Ensure that the iteration over `PacketMaturityTime`s is in order of `maturityTimes`. 

# Problem details

A suggestion would be to use the same approach as in the staking module with the `MatureUBDQueue`, see https://github.com/cosmos/cosmos-sdk/blob/b46d83850270b82496e4cd61421d9ebc8bac87f2/x/staking/keeper/delegation.go#L376. This solution was implemented in https://github.com/cosmos/interchain-security/pull/583. 

# TODOs
- [x] Labels have been added for issue
- [x] Issue has been added to the ICS project

**Comment by smarshall-spitzbart** [comment]
In the PR that fixes this issue, could we use `time.Time` instead of uint64 for the business logic. There should be easy conversion between the two types

**Comment by mpoke** [comment]
Yes, use uint64 in the key and time.Time in the value
