### ISSUE TITLE
Key assignment adds iteration on `MsgCreateValidator`

### ISSUE THREAD

**Issue by mpoke** [cosmos/interchain-security#603]
# Problem

Due to the key assignment protocol, when creating a new validator in the staking module (via the `MsgCreateValidator` message), the code iterates over all consumer keys which have been assigned in order to check if the validator being added is, or was, a consumer chain validator. This can be used as an attack vector. 

# Closing criteria

Figure out a way to get rid of this check. 

# Problem details

The ICS code implements the `AfterValidatorCreated` staking hook, which is called when a new validator is created. This hook iterates over all assigned consumer addresses, i.e., https://github.com/cosmos/interchain-security/blob/3e339eaad34f37f4757049df775ea2c9a8fe941e/x/ccv/provider/keeper/hooks.go#L79 

# TODOs
- [x] Labels have been added for issue
- [x] Issue has been added to the ICS project

**Comment by jtremback** [comment]
The loop iterates over all validators, which is the source of the problem. It does this because it is looking for a consumer address matching the new validator's address in an index with keys like `chainId | consumerAddress`. It can't just iterate over all chainIds and try to get the consumerAddress for each one because there could consumerAddress stored for chainIds that have not been created yet.

To solve this we could create a second index with keys like `consumerAddress | chainId`. This can then be used to check if an address is in use with one operation.

**Comment by mpoke** [comment]
We should also look into whether is possible to have a single index with keys like `consumerAddress | chainId`. @danwt do you see any problems with that?

**Comment by danwt** [comment]
> a second index with keys like `consumerAddress | chainId`

I think it works and is simple 👍 

> have a single index with keys like `consumerAddress | chainId`

I think this also works, and this could replace the current `chainID | consumerAddress` because currently chain wise iteration is only done during `DeleteKeyAssignments(ctx sdk.Context, chainID string)` and this is a very rare operation.

**Comment by yaruwangway** [comment]
Hi, the main is updated.
right now, if chainID is nil, `GetAllValidatorsByConsumerAddr` will get all the consensus addresses on all consumer chains.
It is a bit inefficient, but what else issues this bring ?

If we change the index, from `chainId | consumerAddress` to `consumerAddress | chainId`,  then it has to loop through all the addresses to check if the chainID is the chainID desired.
Instead, present `len(chainID) | chainID ` is more efficient when getting addresses that ChainID not nil.
 https://github.com/cosmos/interchain-security/blob/d137d39f01a2e2c85f90e7ea0bc0d1738affb4b1/x/ccv/provider/keeper/key_assignment.go#L77

**Comment by mpoke** [comment]
`GetAllValidatorsByConsumerAddr` is called in three places:

- `ExportGenesis` calls `GetAllValidatorsByConsumerAddr(ctx, nil)`
- `AfterValidatorCreated` calls `ValidatorConsensusKeyInUse(h.k, ctx, valAddr)`, which calls `GetAllValidatorsByConsumerAddr(ctx, nil)`
- `DeleteKeyAssignments` calls `k.GetAllValidatorsByConsumerAddr(ctx, &chainID)`

Changing the index from `chainId | consumerAddress` to `consumerAddress | chainId` has the following effects: 

- The first call is not changed at all. Still need to iterate over all consumer addresses.
- The second call requires no iteration, i.e.,
```
// ValidatorConsensusKeyInUse is called when a new validator is created
// in the x/staking module of cosmos-sdk. In case it panics, the TX aborts
// and thus, the validator is not created. See AfterValidatorCreated hook.
func ValidatorConsensusKeyInUse(k *Keeper, ctx sdk.Context, valAddr sdk.ValAddress) bool {
	// Get the validator being added in the staking module.
	val, found := k.stakingKeeper.GetValidator(ctx, valAddr)
	if !found {
		// Abort TX, do NOT allow validator to be created
		panic("did not find newly created validator in staking module")
	}

	// Get the consensus address of the validator being added
	consensusAddr, err := val.GetConsAddr()
	if err != nil {
		// Abort TX, do NOT allow validator to be created
		panic("could not get validator cons addr ")
	}

        store := ctx.KVStore(k.storeKey)
        prefix := ccvtypes.AppendMany(types.ValidatorsByConsumerAddrBytePrefix, consensusAddr)
        iterator := sdk.KVStorePrefixIterator(store, prefix)
	defer iterator.Close()

	for ; iterator.Valid(); iterator.Next() {
             return true
        }
        return false
}
``` 
- The third call is less efficient as now we need to iterate over all consumer addresses and just remove the ones for a particular chain. This doesn't really matter though, since `DeleteKeyAssignments` is called only when a consumer chain is removed.

**Comment by yaruwangway** [comment]
I see, in the above second call, when iterate the db to find the `validatorConsumerAddrs`, the consumer chainID is not known,(see below link the chainID aurgument is nil) , so that the prefix with |chainID| does not help fast find the addr, all the address with different chain-ID are returned. So `chainId | consumerAddress` and `consumerAddress | chainId ` are the same in terms of iteration db. https://github.com/cosmos/interchain-security/blob/d137d39f01a2e2c85f90e7ea0bc0d1738affb4b1/x/ccv/provider/keeper/hooks.go#L103

**Comment by yaruwangway** [comment]
since the key is stored like `bytePrefix | len(chainID) | chainID | ConsAddress`, now we want to store  
- `bytePrefix | ConsAddress|len(chainID) | chainID ` or 
- `bytePrefix | ConsAddress| chainID|len(chainiD) ` ?

**Comment by mpoke** [comment]
> * the migration will not delete the old key-value, the old key-value will be deleted in the next upgrade after the upgrade containing this migration.

Why can't we delete the old key-value?

**Comment by yaruwangway** [comment]
> 

we can do all in one migration, i just feel it is secure if we still keep the old data for a bit longer ?

**Comment by MSalopek** [comment]
Just chiming in; it could be worthwhile to explore what cosmos-sdk collections bring us with regards to this issue.
There are some useful, more abstract types for handling data in [the collections package](https://docs.cosmos.network/main/packages/collections) that will be released in v50.

If this turns out to be too much trouble, let's consider using a collection if applicable and refactor this it in a later ICS version?

> we can do all in one migration, i just feel it is secure if we still keep the old data for a bit longer ?

I'm not sure keeping old data adds to security.

**Comment by yaruwangway** [comment]
Big thanks to @MSalopek  for this simple solution ! just check with trying each consumer ChainID, there are not so many chains!

**Comment by MSalopek** [comment]
A note from today's dev session.

It seems that the iterations discussed above can be refactored such that the store key is calculated and simply accessed via `store.Get` that way we could check if the key is in use by making a <10 calls to the store instead of iterating over all consumer keys.

e.g.
```golang
// ValidatorConsensusKeyInUse is called when a new validator is created
// in the x/staking module of cosmos-sdk. In case it panics, the TX aborts
// and thus, the validator is not created. See AfterValidatorCreated hook.
func ValidatorConsensusKeyInUse(k *Keeper, ctx sdk.Context, valAddr sdk.ValAddress) bool {
	// Get the validator being added in the staking module.
	val, found := k.stakingKeeper.GetValidator(ctx, valAddr)
	if !found {
		// Abort TX, do NOT allow validator to be created
		panic("did not find newly created validator in staking module")
	}

	// Get the consensus address of the validator being added
	consensusAddr, err := val.GetConsAddr()
	if err != nil {
		// Abort TX, do NOT allow validator to be created
		panic("could not get validator cons addr ")
	}

	consuChains := k.GetAllConsumerChains(ctx)
	for _, consumerChain := range consuChains {
		if _, found := k.GetValidatorByConsumerAddr(
			ctx,
			consumerChain.ChainId,
			providertypes.NewConsumerConsAddress(consensusAddr)); found {
			return true
		}
	}

	return false
}
```

Additionally, a delete operation can be performed on the entire store subtree.

e.g.
```
// ChainIdWithLenKey returns the key with the following format:
// bytePrefix | len(chainID) | chainID
func ChainIdWithLenKey(prefix byte, chainID string) []byte {
	chainIdL := len(chainID)
	return ccvtypes.AppendMany(
		// Append the prefix
		[]byte{prefix},
		// Append the chainID length
		sdk.Uint64ToBigEndian(uint64(chainIdL)),
		// Append the chainID
		[]byte(chainID),
	)
}


// DeleteKeyAssignments deletes all the state needed for key assignments on a consumer chain
func (k Keeper) DeleteKeyAssignments(ctx sdk.Context, chainID string) {
	// delete ValidatorsByConsumerAddr
	for _, validatorConsumerAddr := range k.GetAllValidatorsByConsumerAddr(ctx, &chainID) {
		consumerAddr := types.NewConsumerConsAddress(validatorConsumerAddr.ConsumerAddr)
		k.DeleteValidatorByConsumerAddr(ctx, chainID, consumerAddr)
	}

        // replace with
        store.Delete(ctx, ChainWithLenKey(prefix, chainID)
        ...
}
```

Not sure about the delete, but by intuition I'd wager it can be done like that.

**Comment by yaruwangway** [comment]
> The loop iterates over all validators, which is the source of the problem. It does this because it is looking for a consumer address matching the new validator's address in an index with keys like `chainId | consumerAddress`. It can't just iterate over all chainIds and try to get the consumerAddress for each one because there could consumerAddress stored for chainIds that have not been created yet.
> 
> To solve this we could create a second index with keys like `consumerAddress | chainId`. This can then be used to check if an address is in use with one operation.

@jtremback , "It can't just iterate over all chainIds and try to get the consumerAddress for each one because there could consumerAddress stored for chainIds that have not been created yet." what does this mean ?  cc @MSalopek

**Comment by MSalopek** [comment]
@mpoke 
Can we implement the TODO from the message above?
```golang
	// TODO: In future, a mechanism will be added to limit assigning keys to chains
	// which are approved or pending approval, only
```

**Comment by mpoke** [comment]
> @mpoke Can we implement the TODO from the message above?
> 
> ```go
> 	// TODO: In future, a mechanism will be added to limit assigning keys to chains
> 	// which are approved or pending approval, only
> ```

Sure. Please open a separate issue though.

**Comment by yaruwangway** [comment]
just to clarify: 
- is it possible `chainID` == ""  in the store key: `bytePrefix | len(chainID) | chainID | ConsAddress`?
- `GetAllConsumerChains` does not return chains with `chainID` == "" ?

@mpoke @MSalopek
