### ISSUE TITLE
Improve unit testing setup

### ISSUE THREAD

**Issue by shaspitz** [cosmos/interchain-security#604]
# Problem

Our unit tests use a different store setup than what is used for a "real" app.go. This could be seen as a feature in that the unit tests run against a bare-bones keeper without any extraneous/esoteric app setup. However, it is possible to run true unit tests with a "real" app.go, and this may be a good option in that it might find more bugs like the one that caused the GOC halt.

# Closing criteria

Either change our `unit_test_helpers.go` file to be closer to the typical setup for an app.go, or leverage the already existing [GaiaAppIniter](https://github.com/cosmos/interchain-security/blob/3e339eaad34f37f4757049df775ea2c9a8fe941e/testutil/ibc_testing/specific_setup.go#L33) to run our provider unit tests against the real gaia app.go. The same applies for consumer unit tests and something like Neutron, etc.

# Problem details

[here](https://github.com/cosmos/interchain-security/blob/3e339eaad34f37f4757049df775ea2c9a8fe941e/testutil/keeper/unit_test_helpers.go#L41) is how we currently setup the store for unit tests, and [here](https://github.com/cosmos/interchain-security/blob/3e339eaad34f37f4757049df775ea2c9a8fe941e/app/consumer-democracy/proposals_whitelisting_test.go#L14) is how we could instead leverage already defined `AppIniter`s to run unit tests against app.go setups.

Note there are some slight changes to make our unit test setup behave closer to typical app.go implementations, if we want to take the bare-bones keeper route:
```go
// NewInMemKeeperParams instantiates in-memory keeper params with default values
func NewInMemKeeperParams(t testing.TB) InMemKeeperParams {
	storeKey := sdk.NewKVStoreKey(ccvtypes.StoreKey)
	tStoreKey := sdk.NewTransientStoreKey(paramstypes.TStoreKey)

	db := tmdb.NewMemDB()
	stateStore := store.NewCommitMultiStore(db)
	stateStore.MountStoreWithDB(storeKey, sdk.StoreTypeIAVL, nil)
	stateStore.MountStoreWithDB(tStoreKey, sdk.StoreTypeTransient, nil)
	require.NoError(t, stateStore.LoadLatestVersion())

	registry := codectypes.NewInterfaceRegistry()
	cdc := codec.NewProtoCodec(registry)

	paramsSubspace := paramstypes.NewSubspace(cdc,
		codec.NewLegacyAmino(),
		storeKey,
		tStoreKey,
		paramstypes.ModuleName,
	)
	ctx := sdk.NewContext(stateStore.CacheMultiStore(), tmproto.Header{}, false, log.NewNopLogger())

	return InMemKeeperParams{
		Cdc:            cdc,
		StoreKey:       storeKey,
		ParamsSubspace: &paramsSubspace,
		Ctx:            ctx,
	}
}
```

**Comment by smarshall-spitzbart** [comment]
Note also that our e2e tests run against full `app.go`s not matter what

**Comment by mpoke** [comment]
This issue should be part of larger EPIC on standardizing QA processes for ICS repo.

**Comment by MSalopek** [comment]
I'm closing this as the amount of work required vs the value created is not satisfactory.

We can revisit this at a later time or make incremental changes to the testing codebase which are much more manageable compared to a full refactor.
