### ISSUE TITLE
General refactor for naming consistency

### ISSUE THREAD

**Issue by jtremback** [cosmos/interchain-security#608]
There are a lot of place where we use different names for things. Examples:
- `vsc` vs `valSetUpdate` vs `valSetChange`
-  "unbonding" vs "undelegation" (or are these different things? lol)

There are probably more I'm missing. Someone just needs to go through and clean everything up.

**Comment by mpoke** [comment]
I'll do it, but let's get a more stable version to not conflict with ongoing work.

**Comment by mpoke** [comment]
https://github.com/cosmos/interchain-security/issues/535 is related

**Comment by mpoke** [comment]
Closing as not needed.
