### ISSUE TITLE
Error-prone storage of throttled packet data

### ISSUE THREAD

**Issue by smarshall-spitzbart** [cosmos/interchain-security#609]
# Problem

We currently store throttled slash and vsc matured packet data in the same chain-specific queue. These types are serialized by a [byte enum](https://github.com/cosmos/interchain-security/blob/ae66785c4f92c26471fb22e97f8348db057f4048/x/ccv/provider/keeper/throttle.go#L225). This is error prone. 

# Closing criteria

Improve how we serialize that data. See if there's any built-in protobuf metadata we can use to infer the type of value bytes that are being deserialized [here](https://github.com/cosmos/interchain-security/blob/ae66785c4f92c26471fb22e97f8348db057f4048/x/ccv/provider/keeper/throttle.go#L321)

# Problem details

This is related to https://github.com/cosmos/interchain-security/issues/567, but that issue is focused on JSON ser/deser from IBC core, whereas this issue deals with how the packet data types are persisted in the provider store during the throttling process.

**Comment by smarshall-spitzbart** [comment]
in `ccv.proto` there is a `ConsumerPacketData` type, introduced by https://github.com/cosmos/interchain-security/pull/626. When this type starts getting used in throttling code, we should consider refactoring it's name to not include "consumer"

Ie. it's confusing to be handling something that is "consumer data" in the provider store. Something like "packet data from consumer" would be easier to understand for quick readers

**Comment by danwt** [comment]
Related: we could refactor all our enums to start from iota + 1, this avoids us accidentally having an uninitiliased enum masquerade as the zeroth enum value

**Comment by smarshall-spitzbart** [comment]
Implicitly closed by deleting all this shiz in #1102
