### ISSUE TITLE
Potential bug regarding which cons addr is used for slashing

### ISSUE THREAD

**Issue by smarshall-spitzbart** [cosmos/interchain-security#610]
# Problem

Upon recv a slash packet on provider, we [map the consumer cons addr to the provider's cons addr](https://github.com/cosmos/interchain-security/blob/ae66785c4f92c26471fb22e97f8348db057f4048/x/ccv/provider/keeper/relay.go#L261). This `providerConsAddr` is used both in the global and chain-specific queue. It's possible that a validator could re-map their keys after a slash packet has been queued for them, but before the slash packet has been handled. This could cause unexpected/undesirable behavior.

# Closing criteria

I believe this issue can be solved by calling `GetProviderAddrFromConsumerAddr` during `HandleThrottleQueues` and `HandleSlashPacket` respectively, instead of mapping the address too early in `OnRecvSlashPacket`.

EDIT: https://github.com/cosmos/interchain-security/issues/610#issuecomment-1360240134

# Problem details

The (possibly outdated) provider cons addr is used [here](https://github.com/cosmos/interchain-security/blob/ae66785c4f92c26471fb22e97f8348db057f4048/x/ccv/provider/keeper/throttle.go#L33) when val power is subtracted from the slash meter, and [here](https://github.com/cosmos/interchain-security/blob/ae66785c4f92c26471fb22e97f8348db057f4048/x/ccv/provider/keeper/relay.go#L310) when handling the slash packet.

I'm not completely sure when/how old addresses are pruned, and which address you'd want to use for slashing in the event that a validator re-maps their key after a slash packet is queued for them, before that packet is handled. @danwt @mpoke, is it more correct to map the address from the consumer right away? Or closest to where the address is actually used (end block)?

**Comment by mpoke** [comment]
I don't think there's an issue here. The keys are pruned once the corresponding `VSCMaturedPackets` are handled. The reason the keys can be pruned is that no other `SlashPackets` for those keys would be accepted afterwards. As `SlashPackets` and `VSCMaturedPackets` are handled in order, it's okay to do the mapping once the `SlashPackets` are added to the queue. The mapping would be the same if done when the  `SlashPackets` are handled. 

A test to check this would be interesting though.

**Comment by smarshall-spitzbart** [comment]
Nice explanation, this issue then becomes _make a small e2e test confirming the above expected behavior_

**Comment by danwt** [comment]
The reverse mapping consumer key -> provider key is kept by Key Assignment for slashing purposes until it is certain that the consumer key will never be seen again. I don't think there's a bug here and I think it's already sufficiently tested.
