### ISSUE TITLE
Roadmap is outdated

### ISSUE THREAD

**Issue by mpoke** [cosmos/interchain-security#617]
# Problem

The roadmap was last updated on June 20th, 2022 

# Closing criteria

Update roadmap with plan for 2023. 

# TODOs
- [x] Labels have been added for issue
- [x] Issue has been added to the ICS project

**Comment by smarshall-spitzbart** [comment]
Imo this issue can be superseded by #695, where we can include a roadmap and/or future work section

**Comment by mpoke** [comment]
Sure, we can link to the roadmap from the docs page. But the issue is that the roadmap is outdated. See https://github.com/cosmos/interchain-security/blob/main/docs/ROADMAP.md
