### ISSUE TITLE
Rewrite some of legacy integration tests

### ISSUE THREAD

**Issue by shaspitz** [cosmos/interchain-security#629]
**EDIT**: e2e tests were renamed to integration tests 

# Problem

A lot of our current integration tests were migrated over in PRs similar to https://github.com/cosmos/interchain-security/pull/297, which tried to clean up testing conventions without changing functionality. The original tests were written in various non-standardized ways, in various files, and may be testing outdated functionality. Some of these testing pitfalls are still present in `main`, and we need to fix this where applicable.

# Closing criteria

All tests (legacy integration tests especially), are relevant to the current implementation of the ccv protocol, and have clear intention of what functionality is actually being tested. 

# Problem details

Here is an [example](https://github.com/cosmos/interchain-security/blob/0c62722c4c8ac138ff795a9b09f9125da3ed2bd7/tests/e2e/slashing.go#L380) of an integration test in which the functionality being tested is outdated? @mpoke created a more up-to-date test that fails. See https://github.com/cosmos/interchain-security/commit/5928146642857ff4bfc73db115c00ededcf61928

**Comment by smarshall-spitzbart** [comment]
Regarding lessons for the future:

Standardizing test conventions, intention, organization, etc. should be the first thing we prioritize for a new repo! Test standardization should not be an afterthought that is prioritized half way through implementing a protocol.
