### ISSUE TITLE
Upgrade to SDK v0.47

### ISSUE THREAD

**Issue by mpoke** [cosmos/interchain-security#63]
- [x] ICS changes are part of SDK v0.47

**Comment by mpoke** [comment]
We should create different releases (tags) for the two versions of SDK.

**Comment by marbar3778** [comment]
id just go with 0.46. There isn't a need to duplicate work. I can pick this up after 0.46 is released

**Comment by mpoke** [comment]
ref. https://github.com/cosmos/cosmos-sdk/issues/12893

**Comment by mmulji-ic** [comment]
@marbar3778 @mpoke This will be bumped this to 0.47, so title should be changed.

**Comment by mpoke** [comment]
Fixed, see https://github.com/cosmos/cosmos-sdk/issues/12893#issuecomment-1272508967
