### ISSUE TITLE
Fix flaking integration tests

### ISSUE THREAD

**Issue by danwt** [cosmos/interchain-security#631]
# Problem

The current integration tests are flaky

# Closing criteria

Make them not flaky

# Problem details

See 

https://github.com/cosmos/interchain-security/actions/runs/3749048773/jobs/6367083292

for an example run.

Additional context (credit @MSalopek @mpoke @jtremback )

> Any time you push them past 2 containers that will happen

> It's a timing issue. There's no way around it besides running them in series

> Re-running the test usually solves it. Bear in mind that multichain tests are not running in the pipeline any longer due to the same issues you are experiencing now

> When I played with tests last week, one thing was apparent - block times are not very consistent, they can vary from 1-2s to anywhere around 20s. We have some actions that wait for a number of blocks to be produced - these often fail due to wait timeouts being reached (not enough blocks produced in specified window, usually 1 minute).

> We should have a chat with the Tendermint team and see how they do it. 

# TODOs
- [x] Labels have been added for issue
- [x] Issue has been added to the ICS project

**Comment by MSalopek** [comment]
Initial idea Id like to test out is running only happy path tests on push to PR -> this reduces pipeline run times while giving us enough coverage during development iterations.

Full integration tests can be run in series after merge. There are [merge queues in GH](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue) but they are somewhat experimental.

The desired behaviour can be used by creating custom github actions, either community contributed or our own. There should be plenty of examples.

**Comment by mpoke** [comment]
Another option is to adopted the approach used by the TM team: run most of the integrations tests over the night on the main branch. If something fails, we investigate and if necessary, either push a fix or revert the problematic PR.
