### ISSUE TITLE
`ValidateBasic` is not called when receiving packets from consumers

### ISSUE THREAD

**Issue by mpoke** [cosmos/interchain-security#634]
# Problem

When receiving packets from a consumer chain, the provider doesn't validate them (by calling `ValidateBasic`, for [VSCMaturedPacketData](https://github.com/cosmos/interchain-security/blob/0c62722c4c8ac138ff795a9b09f9125da3ed2bd7/x/ccv/types/ccv.go#L42) and [SlashPacketData](https://github.com/cosmos/interchain-security/blob/0c62722c4c8ac138ff795a9b09f9125da3ed2bd7/x/ccv/types/ccv.go#L62)), i.e., https://github.com/cosmos/interchain-security/blob/0c62722c4c8ac138ff795a9b09f9125da3ed2bd7/x/ccv/provider/ibc_module.go#L184 

Related to https://github.com/cosmos/interchain-security/issues/544

# Closing criteria

`ValidateBasic` is called in `OnRecvPacket`.

# TODOs
- [x] Labels have been added for issue
- [x] Issue has been added to the ICS project

**Comment by sainoe** [comment]
I think that https://github.com/cosmos/interchain-security/issues/609 should be solved beforehand since it entails renaming the consumer packet type in `ccv.proto`.

**Comment by mpoke** [comment]
Fixed by https://github.com/cosmos/interchain-security/pull/1460
