### ISSUE TITLE
Validate key assignment state in provider genesis

### ISSUE THREAD

**Issue by danwt** [cosmos/interchain-security#645]
# Problem

The key assignment related state in provider::Genesis is not fully validated

# Closing criteria

Amend `func (gs GenesisState) Validate()` to validate the data, checking that all []byte types are correct ect.

# TODOs
- [x] Labels have been added for issue
- [x] Issue has been added to the ICS project

**Comment by danwt** [comment]
See https://github.com/cosmos/interchain-security/pull/642/files for hanging TODOs in the code

**Comment by smarshall-spitzbart** [comment]
@danwt @mpoke should this issue be closed now that #646 and #642 are merged? We can keep this open if there's any outstanding validation we'll need

**Comment by danwt** [comment]
Yes thanks @smarshall-spitzbart !
