### ISSUE TITLE
Duplicate key assignment by the same validator

### ISSUE THREAD

**Issue by ivan-gavran** [cosmos/interchain-security#648]
Surfaced from https://github.com/informalsystems audit of the [key assignment](https://github.com/cosmos/interchain-security/pull/515/files) feature of interchain security.

# Problem

If a validator tries to assign a key which already exists for the consumer chain, we return an error of type `ErrConsumerKeyInUse` (the check is [here](https://github.com/cosmos/interchain-security/blob/ba3316d266a419314c44de62a0595edccfb11c3a/x/ccv/provider/keeper/key_assignment.go#L371)).

However, what happens if the same validator tries to assign the key it had already assigned before? (For whatever reason, maybe mistakenly or because it was not sure whether the previous request has gone through.) We still return the same error.

Would it make sense to disambiguate between the two cases and for the second case not return an error? (So that the validator knows that its intention--to have the key assigned for the consumer chain--succeeded).

**Comment by danwt** [comment]
Thanks, it will return an error in this case but we are considering this a very minor UX problem, not a security problem.

**Comment by danwt** [comment]
Labelling as wontfix and closing. The returned message is `a validator has assigned the consumer key already` which is not wrong
