### ISSUE TITLE
Potential bug in e2e test setup

### ISSUE THREAD

**Issue by smarshall-spitzbart** [cosmos/interchain-security#661]
# Problem

Neutron is experiencing an issue running the ICS e2e tests. The tests compile for their app, but then panic upon an unexpected IBC error. 

# Closing criteria

Find a fix that allows Neutron's tests to pass, or do enough debugging to find that the issue is within another repo.

# Problem details

After some debugging, the panic is being hit by [this caller](https://github.com/cosmos/interchain-security/blob/7ddcf8710d99654d1d5c2aba1fc061887a7c37f4/tests/e2e/setup.go#L220). Unfortunately IBC-go panic logs are not that useful.

See neutron branch for bumping ICS ver: https://github.com/neutron-org/neutron/tree/chore/bump-deps

and specifically the failing test: https://github.com/neutron-org/neutron/blob/a507cb99596a5056f10e67219669ff7d545d4655/tests/e2e/interchain_security_test.go#L17

Here's a quick change you can make to their `TestCCVTestSuite` to have it run a single e2e test and only spit out one panic error
```golang
func TestCCVTestSuite(t *testing.T) {
	// Pass in concrete app types that implement the interfaces defined in /testutil/e2e/interfaces.go
	ccvSuite := e2e.NewCCVTestSuite[*appProvider.App, *appConsumer.App](
		// Pass in ibctesting.AppIniters for provider and consumer.
		icssimapp.ProviderAppIniter, testutil.SetupTestingApp, []string{})

	// Run tests
	ccvSuite.SetT(t)
	ccvSuite.SetupTest()
	ccvSuite.TestHandleSlashPacketDoubleSigning()
}
```

produces: 
```
--- FAIL: TestCCVTestSuite (0.06s)
        	Error:      	Received unexpected error:
        	            	signature verification failed; please verify account number (1) and chain-id (testchain3): unauthorized
        	Test:       	TestCCVTestSuite
FAIL
FAIL	github.com/neutron-org/neutron/tests/e2e	0.527s
FAIL

```

**Comment by smarshall-spitzbart** [comment]
Related: we should consider adding a test to the ICS repo that points to a consumer implementation such as Neutron. It's possible there's something different between production consumer implementations, and our dummy consumer app that causes this issue.

See [gaia test](https://github.com/cosmos/interchain-security/blob/463ec20c87423897009bd78c2dbf96d28bd8f150/tests/e2e/instance_test.go#L60) to pattern match how we currently run e2e tests against the gaia provider implementation

**Comment by smarshall-spitzbart** [comment]
At the very least, we should improve panic logging for e2e setup issues like this. The ibctesting panics can be pretty opaque

**Comment by smarshall-spitzbart** [comment]
Update: https://github.com/neutron-org/neutron/pull/122 seemed to fix the issue for Neutron, but not for duality.

@sainoe @stana-ethernal, could you provide anymore context on #151

**Comment by sainoe** [comment]
https://github.com/duality-labs/duality/pull/284 solved the issue for duality as well
