### ISSUE TITLE
Potential dead code

### ISSUE THREAD

**Issue by ivan-gavran** [cosmos/interchain-security#671]
# Problem

There is a function [`NewHandler`](https://github.com/cosmos/interchain-security/blob/v1.0.0-rc1/x/ccv/provider/handler.go#L10) that seems not to be used at all. It is supposed to call the function `AssignConsumerKey` upon receiving the corresponding message.
From a preliminary discussion with @MSalopek , the same functionality is accomplished with [`tx.pb.go`](https://github.com/cosmos/interchain-security/blob/v1.0.0-rc1/x/ccv/provider/types/tx.pb.go) and [`codec.go`](https://github.com/cosmos/interchain-security/blob/v1.0.0-rc1/x/ccv/provider/types/key_assignment.go), and it seems that `NewHandler` is indeed not needed.

# TODOs
- [ ] Labels have been added for issue
- [ ] Issue has been added to the ICS project

**Comment by MSalopek** [comment]
The [NewHandler](https://github.com/cosmos/interchain-security/blob/v1.0.0-rc1/x/ccv/provider/handler.go#L10) is ineed unused. The message handler is registered elsewhere and this will be removed as part of ICS v1.1

**Comment by mpoke** [comment]
Fixed by https://github.com/cosmos/interchain-security/tree/feat/upgrade-ics-sdk47-ibc7
