### ISSUE TITLE
Add consumer chain timeout e2e/integration tests

### ISSUE THREAD

**Issue by MSalopek** [cosmos/interchain-security#674]
# Problem

Continuation of #361.

We should add a scenario that tests consumer timeouts and subsequent cleanup operations.

# Closing criteria
Scenario is added to `tests/integration`

# TODOs
- [x] Labels have been added for issue
- [ ] Issue has been added to the ICS project

**Comment by mpoke** [comment]
@p-offtermatt How easy is to add this with CometMock?

**Comment by p-offtermatt** [comment]
It should be very easy. The timeout part is trivial, knowing what to test with respect to cleanup is the part that I have uncertainty about.

**Comment by MSalopek** [comment]
This was tested using cometmock.
