### ISSUE TITLE
Fork modified cosmos-sdk modules and add them to this repo

### ISSUE THREAD

**Issue by mpoke** [cosmos/interchain-security#68]
Currently, the Interchain Security branch is https://github.com/cosmos/cosmos-sdk/tree/interchain-security-rebase

Update: https://github.com/cosmos/interchain-security/issues/68#issuecomment-1125976598

Dependencies:
- [ ] Merge https://github.com/cosmos/cosmos-sdk/pull/11921

**Comment by mpoke** [comment]
After discussions within the team, we decided to not merge the Cosmos SDK changes to the master branch, but rather fork the relevant Cosmos SDK modules and add them directly to the interchain-security repo, similarly to https://github.com/iqlusioninc/liquidity-staking-module/tree/master/x

**Comment by mpoke** [comment]
@okwme What is the latest view on this issue? What's the preferred way to go about it? 

1.  Keep own branch on cosmos-sdk, i.e., https://github.com/cosmos/cosmos-sdk/tree/interchain-security-rebase.
2. Move the relevant SDK modules to the interchain-security repo.
3. Merge the changes to the main SDK branch.

**Comment by jtremback** [comment]
This is settled, right @mpoke. Reopen if not.

**Comment by mpoke** [comment]
Yes. The SDK changes need by IS will be merge to the main SDK branch and eventually be part of a new SDK release (e.g., 0.47). See https://github.com/cosmos/cosmos-sdk/pull/13122
