### ISSUE TITLE
Add documentation explaining differences between consumer and democ consumer

### ISSUE THREAD

**Issue by shaspitz** [cosmos/interchain-security#680]
# Problem

There is not much written documentation (or code comments) explaining the difference between a consumer and democracy consumer. We should answer the following questions: 
- Why does the democracy consumer app have a staking keeper? AFAIK for a normal consumer, the consumer CCV keeper acts as the staking keeper
- Why do we maintain apps for both a normal consumer and democracy consumer? This is not intuitive from reading code

# Closing criteria

Add a markdown explaining the relevant differences in implementation and functional behavior. Sufficient code comments could also suffice.

**Comment by mpoke** [comment]
Closing as the current docs are covering the democracy modules.
