### ISSUE TITLE
Consumer addition proposal followed by consumer removal proposal: the chain not removed if not careful with proposal params

### ISSUE THREAD

**Issue by ivan-gavran** [cosmos/interchain-security#686]
Assume there is a proposal that adds a consumer chain `C`, with spawn time `prop1.spawnTime`, and the proposal has passed the vote.
  Afterwards, a new proposal which removes `C` at time `prop2.stopTime` was submitted and passed.
  If `prop2.stopTime < prop1.spawnTime` (which is a conceivable mistake by proposers who want to stop the chain as soon as possible), then the stopping of the chain will be executed first, and it will fail with an error (because the chain that needs to be stopped will not be found). The consequence will be that the chain `C` will happily start at `prop1.spawnTime`.

This is obviously a user's (proposer's) mistake, but one that is easy to make so maybe it makes sense to consider this scenario

**Comment by mpoke** [comment]
@ivan-gavran Thanks for pointing this out. I see this as a non issue as it's quite obvious that the stopTime should be after the spawnTime.
