### ISSUE TITLE
Cosmos-SDK: Implement simapp fuzzing for new addition to Cosmos SDK

### ISSUE THREAD

**Issue by mpoke** [cosmos/interchain-security#69]

**Comment by mpoke** [comment]
@sainoe @okwme @alexanderbez Do we still need this if we do not merge our SDK changes to the master branch of cosmos-sdk? We decided to go with the approach described in https://github.com/cosmos/interchain-security/issues/68

**Comment by jtremback** [comment]
@danwt Can you weigh in on how much the simapp fuzzing would improve coverage over what our diff tests do now? If it's not going to be an improvement and the SDK team doesn't require it, we can close this.

**Comment by danwt** [comment]
I will look again at the existing simapp uses for other modules. I would be surprised if it would help us.

**Comment by danwt** [comment]
It would take some effort anyway so even if simapp fuzzing is useful (which it might be), it would have to be more useful for us than other work to justify it (doubtful).
