### ISSUE TITLE
diff-test core: improve tests to use cryptolib

### ISSUE THREAD

**Issue by sainoe** [cosmos/interchain-security#691]
# Problem

The diff testing setup creates validator consensus and operator addresses using the same pubkey. 

# Closing criteria
- Update the diff tests to use [cryptolib](https://github.com/cosmos/interchain-security/blob/main/testutil/crypto/crypto.go)
- Reformat the diff tests to work when validators' consensus and operator address are differentiated

# TODOs
- [x] Labels have been added for the issue
- [x] Issue has been added to the ICS project

**Comment by p-offtermatt** [comment]
Closing since difftest model was deprecated in favor of MBT
