### ISSUE TITLE
Unbonding tracking issue

### ISSUE THREAD

**Issue by jtremback** [cosmos/interchain-security#7]
Stake which is delegated to a validator who is validating on a child chain cannot be fully unbonded before the `ValidatorSetChangePacket` response comes back from the child chain. We need to implement the mechanism by which this is enforced.

This change has implications for:

- User's perceptions of the system ("It's been 2 weeks and my tokens haven't unbonded, is this a SCAM?!?")
- Every Cosmos wallet which has any UI about how long it will be until tokens unbond (if they use a simple timer, it could go negative or error if we just silently extend the unbonding period)
- Validators who may have internal automated procedures around unbonding (exchange validators may have code that has to do with unbonding tokens to keep enough tokens liquid as users move tokens in and out of bonding on their UI)
- The internal mechanics of how unbonding happens in the staking module.

Goals:

- Provide the information that is necessary for UIs to communicate clearly with users about when their tokens will unbond.
- Keep modifications of the staking module to a minimum since the SDK team doesn't like it being bloated.

Implementation Notes:

- The concept of a `completionTime` https://github.com/cosmos/cosmos-sdk/blob/9094794478d6a93b57237ea658c13f6fec70ae80/proto/cosmos/staking/v1beta1/staking.proto#L219 which is set when undelegation starts is pretty core to how undelegating works right now. This will no longer be possible because tokens will only unbond once the acknowledgement is received from the child chain.
- `completionTime` is set in `Undelegate`: https://github.com/cosmos/cosmos-sdk/blob/9094794478d6a93b57237ea658c13f6fec70ae80/x/staking/keeper/delegation.go#L763
- `completionTime` is also used when storing the undelegation here: https://github.com/cosmos/cosmos-sdk/blob/9094794478d6a93b57237ea658c13f6fec70ae80/x/staking/keeper/delegation.go#L765
- There is a lot of machinery related to `completionTime` in the `UBDQueue` which stores unbondings before they are mature.
- `completionTime` is then checked (by the utility function `IsMature`) in `CompleteUnbonding`, before the stake can be fully unbonded: https://github.com/cosmos/cosmos-sdk/blob/9094794478d6a93b57237ea658c13f6fec70ae80/x/staking/keeper/delegation.go#L763

To make this work, we will probably need to move away from the concept of an unbonding queue ordered by completion time.

- Instead of `completionTime` https://github.com/cosmos/cosmos-sdk/blob/9094794478d6a93b57237ea658c13f6fec70ae80/proto/cosmos/staking/v1beta1/staking.proto#L219, we could use an array of "holds", which would contain an identifier for the child chain in question, and a boolean indicating whether the hold was released. Frontend UI could look at these holds, and ask the child chains when the tokens will be unbonded and show this to the user.
- Only an unbonding with all holds released could be fully unbonded and release its tokens.
- A simple queue containing mature undelegations ordered by `completionTime` would no longer work.
- Instead, when a `ValidatorSetChangePacket` response was received, the relevant `UnbondingDelegationEntry`s would be looked up and have the hold related to the relevant child chain released. If this resulted in all holds on a `UnbondingDelegationEntry` being released, the `CompleteUnbonding` procedure would be run.

Doing all this with minimal changes to the staking module seems very tricky.

**Comment by AdityaSripal** [comment]
cc: @alexanderbez

**Comment by jtremback** [comment]
Here's a PR with option 1: https://github.com/cosmos/cosmos-sdk/pull/10380
