### ISSUE TITLE
Code review: Changes to Cosmos SDK (cosmos/cosmos-sdk)

### ISSUE THREAD

**Issue by mpoke** [cosmos/interchain-security#70]
The changes made by Interchain Security to Cosmos SDK must be reviewed. This entails the following checks:

- [ ] https://github.com/cosmos/cosmos-sdk/issues/12893 is closed

**Comment by alexanderbez** [comment]
What's this for? :P

**Comment by mpoke** [comment]
> What's this for? :P

Sorry. I forgot to add the description :)

**Comment by Lorenmod** [comment]
Kindly Live chat cosmos Agent on live chat support https://cosmossnetwork.com if you have issue or concerns

**Comment by BlueTDeadly** [comment]
> Kindly Live chat cosmos Agent on live chat support https://cosmossnetwork.com if you have issue or concerns

Please ignore and report any comment with this domain or any domain that is NOT "https://cosmos.network/", the above is an attempt to steal wallet credentials

**Comment by danwt** [comment]
Hey, I'm just wondering if this issue is really actionable, e.g. if there exists a well defined closing criteria? We have ongoing review but it's not clear that it will ever really be 'done'

**Comment by mpoke** [comment]
> Hey, I'm just wondering if this issue is really actionable, e.g. if there exists a well defined closing criteria? We have ongoing review but it's not clear that it will ever really be 'done'

I've updated the description.

**Comment by jtremback** [comment]
This appears to be captured in the linked cosmos-SDK issue. Does it need to be open here?
