### ISSUE TITLE
Slashing/jailing naming refactors are needed

### ISSUE THREAD

**Issue by shaspitz** [cosmos/interchain-security#706]
# Problem

Last minute changes like https://github.com/cosmos/interchain-security/pull/692 have made a lot of the semantics around slashing/jailing outdated. We should revisit these naming semantics once the future plans for slashing, untrusted consumers, etc. are more ironed out.

# Closing criteria

Naming semantics around slashing/jailing are properly refactored.

# Problem details

- `HandleSlashPacket` now only handles downtime packets, and mainly just jails a validator. It could be renamed to `HandleDowntimeSlashPacket`, `JailFromDowntimePacket`, etc.. something that can now be more descriptive
- `SlashMeter` is really a "jail meter". We're limiting validator jailings over time, not slashing
- `SlashPackets` are no longer used to enforce slashing, they're used to either log, or jail. `InfractionPacket` could be appropriate here
- These are just examples, there might be more refactors needed

**Comment by mpoke** [comment]
Closing as the refactor would involve API breaking changes.
