### ISSUE TITLE
Code review: Using ibc-go (cosmos/interchain-security)

### ISSUE THREAD

**Issue by mpoke** [cosmos/interchain-security#71]
- [x] ibc-go team needs to review the code from an IBC perspective

**Comment by danwt** [comment]
Ditto comment about closing criteria for issues (see https://github.com/cosmos/interchain-security/issues/70#issuecomment-1234230530)

**Comment by mpoke** [comment]
Outcome of code review:
- https://github.com/cosmos/interchain-security/issues/716
- https://github.com/cosmos/interchain-security/issues/718
- https://github.com/cosmos/interchain-security/issues/719
- https://github.com/cosmos/interchain-security/issues/720
- https://github.com/cosmos/interchain-security/issues/721
- https://github.com/cosmos/interchain-security/issues/722
- https://github.com/cosmos/interchain-security/issues/726
