### ISSUE TITLE
Height <-> ValsetUpdateID mapping is inefficient

### ISSUE THREAD

**Issue by AdityaSripal** [cosmos/interchain-security#718]
At the moment, we save a mapping to valset updateID at every height. This is a new key added every block even if the valset hasn't changed.

We can instead only store the mapping on the height at which the valset is updated.

We can still recover the relevant valsetUpdateID for a given infraction height by using iterators.

Not necessary for first release perhaps, but this is a clear optimization that may prove necessary later on

**Comment by mpoke** [comment]
Putting this issue on hold as epochs would solve the problem.

**Comment by mpoke** [comment]
Solved by the introduction of epochs.
