### ISSUE TITLE
Code review: CCV module (cosmos/interchain-security)

### ISSUE THREAD

**Issue by mpoke** [cosmos/interchain-security#72]

**Comment by danwt** [comment]
Ditto comment about closing criteria for issues (see https://github.com/cosmos/interchain-security/issues/70#issuecomment-1234230530)

**Comment by jtremback** [comment]
Closing this one based on Dan's comment about closing criteria. I myself have recently done another code review, but I'm not sure if it qualifies for this issue. @mpoke reopen this if there are specific people who need to do this, or criteria that needs to be met.
