### ISSUE TITLE
Packet Maturity Time Mapping in the consumer chain is redundant. Storing `time/id -> {time, id}`

### ISSUE THREAD

**Issue by AdityaSripal** [cosmos/interchain-security#721]
All of the information stored in the value is recoverable from the key itself, so there is redundant information being stored. We could just store a sentinel byte value and still have the same information in the store.

https://github.com/cosmos/interchain-security/blob/463ec20c87423897009bd78c2dbf96d28bd8f150/x/ccv/consumer/keeper/keeper.go#L267

**Comment by mpoke** [comment]
@AdityaSripal We want to move away from the pattern of parsing keys to retrieve data as it was a source of bugs in the past. The new pattern should be key -> value, where the key is a unique string and the value is a protobuf that contains all the necessary data. 

In this particular case, the key is never needed as the packet maturity time mapping is only used in an iterator.
