### ISSUE TITLE
ApplyValidatorSetChanges improvement

### ISSUE THREAD

**Issue by AdityaSripal** [cosmos/interchain-security#722]
Seems to me like this function is taking the changes, adding them to a list and then returning the new list. This seems unnecessary to me, when we can just use the passed-in changes directly

https://github.com/cosmos/interchain-security/blob/463ec20c87423897009bd78c2dbf96d28bd8f150/x/ccv/consumer/keeper/validators.go#L16

**Comment by mpoke** [comment]
@AdityaSripal This approach is needed to deal with an edge case, see https://github.com/cosmos/interchain-security/blob/463ec20c87423897009bd78c2dbf96d28bd8f150/x/ccv/consumer/keeper/validators.go#L53
