### ISSUE TITLE
OutOfBlockGas handling

### ISSUE THREAD

**Issue by AdityaSripal** [cosmos/interchain-security#726]
The new CCV modules introduces a lot of logic to be handled in the BeginBlock and Endblock. This could end up consuming a large amount of the block gas limit which may leave no space for transactions or even worse, the beginblock/endblock alone may consume all the gas in the block which I believe will cause a panic and crash the chain

I think there should be some stress testing with many consumer chains to see how much a provider chain can comfortably handle.

If the per-block logic is indeed very expensive relative to the block gas limit, then we need to prioritize making optimizations and even queueing the logic so that not everything must run in the block but can be dequeued as the remaining block gas allows.

**Comment by mpoke** [comment]
@AdityaSripal do BeginBlock and EndBlock consume the block gas limit?

**Comment by AdityaSripal** [comment]
Turns out they do not, closing issue as hitting gas limit is no longer a risk
