### ISSUE TITLE
SlashAcks should not be persisted as string

### ISSUE THREAD

**Issue by smarshall-spitzbart** [cosmos/interchain-security#728]
# Problem

A "slash ack" is a string which is relayed between provider and consumer to reset the consumer's outstanding downtime flag. SlashAcks are *always* consumer consensus addresses, but we persist and send these slash acks as a string type. This design is error prone because:
1. It does not leverage type safety (see https://github.com/cosmos/interchain-security/issues/693)
2. There are multiple formats to convert a consensus address to string

# Closing criteria

Make slash acks persisted and ser/deser as pb types, not strings

# Problem details

A fix to this issue should be built on top of https://github.com/cosmos/interchain-security/pull/725. Since slash acks can be persisted as consumer cons address pb types

**Comment by smarshall-spitzbart** [comment]
Note: this will likely take a state migration so I'm going push it off for a future ICS version

**Comment by smarshall-spitzbart** [comment]
@yaruwangway, now that #725 is merged, this issue is able to be solved if you're interested! Lmk if you want more options for a first issue

**Comment by ameya-deshmukh** [comment]
Hi @smarshall-spitzbart is this still available?

**Comment by smarshall-spitzbart** [comment]
> Hi @smarshall-spitzbart is this still available?

@ameya-deshmukh sorry for the late response! Yes this issue is still open and noone is currently working on it. Are you interested in contributing?

**Comment by MSalopek** [comment]
The issue has become state breaking in the meantime.
Any changes in those parts will require a state migration, I'm not sure how feasible this is.

**Comment by smarshall-spitzbart** [comment]
A solution doesn't have to be state breaking, but it would naturally have to break the wire. Solution could be implemented in such a way that it is backwards compatible tho.

Now that ICS is in production I agree that this issue is most likely not feasible. Unfortunately it is a source of technical debt.

@yaruwangway it seems we could close this issue by simply making the API for `AppendSlashAck`, `GetSlashAcks`, `SetSlashAcks` type safe, and remove the TODOs. The wire can keep string types to avoid complications
