### ISSUE TITLE
Don't allow slash proposal without corresponding slash packet

### ISSUE THREAD

**Issue by jtremback** [cosmos/interchain-security#729]
# Problem

The changes in `ADR 003: Equivocation governance proposal` make it so that double signing packets do not automatically slash validators when they are received. Instead, a governance proposal must be made first. To avoid the possibility of people creating spam slash proposals when no slash packets have been received, it would be good to add a check to the equivocation proposal to see if there have been any slash packets received for that validator during the unbonding period.

# Closing criteria

Close this issue once the feature described below has been implemented.

# Problem details

We would like to prevent slash proposals from being submitted for validators who have never received a slash packet from a consumer chain. This is not a security issue, it is just to prevent spam proposals. The design below does not save the time a slash packet was received. This means that it could be possible for a validator to double sign on a consumer chain and not be punished until long after the unbonding period was over. This could be prevented with extra complexity, but it is acceptable. This design uses a data structure which is not pruned. This means that it will slowly take up space if many slash packets are received. But slash packets are a rare event, so this is not a concern, and anyway it costs gas to relay them.

### Design

In `OnRecvSlashPacket` when a double sign packet is received, we should add a call to a setter `SetSlashLog(ctx, providerConsAddr)`. This setter will write to a `SlashLog` index in the store of `providerConsAddr->bool`.

In `HandleEquivocationProposal`, for each equivocation, we should call a getter `GetSlashLog(ctx, consAddr)`, returning a boolean indicating whether any slash packet for that validator was received. If no slash packet was received for the validator, then the proposal should error. Since proposals are run in a cached context when they are submitted, and are not saved if they fail, this will prevent proposals from being submitted which did not receive a corresponding slash packet.

Write tests for this functionality, checking that if no slash packet was received for a validator, it is impossible for a slash proposal to be created for that validator.

**Comment by sainoe** [comment]
As an implementation detail, I suggest just storing a `SlashLog` flag for a given `providerConsAddr` like `SetOutstandingDowntime` in the consumer, see:

https://github.com/cosmos/interchain-security/blob/5563395cb5a11189d1db132e89cebffa8a98c148/x/ccv/consumer/keeper/keeper.go#L374-L378

**Comment by MSalopek** [comment]
PR with specified approach: https://github.com/cosmos/interchain-security/pull/730

Alternative approach:
Have the `SlashLog` contain all reported equivocations for a validator.
```golang
// pseudocode
slashLog = map[validatorAddress][]SlashPacket
```
When submitting the equivocation proposal, check that the submitted slash packet exists in the log.
If a slash packet exists, move on with the proposal, otherwise the drop the proposal.
Additionally, the logic could check that the slash packet is not too old (eg. is within the unbonding period of the provider at the time the proposal is created).

This would more give more flexibility to the system. We could add queries to check the slash log and keep the entire history of double signing reports.
