### ISSUE TITLE
Enable user txs only after CCV channel enabled

### ISSUE THREAD

**Issue by mpoke** [cosmos/interchain-security#74]
For safety, the consumer chain should not enable user transactions until the CCV channel is established. At this point the consumer is secured by the provider. The CCV channel is established on the consumer chain when the first VSC packet is received, see [spec](https://github.com/cosmos/ibc/blob/marius/ccv/spec/app/ics-028-cross-chain-validation/technical_specification.md#ccv-ccf-rcvvsc1).

**Comment by jackzampolin** [comment]
So architecture wise this would be an antehandler that rejects all non-CCV messages prior to a param being flipped?

**Comment by mpoke** [comment]
> So architecture wise this would be an antehandler that rejects all non-CCV messages prior to a param being flipped?

Yes, something like this. I think it shouldn't be too hard to implement, I just don't know where this needs to be done and how to get access to the CCV flag (probably through a ccvKeeper).

**Comment by alexanderbez** [comment]
Assign this to me, I'll knock it out.

**Comment by alexanderbez** [comment]
@mpoke I was going to introduce a new parameter to the `x/ccv/consumer` module, but I noticed there already is a `Enabled` parameter. What is this parameter for? Can we use this parameter for the purposes of this feature?

**Comment by alexanderbez** [comment]
Right, but we need to add a parameter for that. I was going to actually add a `Enabled` or `TxsEnabled` parameter and then I saw `Enabled` so hence my question. It's a bit confusing. So we need to add a 2nd parameter to gate tx flow?

**Comment by sainoe** [comment]
This `Enabled` parameter is set when creating the consumer genesis in the provider chain
https://github.com/cosmos/interchain-security/blob/f95925c2d04ae155d8877efc2115d3791a20a9a3/x/ccv/provider/keeper/proposal.go#L78

And is mandatory in the consumer `InitGenesis` 
https://github.com/cosmos/interchain-security/blob/f95925c2d04ae155d8877efc2115d3791a20a9a3/x/ccv/consumer/keeper/genesis.go#L18-L21 

So I guess we're good to go with a second parameter like `TxsEnabled`
