### ISSUE TITLE
additional equivocation proposal logic is required

### ISSUE THREAD

**Issue by MSalopek** [cosmos/interchain-security#741]
# Problem
When submitting an equivocation proposal the evidence listed in the proposal can become stale.
If the proposal with stale evidence passes the validator will not get slashed because the `HandleEquivocationEvidence` will exit early with no errors.

# Closing criteria

Add validation that will reject the proposal if the evidence can be deemed too old at:
- proposal submission time
- proposal execution time

# Problem details
When submitting evidence in the Equivocation proposal, the `height` must fall within the `Evidence.MaxAgeNumBlocks` and `EvidenceMaxAgeDuration` on both proposal submission and execution - otherwise the slash will not occur.

The [relevant function from cosmosSDK](https://github.com/cosmos/cosmos-sdk/blob/d6c8598683ce1ac8efd39941109eae78b8211ddf/x/evidence/keeper/infraction.go#L26):
```golang
func (k Keeper) HandleEquivocationEvidence(ctx sdk.Context, evidence *types.Equivocation) {
	logger := k.Logger(ctx)
	consAddr := evidence.GetConsensusAddress()

	// calculate the age of the evidence
	infractionHeight := evidence.GetHeight()
	infractionTime := evidence.GetTime()
	ageDuration := ctx.BlockHeader().Time.Sub(infractionTime)
	ageBlocks := ctx.BlockHeader().Height - infractionHeight

	// Reject evidence if the double-sign is too old. Evidence is considered stale
	// if the difference in time and number of blocks is greater than the allowed
	// parameters defined.
	cp := ctx.ConsensusParams()
	if cp != nil && cp.Evidence != nil {
                 // NOTE: this will exit early!
		if ageDuration > cp.Evidence.MaxAgeDuration && ageBlocks > cp.Evidence.MaxAgeNumBlocks {
			logger.Info(
				"ignored equivocation; evidence too old",
				"validator", consAddr,
				"infraction_height", infractionHeight,
				"max_age_num_blocks", cp.Evidence.MaxAgeNumBlocks,
				"infraction_time", infractionTime,
				"max_age_duration", cp.Evidence.MaxAgeDuration,
			)
			return
		}
	}
```

### Possible cases:
1. Evidence is too old at submission -> prop submission tx rejected
2. Evidence is valid at submission but invalid at execution time -> prop tx accepted, proposal can pass voting, validator cannot be slashed
3. Evidence valid at submission and valid at execution time -> prop tx accepted, proposal can pass voting, validator can be slashed

# TODOs
- [ ] Labels have been added for issue
- [ ] Issue has been added to the ICS project

**Comment by tbruyelle** [comment]
If nobody started to work on it, I can do it. Please assign it to me in that case.

**Comment by jtremback** [comment]
I don't think this is worth doing. Instead we should fix the proposal so that it pauses unbondings for the validator, or we should just get cryptographically automatic equivocation slashing working as we've discussed.
