### ISSUE TITLE
Add automation around tagging/semver

### ISSUE THREAD

**Issue by smarshall-spitzbart** [cosmos/interchain-security#748]
# Problem

https://github.com/cosmos/interchain-security/pull/744 adds some basic standards around contributing to ICS. However, there is room for automation of the following tasks:

- Parsing commits in main to obtain a version number for a release (we'd also have to enforce a naming convention in PR titles)
- Automatic backport PRs, similar to how gaia does things
- Dealing with bugfixes to release branches, and how that affects semver on main 

# Closing criteria

The above concerns are addressed with automation solutions. 

# Problem details

See #744 for further context

**Comment by mpoke** [comment]
Closing as fixed. See CONTRIBUTING.md
