### ISSUE TITLE
Remove SPM

### ISSUE THREAD

**Issue by faddat** [cosmos/interchain-security#753]
This repository was scaffolded with starport, which used to have a module called "spm".  

spm is considered harmful because it results in conflicting version imports in many cases.  In the case of the ccv repo, that's almost certainly the case.  We should remove spm from this repository and replace it with the standard cmd folder layout.

**Comment by faddat** [comment]
Hey there, bump, this is done

**Comment by robert-zaremba** [comment]
Yeah, just learned about SPM. I think the repo was basically copied from a template, rather than using the latest version of ignite CLI.
