### ISSUE TITLE
Enable query from provider to return correct genesis state for sovereign to consumer changeover chains 

### ISSUE THREAD

**Issue by smarshall-spitzbart** [cosmos/interchain-security#789]
As of #757, where all changes only affect consumers, a sovereign to consumer changeover chain will have to query the provider for a genesis state, manually change that genesis JSON before it is used on consumer, then the consumer reads that file. See [this code](https://github.com/cosmos/interchain-security/blob/3651164344c61392ff5d9edb8689c78034a549d9/app/consumer-democracy/app.go#L647).

A future improvement to ICS could introduce a change that affects the provider (MAJOR version bump), s.t there's a provider query returning a properly crafted sovereign to consumer genesis state with more devops automation

**Comment by mpoke** [comment]
Closing in favor of https://github.com/cosmos/interchain-security/issues/894
