### ISSUE TITLE
Fix broken integration test(s) at 80d146a

### ISSUE THREAD

**Issue by jtremback** [cosmos/interchain-security#79]
Currently, the integration tests are failing because the distribution module beginblocker is crashing, because the distribution module needs to be disabled on consumer chains. This would be permanently solved by https://github.com/cosmos/interchain-security/issues/77, but it should also be possible to solve it temporarily by taking the distribution module beginblocker out of the beginblocker order in the exposed module manager (@rigelrozanski can maybe explain how to do this)

**Comment by mpoke** [comment]
Will be solved by #77.

**Comment by mpoke** [comment]
Related to https://github.com/cosmos/interchain-security/pull/98

**Comment by mpoke** [comment]
See https://github.com/cosmos/interchain-security/pull/98#issuecomment-1126571424

**Comment by sainoe** [comment]
Solved by #139 however the integration tests are still failing due to the [states checker](https://github.com/cosmos/interchain-security/blob/9f15cc7adb5d46717fea0ffe9a175441a8826d51/integration-tests/main.go#L60).
The error can be reproduced using this WIP [MVCC branch](https://github.com/cosmos/interchain-security/tree/sainoe/mvcc-disable-modules-B).
@danwt

**Comment by danwt** [comment]
The query problem in the previous comment seems to be fixed in 

https://github.com/cosmos/interchain-security/tree/sainoe/mvcc-integration-tests-fix

but now I'm getting

```bash
main.AddIbcChannelAction{chainA:0x1, chainB:0x0, connectionA:0x0, portA:"consumer", portB:"provider", order:"ordered"}
addIBCChannel: 2022-06-16T14:03:04.163523Z  INFO ThreadId(01) using default configuration from '/root/.hermes/config.toml'
addIBCChannel: Error: missing chain for id (connection-0) in configuration file
{}
main.RelayPacketsAction{chain:0x0, port:"provider", channel:0x0}
2022/06/16 15:03:04 exit status 1
2022-06-16T14:03:04.336735Z  INFO ThreadId(01) using default configuration from '/root/.hermes/config.toml'
Error: supervisor error: channel provider/channel-0 on chain provider is not open
exit status 1
```

which still doesn't seem exactly the same.

**Comment by danwt** [comment]
Debugging, the first `sendTokens` on the consumer that occurs after starting the consumer chain but before relaying any packets between consumer and provider does not work as expected

https://github.com/cosmos/interchain-security/blob/80d146a02b0b7631a01cd40f026e6609ccb2f3d9/integration-tests/steps.go#L128-L143

Leads to

```bash
main.SendTokensAction{chain:0x1, from:0x0, to:0x1, amount:0x1}
"actual state"
{1: {ValBalances: {0: 10000000000,
                   1: 10000000000},
     Proposals:   nil,
     ValPowers:   nil}}
"model state"
{1: {ValBalances: {0: 9999999999,
                   1: 10000000001},
     Proposals:   nil,
     ValPowers:   nil}}
2022/06/26 14:21:47 actual state (-) not equal to model state (+):  {
  1: {
   ValBalances: {
-   0: 10000000000,
-   1: 10000000000,
+   0: 9999999999,
+   1: 10000000001,
   },
   Proposals: nil,
   ValPowers: nil,
  },
 }
exit status 1
```

raised here

https://github.com/cosmos/interchain-security/blob/80d146a02b0b7631a01cd40f026e6609ccb2f3d9/integration-tests/main.go#L63

**Comment by danwt** [comment]
Closed as not fine grained enough. See new issue

https://github.com/cosmos/interchain-security/issues/167
