### ISSUE TITLE
Set unbonding period on the consumer

### ISSUE THREAD

**Issue by mpoke** [cosmos/interchain-security#80]
Currently, the unbonding period on the consumer is hardcoded to 4 weeks, i.e.,  https://github.com/cosmos/interchain-security/blob/aaa9a3b69c285bce51e07729eb7d429cbc04b76c/x/ccv/child/types/keys.go#L44. We should use the unbonding period of the provider chain instead.

**Comment by mpoke** [comment]
One option would be for the provider to pass the unbonding period in every VSCPacket. 

@AdityaSripal Could we get this value from the provider client stored in the consumer CCV module? I'd assume that if the provider updates it's unbonding period, then it needs to update all its clients too, right?  This would also fit the logic [here](https://github.com/cosmos/interchain-security/blob/aaa9a3b69c285bce51e07729eb7d429cbc04b76c/x/ccv/parent/keeper/proposal.go#L42) where we use the provider unbonding period to create a client to the consumer.

**Comment by jtremback** [comment]
IMO, the unbonding time should be several days less than the provider chain. This is so that users will not perceive variation in unbonding times because of relaying delays.

**Comment by mpoke** [comment]
> IMO, the unbonding time should be several days less than the provider chain. This is so that users will not perceive variation in unbonding times because of relaying delays.

I agree. Once we get the unbonding period from the provider, we can subtract a few days from it and use it as the unbonding period on the consumer.
