### ISSUE TITLE
Make consumer chain governance whitelist

### ISSUE THREAD

**Issue by mpoke** [cosmos/interchain-security#82]
By default, the consumer chain should not be able to change any parameter. Every consumer chain can whitelist some parameters, which need to be approved by the provider chain while voting on the governance proposal to accept the consumer chain. 

Do we need to whitelist some parameters by default? 

This issue is related to https://github.com/cosmos/interchain-security/issues/81

**Comment by mpoke** [comment]
Needed for the democracy package (where the gov module is enabled on the consumer)

**Comment by marbar3778** [comment]
This is optional? like a consumer chain doesn't have to do this, right

**Comment by jtremback** [comment]
Closing this in favor of #284
