### ISSUE TITLE
Merge the *-ics variations into the mainline Cosmos SDK

### ISSUE THREAD

**Issue by AaronKutch** [cosmos/interchain-security#828]
Hello, we are planning to use interchain-security v1.1, and I presume that we should rebase our slightly customized SDK on `v0.45.13-ics`, which is what is used in this repo's `go.mod`. The first strange thing is a "This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository" warning. This repo is directly under `cosmos/`, so it should be a branch that completely exists on the cosmos-sdk repo? When I run `make test` on `v0.45.13-ics` (at commit d6c8598683ce1ac8efd39941109eae78b8211ddf), I get some test failures related to hashes. Is the *-ics series going to eventually be merged with the main series?

edit: I just remembered that the hash change is some spurious thing (?) related to having a high enough Go version https://github.com/cosmos/cosmos-sdk/pull/13355

**Comment by faddat** [comment]
I think that we should instead get the needed changes into the next version of the sdk. 

Well, I suppose that we need docs too, but well, here's a comparison for you:

https://docs.google.com/document/d/1ljXZkdbd7g0UjcWlTaigFycfpSlZfN3uNhTXiq6gbVE/edit?usp=sharing

**Comment by AaronKutch** [comment]
So, right now there are both PRs for 0.45.15-ics and 0.47 open with both of them seeming to be close to completion. Just to make sure, there is going to be a point release using 0.45.15-ics before 0.47?

**Comment by jtremback** [comment]
Cosmos-SDK 0.47.x already contains all needed interfaces for ICS. The 0.45.x-ics backports are being maintained since 0.47.x was not ready at launch and audit of ICS.
