### ISSUE TITLE
VSCPackets with multiple updates for the same validator

### ISSUE THREAD

**Issue by mpoke** [cosmos/interchain-security#845]
# Problem

A validator can assign on a consumer the key that it uses on the provider. In such a case, the check [here](https://github.com/cosmos/interchain-security/blob/0e04d58719d584ac519f1be673ee94a9ca5d8edd/x/ccv/provider/keeper/key_assignment.go#L406) will pass due to [this condition](https://github.com/cosmos/interchain-security/blob/0e04d58719d584ac519f1be673ee94a9ca5d8edd/x/ccv/provider/keeper/key_assignment.go#L411).  This would result then in adding the provider key to the KeyAssignmentReplacement (see [this line](https://github.com/cosmos/interchain-security/blob/0e04d58719d584ac519f1be673ee94a9ca5d8edd/x/ccv/provider/keeper/key_assignment.go#L452)). Finally, in [this block](https://github.com/cosmos/interchain-security/blob/0e04d58719d584ac519f1be673ee94a9ca5d8edd/x/ccv/provider/keeper/key_assignment.go#L520) `prevConsumerKey` and `newConsumerKey` are the same, which results in two updates for the same key in the same `VSCPacket`. 

# Closing criteria

A validator cannot assign on a consumer the key that it uses on the provider if it hasn't already assigned a key on that consumer.

**Comment by smarshall-spitzbart** [comment]
Imo it'd be worth refactoring the logic in `AssignConsumerKey` and `MustApplyKeyAssignmentToValUpdates` in the long term. It seems we could achieve the same or similar key assignment behavior with more targeted methods that have less cyclomatic complexity. Regardless it's higher prio to patch the bug without refactors for now
