### ISSUE TITLE
Bug: .proto file versioning is different from the modules used in go.mod

### ISSUE THREAD

**Issue by faddat** [cosmos/interchain-security#866]
In the SDK 45 branch of ICS, we have different versions of .proto files from the modules that we import. 

I consider this a potentially serious bug, since the .proto files define all of the types and interfaces that we later use in ics.

**Comment by jtremback** [comment]
Thanks we'll look into it. Can you link the code?

**Comment by mpoke** [comment]
Closing as no longer relevant since we have moved on to using buf and aligned with cosmos-sdk starting v0.47.x.
