### ISSUE TITLE
CI does not work for external contributors

### ISSUE THREAD

**Issue by faddat** [cosmos/interchain-security#873]
If you have a look at my PR's to this repository, you'll notice that CI has stopped working agian. 

* https://github.com/cosmos/interchain-security/pull/869
* https://github.com/cosmos/interchain-security/pull/872

this harms the experiences of developers who wish to contribute to ics

**Comment by mpoke** [comment]
@faddat The CI seems to work on both PRs. In case you experience any issues, please first just re-run the actions. In case the problem persists, please re-open this issue. Thank you.

**Comment by faddat** [comment]
Unable to reopen.

**Comment by mpoke** [comment]
@faddat Do you still have problems with the CI? Could you please provide more context?
