### ISSUE TITLE
Notional's Pull Requests: upgrade to SDKv47

### ISSUE THREAD

**Issue by pysel** [cosmos/interchain-security#874]
# Tracking

This is a tracking issue to which Notional will publish all pull requests made to #869. 

# PR list 

> <sub>Note that these PRs are not listed sequentially</sub>

* https://github.com/notional-labs/interchain-security/pull/6
* https://github.com/notional-labs/interchain-security/pull/5
* https://github.com/notional-labs/interchain-security/pull/4
* https://github.com/notional-labs/interchain-security/pull/3
* https://github.com/notional-labs/interchain-security/pull/7
* https://github.com/notional-labs/interchain-security/pull/8
* https://github.com/notional-labs/interchain-security/pull/9
* https://github.com/notional-labs/interchain-security/pull/10

**Comment by faddat** [comment]
Hey there, personally I think that this should go directly in the 47 upgrade issue or on the pull request itself. Thank you.

**Comment by mpoke** [comment]
Closing as the issue was fixed in https://github.com/cosmos/interchain-security/releases/tag/v3.0.0
