### ISSUE TITLE
Fix: e2e trace format fails on slashThrottleSteps

### ISSUE THREAD

**Issue by p-offtermatt** [cosmos/interchain-security#880]
# Problem

Extending the unit tests for the trace parser to include slashTrottleSteps fails.

# Closing criteria

The issue for the failure has been identified and fixed.

# Problem details

Writing the trace for slashThrottleSteps produces a correct-looking trace, but the parser fails when reading it from a file.

The error message is

`error reading trace from file: json: cannot unmarshal object into Go struct field ChainState.State.Proposals of type main.Proposal`

**Comment by mpoke** [comment]
Closing as fixed by https://github.com/cosmos/interchain-security/pull/903
