### ISSUE TITLE
feature: add a way to start a local testnet

### ISSUE THREAD

**Issue by p-offtermatt** [cosmos/interchain-security#896]
# Problem

Our testing infrastructure is relatively heavy-weight and hard to use outside the dedicated environment.
For example, we have scripts for starting test chains, but this is happening in docker containers, and is not easy to call by hand.
It would be beneficial to have a way to start a local testnet, to manually test changes quickly.
This is also particularly important with e.g. Hermes, which may be a bit of work to add into the existing docker setup.

I would expect any solution to allow starting a testnet with >1 validator and provider+consumer.
This base case should be set up with a single or at most a couple of commands, and this should be achievable by someone completely new to the repo.

The solution should be documented prominently in the README, since it is one of the most basic ways someone would want to interact with the repo.

# Closing criteria

There is an easy way to start a local testnet with a provider and consumer, with multiple validators for each.

**Comment by p-offtermatt** [comment]
I made a PR that solves this issue with a bash script that is relatively hacky. The issue could alternatively be solved using existing tools, e.g. https://github.com/informalsystems/gm/ or https://github.com/hyphacoop/cosmos-ansible/tree/main/examples#start-a-local-replicated-security-testnet

**Comment by p-offtermatt** [comment]
In #901 the point was made that instead of using a script and have a local testnet, we should reuse code from the e2e tests as much as possible, so this might be a better direction for this issue.

**Comment by mpoke** [comment]
@p-offtermatt is this issue still relevant?

**Comment by p-offtermatt** [comment]
This will be closed as part of #1334, as I will explain in the guidelines also how to use the e2e framework to have a local testnet to work with. I believe that should mean this stays open for now, let me adjust it.
