### ISSUE TITLE
ICS uses hermes 1.2.0

### ISSUE THREAD

**Issue by faddat** [cosmos/interchain-security#922]
The current version is 1.4.1, this issue is closed by:

* https://github.com/cosmos/interchain-security/pull/921

**Comment by smarshall-spitzbart** [comment]
For future opened issues, please follow one of the templates, or at a minimum define a clear problem that exists in the repo and why it needs to be solved. There are more important issues to work on/review than this. #919 would be very useful and helpful to solve for example
