### ISSUE TITLE
CometMock: Add reconnect and crash recovery support to CometMock

### ISSUE THREAD

**Issue by p-offtermatt** [cosmos/interchain-security#936]
Downtime can be done relatively easy with CometMock:
CometMock connects to apps. If an app goes down/stops talking to CometMock, it stops signing blocks with the key belonging to that app.
Thus, this fits seamlessly into how downtime is done in the wild right now. It also implies resistance to apps going down and being restarted, which is essential for node reconfiguration, e.g. it happens when consumer keys are reassigned in ICS e2e tests.

The concrete steps to implement this are:
1) Add detection for disconnected apps to CometMock
2) Perpetually retry disconnected apps
3) Resync disconnected apps
4) Only sign with keys associated to apps that are currently connected

**Closing Criteria**
The steps listed above are implemented so that CometMock can be used to test downtime by simply killing and restarting (or disconnecting from the network) a node.

**Comment by mpoke** [comment]
@p-offtermatt is this issue still relevant?

**Comment by p-offtermatt** [comment]
No, will close for now
