### ISSUE TITLE
Add undelegate functionality to integration tests

### ISSUE THREAD

**Issue by danwt** [cosmos/interchain-security#94]
Support an unbonding action, and verify expected state in integration tests

**Comment by danwt** [comment]
After this is done a new issue should be created to write meaningful tests using them

**Comment by danwt** [comment]
It would be nice to think about how we can get more value from this by tweaking chain/TM params (too speed things up will stil retaining some level of control)

**Comment by mpoke** [comment]
@smarshall-spitzbart Are you currently working on this issue?

**Comment by smarshall-spitzbart** [comment]
> @smarshall-spitzbart Are you currently working on this issue?

Ah yes, thank you for linking me here. My PR is still in draft stage but relevant to this issue
