### ISSUE TITLE
Upgrade proto files to SDK 0.47

### ISSUE THREAD

**Issue by MSalopek** [cosmos/interchain-security#942]
This is a sub issue for tracking required steps for upgrading proto dependencies for upgrading to cosmos-sdk v47 and IBC v7.

The ICS repo/project currently uses `buf` for building protos but since it is on sdk v45 it is using `ghcr.io/cosmos/proto-builder@0.9.0`.

Aside from that, there were many changes with regards to deps which can be checked here (with upgrade instructions):
- https://docs.cosmos.network/v0.47/migrations/upgrading#protobuf

After the repo is migrated, push ICS protos to BSR.

**Comment by faddat** [comment]
Already done
