### ISSUE TITLE
Rework `AfterUnbondingInitiated` staking hook on ICS provider

### ISSUE THREAD

**Issue by MSalopek** [cosmos/interchain-security#945]
More context in the cosmos-sdk issue https://github.com/cosmos/cosmos-sdk/issues/16042 and associated PR https://github.com/cosmos/cosmos-sdk/pull/16043

With the new behaviour in cosmos-sdk we need to address the possible panic in provider code then executing the `AfterUnbondingInitiated`. At present the provider will panic in case the `PubUnbondingOnHold` operation fails. With changes in cosmos-sdk the panic can be de-escalated into a simple error log since the sdk merges can now merge multiple `UndelegationEntries` into a single one (provided multiple entries are created for the same height).

**Comment by mpoke** [comment]
This issue is fixed in https://github.com/cosmos/interchain-security/pull/918/commits/fa543a819d285c18493db9c4bb1063621b407953 and is part of https://github.com/cosmos/interchain-security/pull/918.
