### ISSUE TITLE
Update provider to SDK 0.47

### ISSUE THREAD

**Issue by MSalopek** [cosmos/interchain-security#947]
The provider code needs to be migrated to cosmos-sdk v47 and ibc-go v47 and all breaking API changes need to be addressed.

Main concern is addressing library code, but `app.go` must also be upgraded (but new app wiring should not be used yet) because integration and MBT testing require it for creating mock chains.

e2e testing also depends on app.go but with different issues than integration and MBT tests. For e2e tests the actual binary has to be able to function correctly.

- [x] unit tests are operational
- [x] integration tests are operational
- [x] MBT/diff tests are operational
- [ ] e2e tests are operational

**Comment by faddat** [comment]
It's done, just need your help with the end-to-end tests
