### ISSUE TITLE
Dependabot automation needs to include a changelog addition to main

### ISSUE THREAD

**Issue by smarshall-spitzbart** [cosmos/interchain-security#952]
## Summary

If we want to keep a changelog in main up to date, we'll need the automated dependabot PRs to include the addition of a changelog entry in the unreleased section.

## Problem Definition

We need this so humans don't have to manually add entries to a changelog corresponding to automated PRs.

## Proposal

Build automation around this idea, see original PR -> https://github.com/cosmos/interchain-security/pull/764

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

**Comment by mpoke** [comment]
I don't think we need to add to the changelog the automated dependabot PR. The changelog should contain only bumps of major deps, i.e., SDK, IBC, Comet.
