### ISSUE TITLE
Fix delegation shares in unit tests (ibc-go/testing/app.go) 

### ISSUE THREAD

**Issue by danwt** [cosmos/interchain-security#99]
This function is used for all chains

https://github.com/informalsystems/ibc-go/blob/1f45da82fc7573ec5620635633e96a4b72dea249/testing/app.go#L73-L95

The bondAmt

```go
bondAmt := sdk.TokensFromConsensusPower(1, powerReduction) // 1'000'000
```

does not correspond to having just 1 share

```go
...
			Tokens:            bondAmt,
			DelegatorShares:   sdk.OneDec(),
			Description:       stakingtypes.Description{},
...
```

```go
delegations = append(delegations, stakingtypes.NewDelegation(genAccs[0].GetAddress(), val.Address.Bytes(), sdk.OneDec()))
```

and shares are supposed to be 1-1 with tokens (before any rewards or slashing) ([code](https://github.com/cosmos/cosmos-sdk/blob/16c8e2739f76b2241c095a12a11361cc03b8bd04/x/staking/types/validator.go#L379-L399))

```go
// AddTokensFromDel adds tokens to a validator
func (v Validator) AddTokensFromDel(amount sdk.Int) (Validator, sdk.Dec) {
	// calculate the shares to issue
	var issuedShares sdk.Dec
	if v.DelegatorShares.IsZero() {
		// the first delegation to a validator sets the exchange rate to one
		issuedShares = amount.ToDec()
	} else {
		shares, err := v.SharesFromTokens(amount)
		if err != nil {
			panic(err)
		}

		issuedShares = shares
	}

	v.Tokens = v.Tokens.Add(amount)
	v.DelegatorShares = v.DelegatorShares.Add(issuedShares)

	return v, issuedShares
}
```

this is quite confusing for writing tests. I think some of our tests might work by 'accident'. They're probably still good tests but they will need fixing.

**Comment by jtremback** [comment]
@danwt I am presuming that this can be closed, right?

**Comment by danwt** [comment]
Actually I'm not sure. I'll reopen if needs be. It's very minor anyway. We could even mark it won't fix.
