### ISSUE TITLE
`make proto-all` fails

### ISSUE THREAD

**Issue by freak12techno** [cosmos/interchain-security#993]
## Summary of Bug

Running `make proto-all` fails, which is required to generate .go files from Protobuf.

## Version

 ```
commit eaa34dc7f922d7d4b34b660f1a14faa0993e3508 (HEAD -> add-query-for-assigned-keys, origin/main, origin/HEAD)
Author: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Date:   Wed May 31 07:16:53 2023 -0700
```

## Steps to Reproduce

```
➜  interchain-security git:(add-query-for-assigned-keys) ✗ make proto-all
Formatting Protobuf files
make: lint: No such file or directory
make: *** [proto-lint] Error 1
```

I assume that's because of DOCKER_BUF not initialized:
```
proto-lint:
	@$(DOCKER_BUF) lint --error-format=json
```

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

**Comment by MSalopek** [comment]
Thanks for raising this issue!

The problematic step is `make proto-lint` that runs in `make proto-all`.

`make proto-format` and `make proto-gen` function as expected.

`make proto-gen` will run the compilation step, I would advise using that command until the issue is resolved.

**Comment by MSalopek** [comment]
To continue, in the coming weeks we will upgrade the proto tooling to be in line with `cosmos-sdk` which uses `buf` and does not rely on `third_party` directory.

If you don't mind I would like to close this issue since it will be resolved without any action necessary.

@freak12techno 
Do you agree with closing the issue?

**Comment by freak12techno** [comment]
Sounds ok. To clarify, would there be a lint command to prettify your proto files in the future?

**Comment by MSalopek** [comment]
> Sounds ok. To clarify, would there be a lint command to prettify your proto files in the future?

Yes, that is correct.

While working on versions using `cosmos-sdk < v47` please use `make proto-format` and `make proto-gen`.

I'm closing the issue.

If you find other issues, feel free to tag me to reopen the issue and continue the discussion.

Thanks once again for pointing this out!
